BAOBAB: CO_Place Class Reference
CO_Place Class Reference
Public Member Functions
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_owner_id=NULL, $in_tags_array=NULL, $in_longitude=NULL, $in_latitude=NULL)
set_address_elements ($in_tags, $dont_save=false)
set_address_element ($in_index, $in_value, $dont_save=false)
set_address_element_by_key ($in_key, $in_value, $dont_save=false)
get_address_element_by_index ($in_index)
lookup_address ()
geocode_long_lat ()
get_readable_address ($with_venue=true)
set_tags_from_address_elements ()
get_address_elements ()
Public Member Functions inherited from CO_LL_Location
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_owner_id=NULL, $in_tags_array=NULL, $in_longitude=NULL, $in_latitude=NULL, $in_fuzz_factor=NULL, $in_can_see_through_the_fuzz=NULL)
load_from_db ($in_db_result)
update_db ()
set_longitude ($in_new_value)
set_latitude ($in_new_value)
fuzz_factor ()
is_fuzzy ()
set_fuzz_factor ($in_new_value)
raw_longitude ()
raw_latitude ()
longitude ()
latitude ()
set_can_see_through_the_fuzz ($in_id)
can_see_through_the_fuzz ()
i_can_see_clearly_now ()
Public Member Functions inherited from CO_Main_DB_Record
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_owner_id=NULL, $in_tags_array=NULL)
set_owner_id ($in_new_id)
set_tags ($in_tags_array)
set_tag ($in_tag_index, $in_tag_value)
get_payload ()
set_payload ($in_payload)
owner_id ()
tags ()
Public Member Functions inherited from A_CO_DB_Table_Base
__construct ($in_db_object=NULL, $in_db_result=NULL)
set_batch_mode ()
clear_batch_mode ()
id ()
lock ()
locked ()
danger_will_robinson_danger_clear_id ()
user_can_read ()
user_can_write ()
set_read_security_id ($in_new_id)
set_write_security_id ($in_new_id)
set_name ($in_new_value)
delete_from_db ()
reload_from_db ()
get_access_object ()
get_lang ()
set_lang ($in_lang_id=NULL)
Public Attributes
$address_elements = Array()
These are the address elements we use for creating lookup addresses.
$google_geocode_uri_prefix = NULL
This is the Geocode URI for the Google Geocode.
$google_lookup_uri_prefix = NULL
This is the lookup URI for the Google reverse Geocode.
$region_bias = NULL
This can be set by subclasses in order to set a region bias.
Public Attributes inherited from A_CO_DB_Table_Base
$class_description
This is a description of the class (not the instance).
$instance_description
This is a description that describes the instance.
$last_access
This is a UNIX epoch date that describes the last modification. The default is UNIX Day Two (in case of UTC timezone issues).
$name
This is the "object_name" string field.
$read_security_id
This is a single integer, defining the security ID required to view the record. If it is 0, then it is "open.".
$write_security_id
This is a single integer, defining the required security token to modify the record. If it is 0, then any logged-in user can modify.
$context
This is a mixed associative array, containing fields for the object.
$error
If there is an error, it is contained here, in a LGV_Error instance.
Protected Member Functions
_get_address_element_labels ()
Protected Member Functions inherited from CO_LL_Location
_default_setup ()
_build_parameter_array ()
_km_per_degree ()
_fuzz_me ()
Protected Member Functions inherited from A_CO_DB_Table_Base
_badger_serialize ($in_data)
_badger_unserialize ($in_data)
_write_to_db ()
_seppuku ()
Additional Inherited Members
Static Public Attributes inherited from CO_Main_DB_Record
static $s_table_name = 'co_data_nodes'
Protected Attributes inherited from CO_LL_Location
$_longitude
$_latitude
Protected Attributes inherited from CO_Main_DB_Record
$_owner_id
$_tags
Protected Attributes inherited from A_CO_DB_Table_Base
$_db_object
This is the actual database object that "owns" this instance. It should not be exposed beyond this class or subclasses, thereof.
$_id
This is the within-table unique ID of this record.
$_batch_mode
If this is true, then the write_record call will not be made in update_db. It will be done when clear_batch_mode() is called, instead.
Detailed Description
This is a specialization of the location class. It adds support for US addresses, and uses the first eight tags for this.
Definition at line 46 of file co_place.class.php.
Constructor & Destructor Documentation
__construct()
CO_Place::__construct ($in_db_object = NULL, $in_db_result = NULL, $in_owner_id = NULL, $in_tags_array = NULL, $in_longitude = NULL, $in_latitude = NULL)
Constructor (Initializer)
Parameters
$in_db_object The database object for this instance.
$in_db_result The database row for this instance (associative array, with database keys).
$in_owner_id The ID of the object (in the database) that "owns" this instance.
$in_tags_array An array of up to 10 strings, with address information in the first 8. Order is important:
0: Venue
1: Street Address
2: Extra Information
3: Town
4: County
5: State
6: ZIP Code
7: Nation
Associative keys are not used. The array should be in that exact order.
Parameters
$in_longitude An initial longitude value.
$in_latitude An initial latitude value.
Reimplemented in CO_US_Place_Collection, CO_US_Place, and CO_Place_Collection.
Definition at line 77 of file co_place.class.php.
{
         parent::__construct($in_db_object, $in_db_result, $in_owner_id, $in_tags_array, $in_longitude, $in_latitude);
         $this->class_description = "This is a 'Place' Class for General Addresses.";
         $this->instance_description = isset($this->name) && $this->name ? "$this->name ($this->_longitude, $this->_latitude)" : "($this->_longitude, $this->_latitude)";
         $this->set_address_elements($this->tags(), true);
         $bias = (NULL != $this->region_bias) ? 'region='.$this->region_bias.'&' : '';
         $this->google_geocode_uri_prefix = 'https://maps.googleapis.com/maps/api/geocode/json?'.$bias.'key='.CO_Config::$google_api_key.'&address=';
         $this->google_lookup_uri_prefix = 'https://maps.googleapis.com/maps/api/geocode/json?'.$bias.'key='.CO_Config::$google_api_key.'&latlng=';
     }
References $region_bias, set_address_elements(), and CO_Main_DB_Record\tags().
Member Function Documentation
_get_address_element_labels()
CO_Place::_get_address_element_labels () protected
This fetches string labels to be used as keys for the fixed tags.
Returns
an array of strings, which will correspond to the first eight tags.
Reimplemented in CO_US_Place.
Definition at line 59 of file co_place.class.php.
{
         return Array(
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_0,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_1,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_2,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_3,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_4,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_5,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_6,
                         CO_CHAMELEON_Lang_Common::$chameleon_co_place_tag_7
                     );
     }
References CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_0, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_1, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_2, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_3, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_4, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_5, CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_6, and CO_CHAMELEON_Lang_Common\$chameleon_co_place_tag_7.
Referenced by geocode_long_lat(), get_address_element_by_index(), get_address_elements(), get_readable_address(), set_address_element(), set_address_element_by_key(), set_address_elements(), and set_tags_from_address_elements().
geocode_long_lat()
CO_Place::geocode_long_lat ()
This will do a geocode, using the Google Geocode API, of the object's long/lat, and will return the address (in an associative array). This requires that CO_Config::$google_api_key be set to a valid API key with the Google Geocode service enabled.
Returns
Definition at line 260 of file co_place.class.php.
{
         $uri = $this->google_lookup_uri_prefix . urlencode($this->raw_latitude()) . ',' . urlencode($this->raw_longitude());
         $http_status = '';
         $error_catcher = '';
         $resulting_json = json_decode(CO_Chameleon_Utils::call_curl($uri, false, $http_status, $error_catcher));
         if (isset($resulting_json) && $resulting_json &&isset($resulting_json->results) && is_array($resulting_json->results) && count($resulting_json->results)) {
             if (isset($resulting_json->results[0]->address_components) && is_array($resulting_json->results[0]->address_components) && count($resulting_json->results[0]->address_components)) {
                 $address_components = $resulting_json->results[0]->address_components;
                 $labels = $this->_get_address_element_labels();
                 $ret = Array($labels[0] => '', $labels[1] => '', $labels[3] => '', $labels[4] => '', $labels[5] => '', $labels[6] => '');
                 if (isset($labels[7])) {
                     $ret[$labels[7]] = '';
                 }
                 foreach ($address_components as $component) {
                     $int_key = $component->types[0];
                     switch ($int_key) {
                         case 'premise':
                             if ($ret[$labels[0]]) {
                                 $ret[$labels[0]] = ' '.$ret[$labels[0]];
                             }
                             $ret[$labels[0]] = strval($component->long_name).$ret[$labels[0]];
                         break;
                         case 'street_number':
                             if ($ret[$labels[1]]) {
                                 $ret[$labels[1]] = ' '.$ret[$labels[1]];
                             }
                             $ret[$labels[1]] = strval($component->short_name).$ret[$labels[1]];
                         break;
                         case 'route':
                             if ($ret[$labels[1]]) {
                                 $ret[$labels[1]] .= ' ';
                             }
                             $ret[$labels[1]] .= strval($component->long_name);
                         break;
                         case 'locality':
                             $ret[$labels[3]] = strval($component->long_name);
                         break;
                         case 'administrative_area_level_1':
                             $ret[$labels[5]] = strval($component->short_name);
                         break;
                         case 'administrative_area_level_2':
                             $ret[$labels[4]] = strval($component->short_name);
                         break;
                         case 'postal_code':
                             if ($ret[$labels[6]]) {
                                 $ret[$labels[6]] = '-'.$ret[$labels[6]];
                             }
                             $ret[$labels[6]] = strval($component->short_name).$ret[$labels[6]];
                         break;
                         case 'postal_code_suffix':
                             if ($ret[$labels[6]]) {
                                 $ret[$labels[6]] .= '-';
                             }
                             $ret[$labels[6]] .= strval($component->short_name);
                         break;
                         case 'country':
                             if (isset($labels[7])) {
                                 $ret[$labels[7]] = strval($component->short_name);
                             }
                         break;
                     }
                 }
                 return $ret;
             }
         }
         $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_place_error_code_failed_to_geocode,
                                         CO_CHAMELEON_Lang::$co_place_error_name_failed_to_geocode,
                                         CO_CHAMELEON_Lang::$co_place_error_desc_failed_to_geocode);
         return NULL;
     }
References CO_CHAMELEON_Lang_Common\$co_place_error_code_failed_to_geocode, CO_CHAMELEON_Lang\$co_place_error_desc_failed_to_geocode, CO_CHAMELEON_Lang\$co_place_error_name_failed_to_geocode, _get_address_element_labels(), CO_Chameleon_Utils\call_curl(), CO_LL_Location\raw_latitude(), and CO_LL_Location\raw_longitude().
get_address_element_by_index()
CO_Place::get_address_element_by_index ($in_index)
Returns
the indexed address element, or NULL.
Parameters
$in_index The 0-based index we're looking for.
Definition at line 213 of file co_place.class.php.
{
         $ret = NULL;
         $labels = $this->_get_address_element_labels();
         if ((0 <= $in_index) && ($in_index < count($labels))) {
             $key = $labels[$in_index];
             $ret = $this->address_elements[$key];
         }
         return $ret;
     }
References _get_address_element_labels().
get_address_elements()
CO_Place::get_address_elements ()
Returns
the address elements, in an associative array.
Reimplemented in CO_US_Place.
Definition at line 435 of file co_place.class.php.
{
         $ret = [];
         $labels = $this->_get_address_element_labels();
         for ($i = 0; $i < count($labels); $i++) {
             $key = $labels[$i];
             if (isset($this->address_elements[$key]) && trim($this->address_elements[$key])) {
                 $ret[$key] = trim($this->address_elements[$key]);
             }
         }
         return $ret;
     }
References _get_address_element_labels().
get_readable_address()
CO_Place::get_readable_address ($with_venue = true)
Returns
the address, in a "readable" format.
Parameters
$with_venue If false, then only the street address/town/state/nation will be displayed. That makes this better for geocoding. Default is true.
Definition at line 343 of file co_place.class.php.
{
         $ret = '';
         $tag_key_array = $this->_get_address_element_labels();
         if (isset($tag_key_array) && is_array($tag_key_array) && count($tag_key_array)) {
             if ($with_venue && isset($tag_key_array[0]) && isset($this->address_elements[$tag_key_array[0]])) {
                 $ret = $this->address_elements[$tag_key_array[0]];
             }
             if ($with_venue && isset($tag_key_array[2]) && isset($this->address_elements[$tag_key_array[2]]) && $this->address_elements[$tag_key_array[2]]) {
                 $open_paren = false;
                 if ($ret) {
                     $ret .= ' (';
                     $open_paren = true;
                 }
                 $ret .= $this->address_elements[$tag_key_array[2]];
                 if ($open_paren) {
                     $ret .= ')';
                 }
             }
             if (isset($tag_key_array[1]) && isset($this->address_elements[$tag_key_array[1]]) && $this->address_elements[$tag_key_array[1]]) {
                 if ($ret) {
                     $ret .= ', ';
                 }
                 $ret .= $this->address_elements[$tag_key_array[1]];
             }
             if (isset($tag_key_array[3]) && isset($this->address_elements[$tag_key_array[3]]) && $this->address_elements[$tag_key_array[3]]) {
                 if ($ret) {
                     $ret .= ', ';
                 }
                 $ret .= $this->address_elements[$tag_key_array[3]];
             }
             if (isset($tag_key_array[5]) && isset($this->address_elements[$tag_key_array[5]]) && $this->address_elements[$tag_key_array[5]]) {
                 if ($ret) {
                     $ret .= ', ';
                 }
                 $ret .= $this->address_elements[$tag_key_array[5]];
             }
             if (isset($tag_key_array[6]) && isset($this->address_elements[$tag_key_array[6]]) && $this->address_elements[$tag_key_array[6]]) {
                 if ($ret) {
                     $ret .= ' ';
                 }
                 $ret .= $this->address_elements[$tag_key_array[6]];
             }
             if (isset($tag_key_array[7]) && isset($this->address_elements[$tag_key_array[7]]) && $this->address_elements[$tag_key_array[7]]) {
                 if ($ret) {
                     $ret .= ' ';
                 }
                 $ret .= $this->address_elements[$tag_key_array[7]];
             }
         }
         return $ret;
     }
References _get_address_element_labels().
Referenced by lookup_address().
lookup_address()
CO_Place::lookup_address ()
This will do a reverse geocode, using the Google Geocode API, of the object's address, and will return the long/lat (in an associative array). This requires that CO_Config::$google_api_key be set to a valid API key with the Google Geocode service enabled.
Returns
Definition at line 234 of file co_place.class.php.
{
         $uri = $this->google_geocode_uri_prefix.urlencode($this->get_readable_address(false));
         $http_status = '';
         $error_catcher = '';
         $resulting_json = json_decode(CO_Chameleon_Utils::call_curl($uri, false, $http_status, $error_catcher));
         if (isset($resulting_json) && $resulting_json &&isset($resulting_json->results) && is_array($resulting_json->results) && count($resulting_json->results)) {
             if (isset($resulting_json->results[0]->geometry) && isset($resulting_json->results[0]->geometry->location) && isset($resulting_json->results[0]->geometry->location->lng) && isset($resulting_json->results[0]->geometry->location->lat)) {
                 return Array( 'longitude' => floatval($resulting_json->results[0]->geometry->location->lng), 'latitude' => floatval($resulting_json->results[0]->geometry->location->lat));
             }
         }
         $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_place_error_code_failed_to_lookup,
                                         CO_CHAMELEON_Lang::$co_place_error_name_failed_to_lookup,
                                         CO_CHAMELEON_Lang::$co_place_error_desc_failed_to_lookup);
         return NULL;
     }
References CO_CHAMELEON_Lang_Common\$co_place_error_code_failed_to_lookup, CO_CHAMELEON_Lang\$co_place_error_desc_failed_to_lookup, CO_CHAMELEON_Lang\$co_place_error_name_failed_to_lookup, CO_Chameleon_Utils\call_curl(), and get_readable_address().
set_address_element()
CO_Place::set_address_element ($in_index, $in_value, $dont_save = false)
This sets the indexed address_element property, as per the provided string. This can also update the tag.
Returns
true, if $dont_save was false, and the tags were successfully saved.
Parameters
$in_index The 0-based index of the value to set.
$in_value The value to set to the address element string.
$dont_save If true, then the DB update will not be called.
Definition at line 159 of file co_place.class.php.
{
         $ret = false;
         $in_index = intval($in_index);
         $labels = $this->_get_address_element_labels();
         if ((0 <= $in_index) && ($in_index < count($labels))) {
             $key = $labels[$in_index];
             $in_value = strval($in_value);
             $this->address_elements[$key] = $in_value;
             $this->_tags[$in_index] = $in_value;
             if (!$dont_save) {
                 $ret = $this->update_db();
             }
         }
         return $ret;
     }
References _get_address_element_labels(), and CO_LL_Location\update_db().
Referenced by set_address_element_by_key(), and set_address_elements().
set_address_element_by_key()
CO_Place::set_address_element_by_key ($in_key, $in_value, $dont_save = false)
This sets the address_element property, as per the provided string, and indexed by the associative key. This can also update the tag.
Returns
true, if $dont_save was false, and the tags were successfully saved.
Parameters
$in_key The string, with the element key.
$in_value The value to set to the address element string.
$dont_save If true, then the DB update will not be called.
Definition at line 190 of file co_place.class.php.
{
         $ret = false;
         $in_index = intval($in_index);
         $labels = $this->_get_address_element_labels();
         for ($i = 0; $i < count($labels); $i++) {
             if ($labels[$i] == $in_key) {
                 $ret = $this->set_address_element($i, $in_value, $dont_save);
                 break;
             }
         }
         return $ret;
     }
References _get_address_element_labels(), and set_address_element().
set_address_elements()
CO_Place::set_address_elements ($in_tags, $dont_save = false)
This sets the address_elements property, as per the provided array of strings. This can also update the tags.
Returns
true, if $dont_save was false, and the tags were successfully saved.
Parameters
$in_tags An array of up to 8 strings, with the new address information. Order is important:
0: Venue
1: Street Address
2: Extra Information
3: Town
4: County
5: State
6: ZIP Code
7: Nation
Associative keys are not used. The array should be in that exact order.
Parameters
$dont_save If true, then the DB update will not be called.
Definition at line 115 of file co_place.class.php.
{
         $ret = false;
         $this->address_elements = Array();
         $labels = $this->_get_address_element_labels();
         for ($i = 0; $i < count($labels); $i++) {
             $tag_value = '';
             if (test_is_assoc($in_tags)) {
                 $tag_value = isset($in_tags[$labels[$i]]) ? $in_tags[$labels[$i]] : '';
             } else {
                 $tag_value = isset($in_tags[$i]) ? $in_tags[$i] : '';
             }
             $this->set_address_element($i, $tag_value, true);
         }
         if (!$dont_save) {
             $ret = $this->update_db();
         }
         return $ret;
     }
References _get_address_element_labels(), set_address_element(), test_is_assoc(), and CO_LL_Location\update_db().
Referenced by __construct().
set_tags_from_address_elements()
CO_Place::set_tags_from_address_elements ()
This updates the tags (and saves them to the DB) as per our internal address_elements property.
Returns
true, if successful.
Definition at line 419 of file co_place.class.php.
{
         $new_tags = $this->tags;
         $labels = $this->_get_address_element_labels();
         for ($i = 0; $i < count($labels); $i++) {
             $key = $labels[$i];
             $new_tags[$key] = $this->address_elements[$key];
         }
         return $this->set_tags($new_tags);
     }
References _get_address_element_labels(), and CO_Main_DB_Record\set_tags().
Member Data Documentation
$address_elements
CO_Place::$address_elements = Array()
These are the address elements we use for creating lookup addresses.
Definition at line 47 of file co_place.class.php.
$google_geocode_uri_prefix
CO_Place::$google_geocode_uri_prefix = NULL
This is the Geocode URI for the Google Geocode.
Definition at line 48 of file co_place.class.php.
$google_lookup_uri_prefix
CO_Place::$google_lookup_uri_prefix = NULL
This is the lookup URI for the Google reverse Geocode.
Definition at line 49 of file co_place.class.php.
$region_bias
CO_Place::$region_bias = NULL
This can be set by subclasses in order to set a region bias.
Definition at line 50 of file co_place.class.php.
Referenced by __construct().