BAOBAB: CO_Andisol Class Reference
CO_Andisol Class Reference
Public Member Functions
__construct ($in_login_string_id=NULL, $in_hashed_password=NULL, $in_raw_password=NULL, $in_api_key=NULL)
get_cobra_instance ()
get_chameleon_instance ()
valid ()
logged_in ()
manager ()
god ()
current_login ()
current_user ()
i_have_this_token ($in_token_to_test)
get_login_item ($in_login_integer_id=NULL)
get_login_item_by_login_string ($in_login_string_id)
get_user_from_login_string ($in_login_string_id)
who_can_see ($in_test_target)
get_data_access_class_by_id ($in_id)
get_security_access_class_by_id ($in_id)
generic_search ($in_search_parameters=NULL, $or_search=false, $page_size=0, $initial_page=0, $and_writeable=false, $count_only=false, $ids_only=false)
location_search ($in_longitude_degrees, $in_latitude_degrees, $in_radius_kilometers, $page_size=0, $initial_page=0, $and_writeable=false, $count_only=false, $ids_only=false)
get_all_users ($and_write=false)
get_all_login_users ($and_write=false)
get_all_standalone_users ($and_write=false)
tag_search ($in_tags_associative_array, $in_or_search=false, $page_size=0, $initial_page=0, $and_writeable=false, $count_only=false, $ids_only=false)
get_user_from_login ($in_login_integer_id=NULL, $in_make_user_if_necessary=false)
make_standalone_user ()
create_new_standard_login ($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids=0)
create_new_manager_login ($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids=0)
create_new_user ($in_login_string_id, $in_password=NULL, $in_display_name=NULL, $in_security_tokens=NULL, $in_read_security_id=NULL, $is_manager=false, $in_create_this_many_personal_ids=0)
delete_user ($in_login_string_id, $with_extreme_prejudice=false)
get_all_logins ($and_write=false, $in_login_string_id=NULL, $in_login_integer_id=NULL)
convert_login ($in_login_id, $in_is_login_manager=false)
make_security_token ()
get_multiple_data_records_by_id ($in_id_array)
get_single_data_record_by_id ($in_id)
create_general_data_item ($in_read_security_id=1, $in_write_security_id=NULL, $in_classname='CO_Main_DB_Record')
create_collection ($in_initial_item_ids=[], $in_read_security_id=1, $in_write_security_id=NULL, $in_classname='CO_Collection')
delete_item_by_id ($in_item_id_integer)
get_value_for_key ($in_key, $in_classname='CO_KeyValue_CO_Collection')
key_is_unique ($in_key, $in_classname='CO_KeyValue_CO_Collection')
get_object_for_key ($in_key)
delete_key ($in_key, $in_classname='CO_KeyValue_CO_Collection')
set_value_for_key ($in_key, $in_value, $in_classname='CO_KeyValue_CO_Collection')
create_ll_location ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor=NULL, $in_see_clearly_id=NULL, $in_read_security_id=1, $in_write_security_id=NULL, $in_classname='CO_LL_Location')
create_place ($auto_resolve=true, $in_venue=NULL, $in_street_address=NULL, $in_municipality=NULL, $in_county=NULL, $in_province=NULL, $in_postal_code=NULL, $in_nation=NULL, $in_extra_info=NULL, $in_longitude_degrees=NULL, $in_latitude_degrees=NULL, $in_fuzz_factor=NULL, $in_see_clearly_id=NULL, $in_read_security_id=1, $in_write_security_id=NULL, $in_classname='CO_Place')
create_ll_place ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor=NULL, $in_see_clearly_id=NULL, $in_read_security_id=1, $in_write_security_id=NULL, $in_classname='CO_Place')
create_ll_us_place ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor=NULL, $in_see_clearly_id=NULL, $in_read_security_id=1, $in_write_security_id=NULL)
create_place_collection ($auto_resolve=true, $in_venue=NULL, $in_street_address=NULL, $in_municipality=NULL, $in_county=NULL, $in_province=NULL, $in_postal_code=NULL, $in_nation=NULL, $in_extra_info=NULL, $in_longitude_degrees=NULL, $in_latitude_degrees=NULL, $in_fuzz_factor=NULL, $in_see_clearly_id=NULL, $in_read_security_id=1, $in_write_security_id=NULL)
get_available_tokens ()
count_all_login_objects_with_access ($in_security_token)
get_all_visible_users ()
get_all_visible_logins ()
can_i_see_this_data_record ($in_id)
can_i_see_this_security_record ($in_id)
get_all_login_objects_with_access ($in_security_token, $and_write=false)
get_all_user_objects_with_access ($in_security_token)
fetch_backup ()
check_login_exists_by_login_string ($in_login_id_string)
make_new_blank_record ($in_classname)
get_personal_security_ids ()
set_personal_ids ($in_login_id, $in_personal_ids=[])
get_all_personal_ids_except_for_id ($in_id=0)
get_logins_with_personal_ids ()
is_this_a_personal_id ($in_id)
is_this_a_login_id ($in_id)
add_personal_token_from_current_login ($in_to_id, $in_id)
remove_personal_token_from_this_login ($in_to_id, $in_id)
get_logins_that_have_any_of_my_ids ()
get_remaining_time ($in_login_id=NULL)
Public Attributes
$version
The version indicator.
$error
Any errors that occured are kept here.
Protected Member Functions
_create_db_object ($in_classname, $in_read_security_id=1, $in_write_security_id=NULL)
_make_security_token ()
Protected Attributes
$_chameleon_instance = NULL
This is the CHAMELEON instance.
$_cobra_instance = NULL
This is the COBRA instance.
Detailed Description
This class is the principal Model layer interface for the Rift Valley Platform. You instantiate an instance of this class, and it, in turn, will create an instance of CHAMELEON/BADGER, and, possibly, an instance of COBRA. That establishes a connection to the lower level data storage and security infrastructure.
You are to use this class for ALL access to the lower level functionality.
Definition at line 50 of file co_andisol.class.php.
Constructor & Destructor Documentation
__construct()
CO_Andisol::__construct ($in_login_string_id = NULL, $in_hashed_password = NULL, $in_raw_password = NULL, $in_api_key = NULL)
The constructor.
Default for parameters is NULL, but not supplying them will result in a non-logged-in instance of ANDISOL.
Parameters
$in_login_string_id OPTIONAL: The String login ID
$in_hashed_password OPTIONAL: The password, crypt-hashed
$in_raw_password The password, cleartext.
$in_api_key An API key, for REST.
Definition at line 150 of file co_andisol.class.php.
{
         $this->class_description = 'The main model interface class.';
         $this->version = __ANDISOL_VERSION__;
         $this->error = NULL;
         // The first thing we do, is set up any login instance, as well as any possible COBRA instance.
         $chameleon_instance = new CO_Chameleon($in_login_string_id, $in_hashed_password, $in_raw_password, $in_api_key);
         if (isset($chameleon_instance) && ($chameleon_instance instanceof CO_Chameleon)) {
             if ($chameleon_instance->valid) {
                 $this->_chameleon_instance = $chameleon_instance;
                 $login_item = $chameleon_instance->get_login_item();
                 // COBRA requires a manager (or God).
                 if (isset($login_item) && ($chameleon_instance->god_mode() || ($login_item instanceof CO_Login_Manager))) {
                     $cobra_instance = CO_Cobra::make_cobra($chameleon_instance);
                     if (isset($cobra_instance) && ($cobra_instance instanceof CO_Cobra)) {
                         $this->_cobra_instance = $cobra_instance;
                     } elseif (isset($cobra_instance) && ($cobra_instance->error instanceof LGV_Error)) {
                         $this->error = $cobra_instance->error;
                     }
                 }
             } elseif (isset($chameleon_instance) && ($chameleon_instance->error instanceof LGV_Error)) {
                 $this->error = $chameleon_instance->error;
             }
         }
         // At this point, we have (or have not) logged in, and any infrastructure for logged-in operations is in place.
     }
References __ANDISOL_VERSION__, and CO_Cobra\make_cobra().
Member Function Documentation
_create_db_object()
CO_Andisol::_create_db_object ($in_classname, $in_read_security_id = 1, $in_write_security_id = NULL) protected
This creates an uninitialized object, based upon the passed-in class.
Returns
a new instance of the class.
Parameters
$in_classname REQUIRED: A classname to use.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
Definition at line 67 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->logged_in()) {
             $instance = $this->get_chameleon_instance()->make_new_blank_record($in_classname);
             if (isset($instance) && ($instance instanceof $in_classname)) {
                 // If we did not get a specific read security ID, then we assume 1.
                 if (!isset($in_read_security_id)) {
                     $in_read_security_id = 1;
                 }
                 // If we did not get a specific write security ID, then we assume the logged-in user ID.
                 if (!isset($in_write_security_id) || !intval($in_write_security_id)) {
                     $in_write_security_id = $this->get_chameleon_instance()->get_login_id();
                 }
                 if ($instance->set_read_security_id($in_read_security_id)) {
                     if ($instance->set_write_security_id($in_write_security_id)) {
                         $ret = $instance;
                     } elseif (isset($instance) && ($instance instanceof A_CO_DB_Table_Base)) {
                         if ($instance->error) {
                             $this->error = $instance->error;
                         }
                         $instance->delete_from_db();
                     }
                 } elseif (isset($instance) && ($instance instanceof A_CO_DB_Table_Base)) {
                     if ($instance->error) {
                         $this->error = $instance->error;
                     }
                     $instance->delete_from_db();
                 }
             } elseif (isset($instance) && ($instance instanceof A_CO_DB_Table_Base)) {
                 if ($instance->error) {
                     $this->error = $instance->error;
                 }
                 $instance->delete_from_db();
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_chameleon_instance(), and logged_in().
Referenced by create_general_data_item().
_make_security_token()
CO_Andisol::_make_security_token () protected
This creates a new security token. Only managers or God can do this.
Returns
an integer, with the new token. NULL, if this did not work.
Definition at line 126 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->manager()) {
             $ret = $this->get_cobra_instance()->make_security_token();
             if (0 == $ret) {
                 $ret = NULL;
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_cobra_instance(), and manager().
Referenced by make_security_token().
add_personal_token_from_current_login()
CO_Andisol::add_personal_token_from_current_login ($in_to_id, $in_id)
This adds a personal token from one ID's pool, to the regular ID pool of another ID.
Returns
true, if the operation was successful.
Parameters
$in_to_id The ID of the object we are affecting.
$in_id The ID (personal token) to be added.
Definition at line 1918 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->add_personal_token_from_current_login($in_to_id, $in_id);
     }
References get_chameleon_instance().
can_i_see_this_data_record()
CO_Andisol::can_i_see_this_data_record ($in_id)
This returns true, if the current user at least has read access to the Data DB record whose ID is provided..
This is "security safe," so that means that if the user does not have rights to the row, or the row does not exist, they will get false.
Returns
a boolean, true, if the user has read access to an existing record in the Data database.
Parameters
$in_id This is the ID of the record to check.
Definition at line 1755 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->can_i_see_this_data_record($in_id);
     }
References get_chameleon_instance().
Referenced by get_data_access_class_by_id().
can_i_see_this_security_record()
CO_Andisol::can_i_see_this_security_record ($in_id)
This returns true, if the current user at least has read access to the Security DB record whose ID is provided..
This is "security safe," so that means that if the user does not have rights to the row, or the row does not exist, they will get false.
Returns
a boolean, true, if the user has read access to an existing record in the Security database.
Parameters
$in_id This is the ID of the record to check.
Definition at line 1768 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->can_i_see_this_security_record($in_id);
     }
References get_chameleon_instance().
check_login_exists_by_login_string()
CO_Andisol::check_login_exists_by_login_string ($in_login_id_string)
Returns
true, if the given login exists, false, if not, but NULL, if there is no security DB (we're not logged in). NOTE: This is not subject to security vetting.
Parameters
$in_login_id_string The string login ID to check
Definition at line 1816 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->check_login_exists_by_login_string($in_login_id_string);
     }
References get_chameleon_instance().
convert_login()
CO_Andisol::convert_login ($in_login_id, $in_is_login_manager = false)
This is the public function used to convert a login to (or from) a manager, in the security database. This can only be called from a login manager. The user is not affected, and the login IDs (tokens) are also left "as is."
Returns
the converted instance.
Parameters
$in_login_id The login ID as text. This must be for a login that can be managed by the current manager.
$in_is_login_manager If true, then this is a "promotion" to a a manager. If false (default), then this is a "demotion" to a standard user.
Definition at line 987 of file co_andisol.class.php.
{
         return $this->get_cobra_instance()->convert_login($in_login_id, $in_is_login_manager);
     }
References get_cobra_instance().
count_all_login_objects_with_access()
CO_Andisol::count_all_login_objects_with_access ($in_security_token)
You give a security ID, and you will get a count of all login objects that have that token in their list (or are of that ID).
This is not restricted, and will count logins that we don't otherwise know about.
It does not count the "God" admin, which always has access.
Returns
an integer, with the total count of logins with access to the ID. -1, if we are not allowed to see the token.
Parameters
$in_security_token An integer, with the requested security token.
Definition at line 1726 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->count_all_login_objects_with_access($in_security_token);
     }
References get_chameleon_instance().
create_collection()
CO_Andisol::create_collection ($in_initial_item_ids = [], $in_read_security_id = 1, $in_write_security_id = NULL, $in_classname = 'CO_Collection')
This creates new generic collection object.
Returns
a new instance of the class.
Parameters
$in_initial_item_ids OPTIONAL: An array of integers, containing the data database IDs of existing items that are to be added to the collection. Default is empty.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
$in_classname OPTIONAL: This is the name of the class we want to create. It's optional, but leaving it out will give only the most basic collection record.
Definition at line 1071 of file co_andisol.class.php.
{
         $ret = $this->create_general_data_item($in_read_security_id, $in_write_security_id, $in_classname);
         if (isset($in_initial_item_ids) && is_array($in_initial_item_ids) && count($in_initial_item_ids) && isset($ret) && ($ret instanceof CO_Collection)) {
             $elements = $this->get_chameleon_instance()->get_multiple_data_records_by_id($in_initial_item_ids);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
             if (isset($elements) && is_array($elements) && count($elements) && !isset($this->error)) {
                 if (!$ret->appendElements($elements)) {
                     $this->error = $ret->error;
                     $ret->delete_from_db();
                     $ret = NULL;
                 }
             } else {
                 $ret->delete_from_db();
                 $ret = NULL;
             }
         }
         return $ret;
     }
References create_general_data_item(), and get_chameleon_instance().
create_general_data_item()
CO_Andisol::create_general_data_item ($in_read_security_id = 1, $in_write_security_id = NULL, $in_classname = 'CO_Main_DB_Record')
This creates an uninitialized object, based upon the passed-in class.
Returns
a new instance of the class.
Parameters
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
$in_classname OPTIONAL: This is the name of the class we want to create. It's optional, but leaving it out will give only the most basic data record.
Definition at line 1058 of file co_andisol.class.php.
{
         return $this->_create_db_object($in_classname, $in_read_security_id, $in_write_security_id);
     }
References _create_db_object().
Referenced by create_collection(), create_ll_location(), and create_place().
create_ll_location()
CO_Andisol::create_ll_location ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor = NULL, $in_see_clearly_id = NULL, $in_read_security_id = 1, $in_write_security_id = NULL, $in_classname = 'CO_LL_Location')
This creates an initialized basic location object, based upon the passed-in class.
Returns
a new instance of the class.
Parameters
$in_longitude_degrees REQUIRED: The longitude, in degrees.
$in_latitude_degrees REQUIRED: The latitude, in degrees.
$in_fuzz_factor OPTIONAL: If there is a "fuzz factor" to be applied, it should be sent in as a distance in Kilometers. This creates a square, double the fuzz factor to a side, which is filled with a random value whenever the long/lat is queried. This is used when we don't want an exact location being returned. It is used to do things like preserve privacy. The "fuzzing" is done at an extremely low level, and only God, or IDs with write permission, can "see clearly." If you have the ability to "see" the exact location, then you can call special functions. Read permissions are not sufficient to "see clearly." You need to have write permissions on the object. You can also set a single security token that is allowed to see If NULL (default), or 0.0, no "fuzz factor" is applied, so the location is exact.
$in_see_clearly_id OPTIONAL: Ignored, if $in_fuzz_factor is not supplied. If $in_fuzz_factor is supplied, then this can be an ID, in addition to the write ID, that has permission to see the exact location. Default is NULL.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
$in_classname OPTIONAL: A classname to use, besides the lowest-level class. If NULL, then the CO_LL_Location class is used.
Definition at line 1221 of file co_andisol.class.php.
{
         $ret = NULL;
         $instance = $this->create_general_data_item($in_read_security_id, $in_write_security_id, $in_classname);
         // First, make sure we're in the right ballpark.
         if (isset($instance) && ($instance instanceof CO_LL_Location)) {
             if ($instance->set_longitude($in_longitude_degrees)) {
                 if ($instance->set_latitude($in_latitude_degrees)) {
                     if (isset($in_fuzz_factor) && (0.0 < floatval($in_fuzz_factor))) {
                         if ($instance->set_fuzz_factor($in_fuzz_factor)) {
                             if (isset($in_see_clearly_id) && (0 < intval($in_see_clearly_id))) {
                                 if ($instance->set_can_see_through_the_fuzz($in_see_clearly_id)) {
                                     $ret = $instance;
                                 } else {
                                     if ($instance->error) {
                                         $this->error = $instance->error;
                                     }
                                     $instance->delete_from_db();
                                 }
                             } else {
                                 $ret = $instance;
                             }
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                         }
                     } else {
                         $ret = $instance;
                     }
                 } else {
                     if ($instance->error) {
                         $this->error = $instance->error;
                     }
                     $instance->delete_from_db();
                 }
             } else {
                 if ($instance->error) {
                     $this->error = $instance->error;
                 }
                 $instance->delete_from_db();
             }
         } else {
             if (isset($instance) && ($instance instanceof A_CO_DB_Table_Base)) {
                 if ($instance->error) {
                     $this->error = $instance->error;
                 }
                 $instance->delete_from_db();
             }
         }
         return $ret;
     }
References create_general_data_item().
create_ll_place()
CO_Andisol::create_ll_place ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor = NULL, $in_see_clearly_id = NULL, $in_read_security_id = 1, $in_write_security_id = NULL, $in_classname = 'CO_Place')
This creates an initialized place location object, based upon the passed-in class. However, this method will take just a long/lat, like creating a long/lat class, and do a geocode to set the address fields.
Returns
a new instance of the class.
Parameters
$in_longitude_degrees REQUIRED: The longitude, in degrees.
$in_latitude_degrees REQUIRED: The latitude, in degrees.
$in_fuzz_factor OPTIONAL: If there is a "fuzz factor" to be applied, it should be sent in as a distance in Kilometers. This creates a square, double the fuzz factor to a side, which is filled with a random value whenever the long/lat is queried. This is used when we don't want an exact location being returned. It is used to do things like preserve privacy. The "fuzzing" is done at an extremely low level, and only God, or IDs with write permission, can "see clearly." If you have the ability to "see" the exact location, then you can call special functions. Read permissions are not sufficient to "see clearly." You need to have write permissions on the object. You can also set a single security token that is allowed to see If NULL (default), or 0.0, no "fuzz factor" is applied, so the location is exact.
$in_see_clearly_id OPTIONAL: Ignored, if $in_fuzz_factor is not supplied. If $in_fuzz_factor is supplied, then this can be an ID, in addition to the write ID, that has permission to see the exact location. Default is NULL.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
$in_classname OPTIONAL: A classname to use, besides the lowest-level class. If NULL, then the CO_Place class is used.
Definition at line 1617 of file co_andisol.class.php.
{
         return $this->create_place(true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor, $in_see_clearly_id, $in_read_security_id, $in_write_security_id, $in_classname);
     }
References create_place().
create_ll_us_place()
CO_Andisol::create_ll_us_place ($in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor = NULL, $in_see_clearly_id = NULL, $in_read_security_id = 1, $in_write_security_id = NULL)
This creates an initialized basic US place location COLLECTION object. This does not accept a classname. Use the regular function if you want to get fancy. However, this method will take just a long/lat, like creating a long/lat class, and do a geocode to set the address fields.
Returns
a new instance of the class.
Parameters
$in_longitude_degrees REQUIRED: The longitude, in degrees.
$in_latitude_degrees REQUIRED: The latitude, in degrees.
$in_fuzz_factor OPTIONAL: If there is a "fuzz factor" to be applied, it should be sent in as a distance in Kilometers. This creates a square, double the fuzz factor to a side, which is filled with a random value whenever the long/lat is queried. This is used when we don't want an exact location being returned. It is used to do things like preserve privacy. The "fuzzing" is done at an extremely low level, and only God, or IDs with write permission, can "see clearly." If you have the ability to "see" the exact location, then you can call special functions. Read permissions are not sufficient to "see clearly." You need to have write permissions on the object. You can also set a single security token that is allowed to see If NULL (default), or 0.0, no "fuzz factor" is applied, so the location is exact.
$in_see_clearly_id OPTIONAL: Ignored, if $in_fuzz_factor is not supplied. If $in_fuzz_factor is supplied, then this can be an ID, in addition to the write ID, that has permission to see the exact location. Default is NULL.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
Definition at line 1643 of file co_andisol.class.php.
{
         return $this->create_place(true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor, $in_see_clearly_id, $in_read_security_id, $in_write_security_id, 'CO_US_Place');
     }
References create_place().
create_new_manager_login()
CO_Andisol::create_new_manager_login ($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids = 0)
This is the public function used to create a new login manager login in the security database. This can only be called from a login manager.
Returns
the new CO_Login_Manager instance.
Parameters
$in_login_id The login ID as text. It needs to be unique, within the Security database, and this will fail, if it is not.
$in_cleartext_password The password to set (in cleartext). It will be stored as a hashed password.
$in_create_this_many_personal_ids This is how many Personal tokens should be created and assigned. Default is 0.
Definition at line 715 of file co_andisol.class.php.
{
         return $this->get_cobra_instance()->create_new_manager_login($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids);
     }
References get_cobra_instance().
create_new_standard_login()
CO_Andisol::create_new_standard_login ($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids = 0)
This is the public function used to create a new standard login in the security database. This can only be called from a login manager.
Returns
the new CO_Cobra_Login instance.
Parameters
$in_login_id The login ID as text. It needs to be unique, within the Security database, and this will fail, if it is not.
$in_cleartext_password The password to set (in cleartext). It will be stored as a hashed password.
$in_create_this_many_personal_ids This is how many Personal tokens should be created and assigned. Default is 0.
Definition at line 701 of file co_andisol.class.php.
{
         return $this->get_cobra_instance()->create_new_standard_login($in_login_id, $in_cleartext_password, $in_create_this_many_personal_ids);
     }
References get_cobra_instance().
create_new_user()
CO_Andisol::create_new_user ($in_login_string_id, $in_password = NULL, $in_display_name = NULL, $in_security_tokens = NULL, $in_read_security_id = NULL, $is_manager = false, $in_create_this_many_personal_ids = 0)
This method can only be called if the user is logged in as a Login Manager (or God). This creates a new login and user collection. Upon successful completion, both a new login, and a user collection, based upon that login, now exist. If there was an error, the user and login are deleted. It should be noted that, if the login was created, it is not really deleted, and is, instead, turned into a security token object.
Returns
a string, with the login password as cleartext (If an acceptable-length password is supplied in $in_password, that that is returned). If the operation failed, then NULL is returned.
Parameters
$in_login_string_id REQUIRED: The string login ID. It must be unique in the Security DB.
$in_password OPTIONAL: A new password. It must be at least as long as the minimum password length. If not supplied, an auto-generated password is created and returned as the function return. If too short, then an auto-generated password is created.
$in_display_name OPTIONAL: A string, representing the basic "display name" to be associated with the login and user collection. If not supplied, the $in_login_string_id is used.
$in_security_tokens Any additional security tokens to apply to the new login. These must be a subset of the security tokens available to the logged-in manager. The God admin can set any tokens they want.
$in_read_security_id An optional read security ID. If not supplied, then ID 1 (logged-in users) is set. The write security ID is always set to the ID of the login.
$is_manager If true (default is false), then the new user will be a CO_Login_Manager object.
$in_create_this_many_personal_ids This is how many Personal tokens should be created and assigned. Default is 0.
Definition at line 731 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($in_login_string_id) {
             if ($this->manager()) { // Don't even bother unless we're a manager.
                 $login_item = NULL;
                 // See if we need to auto-generate a password.
                 if (!$in_password || (strlen($in_password) < CO_Config::$min_pw_len)) {
                     $in_password = substr(str_shuffle("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*~_-=+;:,.!?"), 0, CO_Config::$min_pw_len);
                 }
                 if ($is_manager) {  // See if they want to create a manager, or a standard login.
                     $login_item = $this->get_cobra_instance()->create_new_manager_login($in_login_string_id, $in_password, $in_create_this_many_personal_ids);
                 } else {
                     $login_item = $this->get_cobra_instance()->create_new_standard_login($in_login_string_id, $in_password, $in_create_this_many_personal_ids);
                 }
                 // Make sure we got what we expect.
                 if ($login_item instanceof CO_Security_Login) {
                     // Set any provided security tokens.
                     if (is_array($in_security_tokens) && count($in_security_tokens)) {
                         $login_item->set_ids($in_security_tokens);
                     }
                     // Next, set the display name.
                     $display_name = $in_display_name;
                     if (!$display_name) {
                         $display_name = $in_login_string_id;
                     }
                     // Set the display name.
                     if ($login_item->set_name($display_name)) {
                         // Assuming all that went well, now we create the user item.
                         $id = $login_item->id();
                         $user_item = $this->get_cobra_instance()->get_user_from_login($id, true);
                         if (isset($in_read_security_id) && intval($in_read_security_id)) {
                             if (!$user_item->set_read_security_id(intval($in_read_security_id))) {
                                 $user_item->delete_from_db();
                                 $login_item->delete_from_db();
                                 $user_item = NULL;
                                 $login_item = NULL;
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             } elseif (!$login_item->set_read_security_id($login_item->id())) {
                                 $user_item->delete_from_db();
                                 $login_item->delete_from_db();
                                 $user_item = NULL;
                                 $login_item = NULL;
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             }
                         } else {    // By default, users are any-login-readable, and logins are login-user-only readable, and neither can be written except by the login.
                             if (!$user_item->set_read_security_id(1)) {
                                 $user_item->delete_from_db();
                                 $login_item->delete_from_db();
                                 $user_item = NULL;
                                 $login_item = NULL;
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             } elseif (!$login_item->set_read_security_id($login_item->id())) {
                                 $user_item->delete_from_db();
                                 $login_item->delete_from_db();
                                 $user_item = NULL;
                                 $login_item = NULL;
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             }
                         }
                         if ($user_item instanceof CO_User_Collection) {
                             if ($user_item->set_name($display_name)) {
                                 if ($login_item->set_password_from_cleartext($in_password)) {
                                     $ret = $in_password;
                                 } else {
                                     $user_item->delete_from_db();
                                     $login_item->delete_from_db();
                                     $user_item = NULL;
                                     $login_item = NULL;
                                     $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                     CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                     CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                                 }
                             } else {
                                 $user_item->delete_from_db();
                                 $login_item->delete_from_db();
                                 $user_item = NULL;
                                 $login_item = NULL;
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             }
                         } else {
                             $this->error = $this->get_cobra_instance()->error;
                             // Just in case something was created.
                             if (isset($user_item) && ($user_item instanceof A_CO_DB_Table_Base)) {
                                 $user_item->delete_from_db();
                             }
                             $user_item = NULL;
                             $login_item->delete_from_db();
                             $login_item = NULL;
                             if (!$this->error) {
                                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                                 CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                             }
                         }
                     } else {
                         $this->error = $this->get_cobra_instance()->error;
                         $login_item->delete_from_db();
                         $login_item = NULL;
                         if (!$this->error) {
                             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                             CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                             CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                         }
                     }
                 } else {
                     $this->error = $this->get_cobra_instance()->error;
                     // Just in case something was created.
                     if (isset($login_item) && ($login_item instanceof A_CO_DB_Table_Base)) {
                         $login_item->delete_from_db();
                     }
                     $login_item = NULL;
                     if (!$this->error) {
                         $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_failed_to_initialize,
                                                         CO_ANDISOL_Lang::$andisol_error_name_login_instance_failed_to_initialize,
                                                         CO_ANDISOL_Lang::$andisol_error_desc_login_instance_failed_to_initialize);
                     }
                 }
             } else {
                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                                 CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                                 CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
             }
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_login_instance_failed_to_initialize, CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_login_instance_failed_to_initialize, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_login_instance_failed_to_initialize, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_cobra_instance(), and manager().
create_place()
CO_Andisol::create_place ($auto_resolve = true, $in_venue = NULL, $in_street_address = NULL, $in_municipality = NULL, $in_county = NULL, $in_province = NULL, $in_postal_code = NULL, $in_nation = NULL, $in_extra_info = NULL, $in_longitude_degrees = NULL, $in_latitude_degrees = NULL, $in_fuzz_factor = NULL, $in_see_clearly_id = NULL, $in_read_security_id = 1, $in_write_security_id = NULL, $in_classname = 'CO_Place')
This creates an initialized basic place location object, based upon the passed-in class. Although all parameters are optional, you need to specify at last enough information to specify a place.
Returns
a new instance of the class.
Parameters
$auto_resolve OPTIONAL: If false (Default is true), then we will not try to "fill in the blanks" with any missing information.
$in_venue OPTIONAL: The venue (place/building/establishment name).
$in_street_address OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The street address (including number).
$in_municipality OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The town/city.
$in_county OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The county/sub-province.
$in_province OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The state/province/prefecture.
$in_postal_code OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The ZIP/postal code.
$in_nation OPTIONAL: Ignored if $in_fuzz_factor is nonzero. The nation.
$in_extra_info OPTIONAL: Additional (casual text) address/location/venue information.
$in_longitude_degrees OPTIONAL: The longitude, in degrees.
$in_latitude_degrees OPTIONAL: The latitude, in degrees.
$in_fuzz_factor OPTIONAL: If there is a "fuzz factor" to be applied, it should be sent in as a distance in Kilometers. This creates a square, double the fuzz factor to a side, which is filled with a random value whenever the long/lat is queried. This is used when we don't want an exact location being returned. It is used to do things like preserve privacy. The "fuzzing" is done at an extremely low level, and only God, or IDs with write permission, can "see clearly." If you have the ability to "see" the exact location, then you can call special functions. Read permissions are not sufficient to "see clearly." You need to have write permissions on the object. You can also set a single security token that is allowed to see If NULL (default), or 0.0, no "fuzz factor" is applied, so the location is exact.
$in_see_clearly_id OPTIONAL: Ignored, if $in_fuzz_factor is not supplied. If $in_fuzz_factor is supplied, then this can be an ID, in addition to the write ID, that has permission to see the exact location. Default is NULL.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
$in_classname OPTIONAL: A classname to use, besides the lowest-level class. If NULL, then the CO_Place class is used.
Definition at line 1304 of file co_andisol.class.php.
{
         $ret = NULL;
         // We can create the special US version of the place, if we know we are US (Only if we are using the generic base class).
         if (((strtoupper($in_nation) == 'US') || (strtoupper($in_nation) == 'USA')) && ($in_classname == 'CO_Place')) {
             $in_classname ='CO_US_Place';
         }
         // If we know we are US, then we don't need to specify a nation.
         if ($in_classname == 'CO_US_Place') {
             $in_nation = NULL;
         }
         // We have to have at least enough basic information to denote a place.
         if((isset($in_longitude_degrees) && isset($in_longitude_degrees))   ||
             isset($in_venue) ||
             isset($in_street_address) ||
             isset($in_municipality) ||
             isset($in_county) ||
             isset($in_province) ||
             isset($in_postal_code) ||
             isset($in_nation)) {
             $instance = $this->create_general_data_item($in_read_security_id, $in_write_security_id, $in_classname);
             // First, make sure we're in the right ballpark.
             if (isset($instance) && ($instance instanceof CO_Place)) {
                 $long_lat_explicitly_set = false;   // We use this to figure whether or not to do an initial lookup.
                 $address_explicitly_set = false;    // We use this to figure whether or not to do an initial geocode.
                 // If a long/lat was provided, we start by setting that to our object.
                 if(isset($in_longitude_degrees) && isset($in_longitude_degrees)) {
                     if ($instance->set_longitude($in_longitude_degrees)) {
                         if ($instance->set_latitude($in_latitude_degrees)) {
                             $long_lat_explicitly_set = true;    // This means we won't be needing a lookup.
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     } else {
                         if ($instance->error) {
                             $this->error = $instance->error;
                         }
                         $instance->delete_from_db();
                         $instance = NULL;
                     }
                 }
                 // Next, see if a venue name was provided.
                 if(isset($instance) && isset($in_venue)) {
                     if ($instance->set_tag(0, $in_venue)) {
                         $address_explicitly_set = true;
                     } else {
                         if ($instance->error) {
                             $this->error = $instance->error;
                         }
                         $instance->delete_from_db();
                         $instance = NULL;
                     }
                 }
                 // Next, see if extra info was provided.
                 if(isset($instance) && isset($in_extra_info)) {
                     if (!$instance->set_tag(2, $in_extra_info)) {
                         if ($instance->error) {
                             $this->error = $instance->error;
                         }
                         $instance->delete_from_db();
                         $instance = NULL;
                     }
                 }
                 // We only allow a specific address to be entered if this is a "non-fuzzed" location. This is a security measure.
                 if (isset($instance) && (!isset($in_fuzz_factor) || (0.0 == floatval($in_fuzz_factor)))) {
                     // Next, see if a street address was provided.
                     if(isset($instance) && isset($in_street_address)) {
                         if ($instance->set_tag(1, $in_street_address)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                     // Next, see if a town was provided.
                     if(isset($instance) && isset($in_municipality)) {
                         if ($instance->set_tag(3, $in_municipality)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                     // Next, see if a county was provided.
                     if(isset($instance) && isset($in_county)) {
                         if ($instance->set_tag(4, $in_county)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                     // Next, see if a state was provided.
                     if(isset($instance) && isset($in_province)) {
                         if ($instance->set_tag(5, $in_province)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                     // Next, see if a ZIP code was provided.
                     if(isset($instance) && isset($in_postal_code)) {
                         if ($instance->set_tag(6, $in_postal_code)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                     // Next, see if a nation was provided.
                     if(isset($instance) && isset($in_nation)) {
                         if ($instance->set_tag(7, $in_nation)) {
                             $address_explicitly_set = true;
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                 } elseif (isset($instance)) {
                     $auto_resolve = false;  // We do not do an auto-lookup if we are "fuzzy."
                     if ($instance->set_fuzz_factor($in_fuzz_factor)) {
                         if (isset($in_see_clearly_id) && (0 < intval($in_see_clearly_id))) {
                             if (!$instance->set_can_see_through_the_fuzz($in_see_clearly_id)) {
                                 if ($instance->error) {
                                     $this->error = $instance->error;
                                 }
                                 $instance->delete_from_db();
                                 $instance = NULL;
                             }
                         }
                     } else {
                         if ($instance->error) {
                             $this->error = $instance->error;
                         }
                         $instance->delete_from_db();
                         $instance = NULL;
                     }
                 }
                 // OK. If we are here, and still have a valid instance, then we can "set it in stone," and see if we need to do a geocode.
                 if (isset($instance)) {
                     $instance->set_address_elements($instance->tags(), true);
                     // If we did not explicitly set a long/lat, and have a Google API key (assumed valid), then let's try a geocode.
                     if ($auto_resolve && !$long_lat_explicitly_set && CO_Config::$google_api_key) {  // If we can do a lookup, and need to, then lets's give that a go.
                         $long_lat = $instance->lookup_address();
                         if (isset($long_lat) && is_array($long_lat) && (1 < count($long_lat))) {
                             if ($instance->set_longitude($long_lat['longitude'])) {
                                 if ($instance->set_latitude($long_lat['latitude'])) {
                                     $ret = $instance;   // Now we're ready for our close-up, Mr. DeMille...
                                 } else {
                                     if ($instance->error) {
                                         $this->error = $instance->error;
                                     }
                                     $instance->delete_from_db();
                                     $instance = NULL;
                                 }
                             } else {
                                 if ($instance->error) {
                                     $this->error = $instance->error;
                                 }
                                 $instance->delete_from_db();
                                 $instance = NULL;
                             }
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     } else {    // Otherwise, we simply send the current result back.
                         $ret = $instance;
                     }
                     // If we did not explicitly set an address, and have a Google API key (assumed valid), then let's try a geocode.
                     if ($ret && $auto_resolve && !$address_explicitly_set && CO_Config::$google_api_key) {  // If we can do a lookup, and need to, then lets's give that a go.
                         $ret = NULL;    // Not so fast, Skippy.
                         $address = $instance->geocode_long_lat();
                         if (isset($address) && is_array($address) && (0 < count($address))) {
                             for ($i = 0; $i < 8; $i++) {
                                 eval("\$key = CO_CHAMELEON_Lang::\$chameleon_co_place_tag_$i;");
                                 if (isset($address[$key]) && trim($address[$key])) { // Is there a venue?
                                     if (!$instance->set_tag($i, trim($address[$key]))) {
                                         if ($instance->error) {
                                             $this->error = $instance->error;
                                         }
                                         $instance->delete_from_db();
                                         $instance = NULL;
                                         break;
                                     }
                                 }
                             }
                             // OK. Now we can do it.
                             if (isset($instance)) {
                                 // This sets the object up to what we just sent in.
                                 $instance->set_address_elements($instance->tags(), true);
                                 $ret = $instance;
                             }
                         } else {
                             if ($instance->error) {
                                 $this->error = $instance->error;
                             }
                             $instance->delete_from_db();
                             $instance = NULL;
                         }
                     }
                 } else {
                     $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_location_failed_to_initialize,
                                                     CO_ANDISOL_Lang::$andisol_error_name_location_failed_to_initialize,
                                                     CO_ANDISOL_Lang::$andisol_error_desc_location_failed_to_initialize);
                 }
             } else {
                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_location_failed_to_initialize,
                                                 CO_ANDISOL_Lang::$andisol_error_name_location_failed_to_initialize,
                                                 CO_ANDISOL_Lang::$andisol_error_desc_location_failed_to_initialize);
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_insufficient_location_information,
                                             CO_ANDISOL_Lang::$andisol_error_name_insufficient_location_information,
                                             CO_ANDISOL_Lang::$andisol_error_desc_insufficient_location_information);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_insufficient_location_information, CO_ANDISOL_Lang_Common\$andisol_error_code_location_failed_to_initialize, CO_ANDISOL_Lang\$andisol_error_desc_insufficient_location_information, CO_ANDISOL_Lang\$andisol_error_desc_location_failed_to_initialize, CO_ANDISOL_Lang\$andisol_error_name_insufficient_location_information, CO_ANDISOL_Lang\$andisol_error_name_location_failed_to_initialize, and create_general_data_item().
Referenced by create_ll_place(), create_ll_us_place(), and create_place_collection().
create_place_collection()
CO_Andisol::create_place_collection ($auto_resolve = true, $in_venue = NULL, $in_street_address = NULL, $in_municipality = NULL, $in_county = NULL, $in_province = NULL, $in_postal_code = NULL, $in_nation = NULL, $in_extra_info = NULL, $in_longitude_degrees = NULL, $in_latitude_degrees = NULL, $in_fuzz_factor = NULL, $in_see_clearly_id = NULL, $in_read_security_id = 1, $in_write_security_id = NULL)
This creates an initialized basic place location COLLECTION object. This does not accept a classname. Use the regular function if you want to get fancy. Although all parameters are optional, you need to specify at last enough information to specify a place.
Returns
a new instance of the class.
Parameters
$auto_resolve OPTIONAL: If false (Default is true), then we will not try to "fill in the blanks" with any missing information.
$in_venue OPTIONAL: The venue (place/building/establishment name).
$in_street_address OPTIONAL: The street address (including number).
$in_municipality OPTIONAL: The town/city.
$in_county OPTIONAL: The county/sub-province.
$in_province OPTIONAL: The state/province/prefecture.
$in_postal_code OPTIONAL: The ZIP/postal code.
$in_nation OPTIONAL: The nation.
$in_extra_info OPTIONAL: Additional (casual text) address/location/venue information.
$in_longitude_degrees OPTIONAL: The longitude, in degrees.
$in_latitude_degrees OPTIONAL: The latitude, in degrees.
$in_fuzz_factor OPTIONAL: If there is a "fuzz factor" to be applied, it should be sent in as a distance in Kilometers. This creates a square, double the fuzz factor to a side, which is filled with a random value whenever the long/lat is queried. This is used when we don't want an exact location being returned. It is used to do things like preserve privacy. The "fuzzing" is done at an extremely low level, and only God, or IDs with write permission, can "see clearly." If you have the ability to "see" the exact location, then you can call special functions. Read permissions are not sufficient to "see clearly." You need to have write permissions on the object. You can also set a single security token that is allowed to see If NULL (default), or 0.0, no "fuzz factor" is applied, so the location is exact.
$in_see_clearly_id OPTIONAL: Ignored, if $in_fuzz_factor is not supplied. If $in_fuzz_factor is supplied, then this can be an ID, in addition to the write ID, that has permission to see the exact location. Default is NULL.
$in_read_security_id OPTIONAL: An initial read security ID. If not specified, 1 (open to all logged-in users) will be specified.
$in_write_security_id OPTIONAL: An initial write security ID. If not specified, the current user's integer login ID will be used as the write security token.
Definition at line 1668 of file co_andisol.class.php.
{
         $class = 'CO_Place_Collection';
         // We can create the special US version of the place, if we know we are US.
         if ((strtoupper($in_nation) == 'US') || (strtoupper($in_nation) == 'USA')) {
             $class ='CO_US_Place_Collection';
             $in_nation = NULL;
         }
         return $this->create_place($auto_resolve, $in_venue, $in_street_address, $in_municipality, $in_county, $in_province, $in_postal_code, NULL, NULL, $in_longitude_degrees, $in_latitude_degrees, $in_fuzz_factor, $in_see_clearly_id, $in_read_security_id, $in_write_security_id, $class);
     }
References create_place().
current_login()
CO_Andisol::current_login ()
Returns
The current login Item. NULL if no login.
Definition at line 245 of file co_andisol.class.php.
{
         return $this->get_login_item();
     }
References get_login_item().
current_user()
CO_Andisol::current_user ()
Returns
The current user Item. NULL, if no user for the current login.
Definition at line 253 of file co_andisol.class.php.
{
         return $this->get_user_from_login();
     }
References get_user_from_login().
delete_item_by_id()
CO_Andisol::delete_item_by_id ($in_item_id_integer)
Deletes a data item, given its integer ID.
Returns
true, if successful.
Parameters
$in_item_id_integer REQUIRED: This is the key that we are deleting. It must be a string.
Definition at line 1105 of file co_andisol.class.php.
{
         $ret = false;
         if ($this->logged_in()) {
             $ret = $this->get_chameleon_instance()->delete_data_record($in_item_id_integer);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_chameleon_instance(), and logged_in().
delete_key()
CO_Andisol::delete_key ($in_key, $in_classname = 'CO_KeyValue_CO_Collection')
This deletes a key (and its associated data).
Returns
true, if successful.
Parameters
$in_key REQUIRED: This is the key that we are deleting. It must be a string.
$in_classname OPTIONAL: This is the class to search for the key. The default is the base class.
Definition at line 1177 of file co_andisol.class.php.
{
         return $this->set_value_for_key($in_key, NULL, $in_classname);
     }
References set_value_for_key().
delete_user()
CO_Andisol::delete_user ($in_login_string_id, $with_extreme_prejudice = false)
This method can only be called if the user is logged in as a Login Manager (or God). This will delete both the login and the user collection for the given login ID. It should be noted that deleting a collection does not delete the data associated with that collection, unless $with_extreme_prejudice is true, and even then, only the records this manager can see will be deleted.
Returns
true, if the operation was successful.
Parameters
$in_login_string_id REQUIRED: The string login ID of the user to delete.
$with_extreme_prejudice OPTIONAL: If true (Default is false), then the manager will delete as many of the user data points as possible (It may not be possible for the manager to delete all data, unless the manager is God).
Definition at line 898 of file co_andisol.class.php.
{
         $ret = false;
         if ($in_login_string_id) {
             if ($this->manager()) { // Don't even bother unless we're a manager.
                 // First, fetch the login item.
                 $login_item = $this->get_cobra_instance()->get_login_instance($in_login_string_id);
                 if ($login_item) {
                     // Next, get the user item.
                     $user_item = $this->get_cobra_instance()->get_user_from_login($login_item->id());
                     if ($user_item) {
                         // We have to have both the login and the user. Now, we make sure that we have write perms on both.
                         if ($login_item->user_can_write() && $user_item->user_can_write()) {
                             if ($user_item->delete_from_db($with_extreme_prejudice, true)) {
                                 $ret = true;
                             } else {
                                 $this->error = $user_item->error;
                                 if (!$this->error) {
                                     $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_deleted,
                                                                     CO_ANDISOL_Lang::$andisol_error_name_user_not_deleted,
                                                                     CO_ANDISOL_Lang::$andisol_error_desc_user_not_deleted);
                                 }
                             }
                         } else {
                             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
                         }
                     } else {
                         $this->error = $this->get_cobra_instance()->error;
                         if (!$this->error) {
                             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_instance_unavailable,
                                                             CO_ANDISOL_Lang::$andisol_error_name_user_instance_unavailable,
                                                             CO_ANDISOL_Lang::$andisol_error_desc_user_instance_unavailable);
                         }
                     }
                 } else {
                     $this->error = $this->get_cobra_instance()->error;
                     if (!$this->error) {
                         $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_login_instance_unavailable,
                                                         CO_ANDISOL_Lang::$andisol_error_name_login_instance_unavailable,
                                                         CO_ANDISOL_Lang::$andisol_error_desc_login_instance_unavailable);
                     }
                 }
             } else {
                 $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                                 CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                                 CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
             }
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_login_instance_unavailable, CO_ANDISOL_Lang_Common\$andisol_error_code_user_instance_unavailable, CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_deleted, CO_ANDISOL_Lang\$andisol_error_desc_login_instance_unavailable, CO_ANDISOL_Lang\$andisol_error_desc_user_instance_unavailable, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_deleted, CO_ANDISOL_Lang\$andisol_error_name_login_instance_unavailable, CO_ANDISOL_Lang\$andisol_error_name_user_instance_unavailable, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_deleted, get_cobra_instance(), and manager().
fetch_backup()
CO_Andisol::fetch_backup ()
This is a special "God Mode-Only" method that dumps everything in both databases. It is used to generate a CSV backup file.
The user must be logged in as "God."
Returns
an associative array ('security' => array, 'data' => array') of two sets of associative arrays, with the dump. NULL if the user is not authorized.
Definition at line 1808 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->fetch_backup();
     }
References get_chameleon_instance().
generic_search()
CO_Andisol::generic_search ($in_search_parameters = NULL, $or_search = false, $page_size = 0, $initial_page = 0, $and_writeable = false, $count_only = false, $ids_only = false)
This is a "generic" data search. It can be called from external user contexts, and allows a fairly generalized search of the "data" datasource. Sorting will be done for the "owner" and "location" values. "owner" will be sorted by the ID of the returned records, and "location" will be by distance from the center.
String searches are always case-insensitive.
All parameters are optional, but calling this "blank" will return the entire data databse (that is visible to the user).
Here are a few examples:
// Search for records with long/lat set within a 10Km radius circle (centered on Tysons Corner, VA):
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested location:
                                                                'location' => Array('longitude' => -77.2311,
                                                                                    'latitude' => 38.9187,
                                                                                    'radius' => 10
                                                                                    )
                                                            )
                                                    );
// Search for records with an access_class of CO_User_Collection:
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested class:
                                                                'access_class' => 'CO_User_Collection'
                                                            )
                                                    );
// Search for records with an access_class of CO_User_Collection, but this time, specify a wildcard, so you also get subclasses:
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested class:
                                                                'access_class' => '%_User_Collection',
                                                                'use_like' => 1
                                                            )
                                                    );
// Search for records with an object_name of "Back to Basics", and a class of CO_US_Place_Collection.
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested class:
                                                                'access_class' => 'CO_US_Place_Collection',
                                                                'Back to Basics'
                                                            )
                                                    );
// Search for records with an object_name of "Back to Basics", and a class of CO_US_Place_Collection. However, this time, we make it an OR search.
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested class:
                                                                'access_class' => 'CO_US_Place_Collection',
                                                                'Back to Basics'
                                                            ),
                                                        true
                                                    );
// Search for records with an object_name of "Back to Basics", and a class of CO_US_Place_Collection. However, this time, we make it an OR search, and only the second page, with pages of ten.
$returned_array = $andisol_instance->generic_search(// The first parameter is an associative array of main search keys and values:
                                                        Array(  // This is the requested class:
                                                                'access_class' => 'CO_US_Place_Collection',
                                                                'Back to Basics'
                                                            ),
                                                        true,
                                                        10,
                                                        1
                                                    );
Returns
an array of instances (or integers, if $ids_only is true) that match the search parameters. If $count_only is true, then it will be a single integer, with the count of responses to the search (if a page, then this count will only be the number of items on that page).
Parameters
$in_search_parameters OPTIONAL: This is an associative array of terms to define the search. The keys should be:
'id' This should be accompanied by an array of one or more integers, representing specific item IDs.
'access_class' This should be accompanied by an array, containing one or more PHP class names.
'name' This will contain a case-insensitive array of strings to check against the object_name column.
'owner' This should be accompanied by an array of one or more integers, representing specific item IDs for "owner" objects.
'tags' This should be accompanied by an array (up to 10 elements) of one or more case-insensitive strings, representing specific tag values. The position in the array denotes which tag to match, so unchecked tags should still be in the array, but empty. You don't match empty tags. You can specify an array for the values, which allows you to do an OR search for the values.
'location' This is only relevant if we are searching for subclasses (or instances) of CO_LL_Location This requires that the parameter be a 3-element associative array of floating-point numbers:
'longitude' This is the search center location longitude, in degrees.
'latitude' This is the search center location latitude, in degrees.
'radius' This is the search radius, in Kilometers.
You can specify an array for any one of the values, which allows you to do an OR search for those values ($or_search does not apply. It is only for the combination of main values). If you add an element called 'use_like' ('use_like' => 1) to the end of 'access_class', 'name' or one of the 'tags', then you can use SQL-style "wildcards" (%) in your matches. If you have 'use_like', and put just a single wildcard in quotes (''), then you are saying "not-empty." NOTE: Although this is an optional parameter, failing to provide anything could return the entire readable database.
Parameters
$or_search OPTIONAL: If true, then the search is very wide (OR), as opposed to narrow (AND), by default. If you specify a location, then that will always be AND, but the other fields can be OR. Tags will always be searched as OR.
$page_size OPTIONAL: If specified with a 1-based integer, this denotes the size of a "page" of results. NOTE: This is only applicable to MySQL or Postgres, and will be ignored if the DB is not MySQL or Postgres. Default is 0.
$initial_page OPTIONAL: This is ignored unless $page_size is greater than 0. In that case, this 0-based index will specify which page of results to return. Values beyond the maximum number of pages will result in no returned values.
$and_writeable OPTIONAL: If true, then we only want records we can modify.
$count_only OPTIONAL: If true (default is false), then only a single integer will be returned, with the count of items that fit the search.
$ids_only OPTIONAL: If true (default is false), then the return array will consist only of integers (the object IDs). If $count_only is true, this is ignored.
Definition at line 481 of file co_andisol.class.php.
{
         $ret = $this->get_chameleon_instance()->generic_search($in_search_parameters, $or_search, $page_size, $initial_page, $and_writeable, $count_only, $ids_only);
         if (isset($this->get_chameleon_instance()->error)) {
             $this->error = $this->get_chameleon_instance()->error;
         }
         return $ret;
     }
References get_chameleon_instance().
Referenced by get_all_login_users(), get_all_standalone_users(), get_all_users(), and location_search().
get_all_login_objects_with_access()
CO_Andisol::get_all_login_objects_with_access ($in_security_token, $and_write = false)
You give a security ID, and you will get all login objects that have that token in their list (or are of that ID).
This is restricted to use security vetting, so only logins visible to the current login.
Returns
an array of instances.
Parameters
$in_security_token An integer, with the requested security token.
$and_write If true, then we only want ones we have write access to.
Definition at line 1781 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_all_login_objects_with_access($in_security_token, $and_write);
     }
References get_chameleon_instance().
get_all_login_users()
CO_Andisol::get_all_login_users ($and_write = false)
Returns
an array of instances of all the users (not logins) that are visible to the current login, and that have logins, themselves. It should be noted that this will not return standalone users.
Parameters
$and_write OPTIONAL: If true (Default is false), then we only want ones we have write access to.
Definition at line 574 of file co_andisol.class.php.
{
         $ret = Array();
         $temp = $this->generic_search(Array('access_class' => Array('%_User_Collection', 'use_like' => 1), 'tags' => Array('%', 'use_like' => 1)), false, 0, 0, $and_write);
         if (isset($temp) && is_array($temp) && count($temp)) {
             // We make sure that we don't return the God user, if there is one (unless we are God).
             foreach ($temp as $user) {
                 $login_instance = $user->get_login_instance();
                 if (isset($login_instance) && ($login_instance instanceof CO_Security_Login)) {
                     if ($this->god() || !$user->is_god()) {
                         array_push($ret, $user);
                     }
                 }
             }
         }
         return $ret;
     }
References generic_search(), and god().
get_all_logins()
CO_Andisol::get_all_logins ($and_write = false, $in_login_string_id = NULL, $in_login_integer_id = NULL)
Returns
an array of instances of all the logins that are visible to the current login (or a supplied login, if in "God" mode). The user must be a manager.
Parameters
$and_write OPTIONAL: If true (Default is false), then we only want ones we have write access to.
$in_login_string_id OPTIONAL: This is ignored, unless this is the God login. If We are logged in as God, then we can select a login via its string login ID, and see what logins are available to it. This trumps the integer ID.
$in_login_integer_id OPTIONAL: This is ignored, unless this is the God login and $in_login_string_id is not specified. If We are logged in as God, then we can select a login via its integer login ID, and see what logins are available to it.
Definition at line 958 of file co_andisol.class.php.
{
         $ret = Array();
         if ($this->manager()) { // Don't even bother unless we're a manager.
             $ret = $this->get_cobra_instance()->get_all_logins($and_write, $in_login_string_id, $in_login_integer_id);
             if (isset($this->get_cobra_instance()->error)) {
                 $this->error = $this->get_cobra_instance()->error;
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_cobra_instance(), and manager().
get_all_personal_ids_except_for_id()
CO_Andisol::get_all_personal_ids_except_for_id ($in_id = 0)
This returns just the "personal" IDs for ALL logins, EXCEPT for the given ID.
This should only be called from the ID fetcher in the access class, as it does not do a security predicate.
Returns
an array of integers, each, a personal security ID.
Parameters
$in_id The integer ID of the row we want exempted. If not specified, then all IDs are returned.
Definition at line 1874 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_all_personal_ids_except_for_id($in_id);
     }
References get_chameleon_instance().
get_all_standalone_users()
CO_Andisol::get_all_standalone_users ($and_write = false)
Returns
an array of instances of all the users (not logins) that are visible to the current login. It should be noted that this can return standalone users.
Parameters
$and_write OPTIONAL: If true (Default is false), then we only want ones we have write access to.
Definition at line 599 of file co_andisol.class.php.
{
         $ret = Array();
         $temp = $this->generic_search(Array('access_class' => Array('%_User_Collection', 'use_like' => 1), 'tags' => Array('')), false, 0, 0, $and_write);
         if (isset($temp) && is_array($temp) && count($temp)) {
             // We make sure that we don't return the God user, if there is one (unless we are God).
             foreach ($temp as $user) {
                 $login_instance = $user->get_login_instance();
                 if ($this->god() || !$user->is_god()) {
                     array_push($ret, $user);
                 }
             }
         }
         return $ret;
     }
References generic_search(), and god().
get_all_user_objects_with_access()
CO_Andisol::get_all_user_objects_with_access ($in_security_token)
You give a security ID, and you will get all user objects that have a login wih that token in their list (or are of that ID).
This is restricted to use security vetting, so only users visible to the current login.
Returns
an array of instances.
Parameters
$in_security_token An integer, with the requested security token.
Definition at line 1795 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_all_user_objects_with_access($in_security_token);
     }
References get_chameleon_instance().
get_all_users()
CO_Andisol::get_all_users ($and_write = false)
Returns
an array of instances of all the users (not logins) that are visible to the current login. It should be noted that this can return standalone users.
Parameters
$and_write OPTIONAL: If true (Default is false), then we only want ones we have write access to.
Definition at line 551 of file co_andisol.class.php.
{
         $ret = Array();
         $temp = $this->generic_search(Array('access_class' => Array('%_User_Collection', 'use_like' => 1)), false, 0, 0, $and_write);
         if (isset($temp) && is_array($temp) && count($temp)) {
             // We make sure that we don't return the God user, if there is one (unless we are God).
             foreach ($temp as $user) {
                 $login_instance = $user->get_login_instance();
                 if ($this->god() || !$user->is_god()) {
                     array_push($ret, $user);
                 }
             }
         }
         return $ret;
     }
References generic_search(), and god().
get_all_visible_logins()
CO_Andisol::get_all_visible_logins ()
Returns
a simple associative array, indexed by login (not user) IDs, with each element being an array, containing the name (usually display name) of the login object in [0], and the login ID, in [1]. It reurns ALL logins visible to the current login.
Definition at line 1743 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance->get_all_visible_users();
     }
References get_chameleon_instance().
get_all_visible_users()
CO_Andisol::get_all_visible_users ()
Returns
a simple associative array, indexed by user (not login) IDs, with each element being the name (usually display name) of the user object. It reurns ALL users visible to the current login.
Definition at line 1735 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_all_visible_users();
     }
References get_chameleon_instance().
get_available_tokens()
CO_Andisol::get_available_tokens ()
This fetches the list of security tokens the currently logged-in user has available. This will reload any non-God Mode IDs before fetching the IDs, in order to spike privilege escalation.
With the God Mode, you get all the security tokens.
Returns
an array of integers, with each one representing a security token. The first element will always be the ID of the user.
Definition at line 1712 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_available_tokens();
     }
References get_chameleon_instance().
get_chameleon_instance()
CO_Andisol::get_chameleon_instance ()
Returns
The CHAMELEON instance.
Definition at line 201 of file co_andisol.class.php.
{
         return $this->_chameleon_instance;
     }
References $_chameleon_instance.
Referenced by _create_db_object(), add_personal_token_from_current_login(), can_i_see_this_data_record(), can_i_see_this_security_record(), check_login_exists_by_login_string(), count_all_login_objects_with_access(), create_collection(), delete_item_by_id(), fetch_backup(), generic_search(), get_all_login_objects_with_access(), get_all_personal_ids_except_for_id(), get_all_user_objects_with_access(), get_all_visible_logins(), get_all_visible_users(), get_available_tokens(), get_data_access_class_by_id(), get_login_item(), get_login_item_by_login_string(), get_logins_that_have_any_of_my_ids(), get_logins_with_personal_ids(), get_multiple_data_records_by_id(), get_object_for_key(), get_personal_security_ids(), get_remaining_time(), get_security_access_class_by_id(), get_single_data_record_by_id(), get_user_from_login(), get_value_for_key(), god(), i_have_this_token(), is_this_a_login_id(), is_this_a_personal_id(), key_is_unique(), logged_in(), make_new_blank_record(), remove_personal_token_from_this_login(), set_value_for_key(), and valid().
get_cobra_instance()
CO_Andisol::get_cobra_instance ()
Returns
The COBRA instance. It will be NULL if the current login is not a manager or God.
Definition at line 193 of file co_andisol.class.php.
{
         return $this->_cobra_instance;
     }
References $_cobra_instance.
Referenced by _make_security_token(), convert_login(), create_new_manager_login(), create_new_standard_login(), create_new_user(), delete_user(), get_all_logins(), get_user_from_login(), make_standalone_user(), manager(), set_personal_ids(), and who_can_see().
get_data_access_class_by_id()
CO_Andisol::get_data_access_class_by_id ($in_id)
This returns the access class for the given ID for the Data Database.
This is "security safe," so that means that if the user does not have rights to the row, they will get NULL.
Returns
a string, containing the access_class data column. NULL, if no response (like the ID does not exist, or the user does not have read rights to it).
Parameters
$in_id This is the ID of the record to fetch.
Definition at line 367 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->get_chameleon_instance()->can_i_see_this_data_record($in_id)) {
             $ret = $this->get_chameleon_instance()->get_data_access_class_by_id($in_id);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         }
         return $ret;
     }
References can_i_see_this_data_record(), and get_chameleon_instance().
get_login_item()
CO_Andisol::get_login_item ($in_login_integer_id = NULL)
This returns the actual security DB login item for the requested user (or the current logged-in user).
The response is subject to standard security vetting, so there is a possibility that nothing will be returned, when there is an existing login at that ID.
Returns
the instance for the requested user. NULL, if not logged in.
Parameters
$in_login_integer_id OPTIONAL: The integer login ID to check (Default is NULL). If not-NULL, then the ID of a login instance. It must be one that the current user can see. If NULL, then the current user.
Definition at line 280 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->logged_in()) {
             $ret = $this->get_chameleon_instance()->get_login_item($in_login_integer_id);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         }
         return $ret;
     }
References get_chameleon_instance(), and logged_in().
Referenced by current_login().
get_login_item_by_login_string()
CO_Andisol::get_login_item_by_login_string ($in_login_string_id)
This returns the actual security DB login item for the requested user (or the current logged-in user).
The response is subject to standard security vetting, so there is a possibility that nothing will be returned, when there is an existing login at that ID.
Returns
the instance for the requested user. NULL, if not logged in.
Parameters
$in_login_string_id REQUIRED: The string login ID to check. It must be one that the current user can see.
Definition at line 302 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->logged_in()) {
             $ret = $this->get_chameleon_instance()->get_login_item_by_login_string($in_login_string_id);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         }
         return $ret;
     }
References get_chameleon_instance(), and logged_in().
Referenced by get_user_from_login_string().
get_logins_that_have_any_of_my_ids()
CO_Andisol::get_logins_that_have_any_of_my_ids ()
This returns IDs that have our personal IDs.
Returns
an associative array of arrays of integer, keyed by integer. The key is the ID of the login, and the value is an array of integer, with the IDs that match. NULL, if an error.
Definition at line 1942 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_logins_that_have_any_of_my_ids();
     }
References get_chameleon_instance().
get_logins_with_personal_ids()
CO_Andisol::get_logins_with_personal_ids ()
This returns IDs that have personal IDs. This only works for the God admin.
Returns
an associative array of arrays of integer, keyed by integer. The key is the ID of the login, and the value is an array of integer, with the Personal IDs that match. NULL, if an error.
Definition at line 1886 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_logins_with_personal_ids();
     }
References get_chameleon_instance().
get_multiple_data_records_by_id()
CO_Andisol::get_multiple_data_records_by_id ($in_id_array)
This method queries the "data" databse for multiple records, given a list of IDs.
The records will not be returned if the user does not have read permission for them.
Returns
an array of instances, fetched an initialized from the database.
Parameters
$in_id_array REQUIRED: An array of integers, with the item IDs.
Definition at line 1016 of file co_andisol.class.php.
{
         $ret = $this->get_chameleon_instance()->get_multiple_data_records_by_id($in_id_array);
         if (isset($this->get_chameleon_instance()->error)) {
             $this->error = $this->get_chameleon_instance()->error;
         }
         return $ret;
     }
References get_chameleon_instance().
get_object_for_key()
CO_Andisol::get_object_for_key ($in_key)
Returns
the object that stores the given key. NULL, if no value or instance for the key.
Parameters
$in_key REQUIRED: This is the key that we are searching for. It must be a string.
Definition at line 1160 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->valid()) {
             $ret = $this->get_chameleon_instance()->get_object_for_key($in_key);
         }
         return $ret;
     }
References get_chameleon_instance(), and valid().
get_personal_security_ids()
CO_Andisol::get_personal_security_ids ()
This fetches the list of the "personal" security tokens the currently logged-in user has available. This will reload any non-God Mode IDs before fetching the IDs, in order to spike privilege escalation. If they have God Mode, then you're pretty much screwed, anyway.
Returns
an array of integers, with each one representing a personal security token.
Definition at line 1846 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_personal_security_ids();
     }
References get_chameleon_instance().
get_remaining_time()
CO_Andisol::get_remaining_time ($in_login_id = NULL)
Returns
a floating-point number, with the remaining login time, in seconds. -1 means no timeout. 0 means time's up.
Parameters
$in_login_id The integer login ID to check. If not-NULL, then the ID of a login instance. It must be one that the current user can see.
Definition at line 1950 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->get_remaining_time($in_login_id);
     }
References get_chameleon_instance().
get_security_access_class_by_id()
CO_Andisol::get_security_access_class_by_id ($in_id)
This returns the access class for the given ID for the Security Database.
This is "security safe," so that means that if the user does not have rights to the row, they will get NULL.
Returns
a string, containing the access_class data column. NULL, if no response (like the ID does not exist, or the user does not have read rights to it).
Parameters
$in_id This is the ID of the record to fetch.
Definition at line 389 of file co_andisol.class.php.
{
         $ret = $this->$this->get_chameleon_instance()->get_security_access_class_by_id($in_id);
         if (isset($this->get_chameleon_instance()->error)) {
             $this->error = $this->get_chameleon_instance()->error;
         }
         return $ret;
     }
References get_chameleon_instance().
get_single_data_record_by_id()
CO_Andisol::get_single_data_record_by_id ($in_id)
This is a "security-safe" method for fetching a single record from the "data" database, by its ID.
Returns
a single new instance, initialized from the database.
Parameters
$in_id REQUIRED: The ID of the record to fetch.
Definition at line 1033 of file co_andisol.class.php.
{
         $ret = $this->get_chameleon_instance()->get_single_data_record_by_id($in_id);
         if (isset($this->get_chameleon_instance()->error)) {
             $this->error = $this->get_chameleon_instance()->error;
         }
         return $ret;
     }
References get_chameleon_instance().
get_user_from_login()
CO_Andisol::get_user_from_login ($in_login_integer_id = NULL, $in_make_user_if_necessary = false)
This is a special function for returning the user for a login, with the possibility of creating one, if one was not already in place. In order to potentially create a user, the current login must be a manager, $in_make_user_if_necessary must be true, and the user must not already exist (even if the current login cannot see that user).
Returns
the user collection object for a given login. If there is no login given, then the current login is assumed. This is subject to security restrictions.
Parameters
$in_login_integer_id OPTIONAL: The integer login ID that is associated with the user collection. If NULL (Default), then the current login is used.
$in_make_user_if_necessary OPTIONAL: If true (Default is false), then the user will be created if it does not already exist. Ignored, if we are not a Login Manager.
Definition at line 651 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($in_make_user_if_necessary && $this->manager()) {   // See if we are a manager, and they want to maybe create a new user.
             $ret = $this->get_cobra_instance()->get_user_from_login($in_login_integer_id, $in_make_user_if_necessary);
             $this->error = isset($this->get_cobra_instance()->error) ? $this->get_cobra_instance()->error : NULL;
         } else {
             $ret = $this->get_chameleon_instance()->get_user_from_login($in_login_integer_id);
             $this->error = isset($this->get_chameleon_instance()->error) ? $this->get_chameleon_instance()->error : NULL;
         }
         return $ret;
     }
References get_chameleon_instance(), get_cobra_instance(), and manager().
Referenced by current_user(), and get_user_from_login_string().
get_user_from_login_string()
CO_Andisol::get_user_from_login_string ($in_login_string_id)
Returns
the user collection object for a given login string. If there is no login given, then the current login is assumed. This is subject to security restrictions.
Parameters
$in_login_string_id REQUIRED: The string login ID that is associated with the user collection.
Definition at line 321 of file co_andisol.class.php.
{
         $ret = NULL;
         $login_item = $this->get_login_item_by_login_string($in_login_string_id);
         if (isset($login_item) && ($login_item instanceof CO_Security_Login)) {
             $ret = $this->get_user_from_login($login_item->id());
         }
         return $ret;
     }
References get_login_item_by_login_string(), and get_user_from_login().
get_value_for_key()
CO_Andisol::get_value_for_key ($in_key, $in_classname = 'CO_KeyValue_CO_Collection')
Returns
the value for a given key. It is dependent on the class passed in. NULL, if no value or instance for the key.
Parameters
$in_key REQUIRED: This is the key that we are searching for. It must be a string.
$in_classname OPTIONAL: This is the class to search for the key. The default is the base class.
Definition at line 1131 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->valid()) {
             $ret = $this->get_chameleon_instance()->get_value_for_key($in_key, $in_classname);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         }
         return $ret;
     }
References get_chameleon_instance(), and valid().
god()
CO_Andisol::god ()
Returns
true, if we are logged in as the "God" admin ID.
Definition at line 237 of file co_andisol.class.php.
{
         return $this->manager() && $this->get_chameleon_instance()->god_mode();
     }
References get_chameleon_instance(), and manager().
Referenced by get_all_login_users(), get_all_standalone_users(), and get_all_users().
i_have_this_token()
CO_Andisol::i_have_this_token ($in_token_to_test)
Tests a token, to see if the current user has it.
Returns
true, if the current user has the given token.
Parameters
$in_token_to_test The token we are checking out
Definition at line 263 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->i_have_this_token($in_token_to_test);
     }
References get_chameleon_instance().
is_this_a_login_id()
CO_Andisol::is_this_a_login_id ($in_id)
This checks an ID, to see if it is a login ID.
Returns
true, if the ID is a login ID.
Parameters
$in_id The ID we are checking. Must be greater than 1.
Definition at line 1907 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->is_this_a_login_id($in_id);
     }
References get_chameleon_instance().
is_this_a_personal_id()
CO_Andisol::is_this_a_personal_id ($in_id)
This checks an ID, to see if it is a personal ID.
Returns
true, if the ID is a personal ID.
Parameters
$in_id The ID we are checking. Must be greater than 1.
Definition at line 1896 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->is_this_a_personal_id($in_id);
     }
References get_chameleon_instance().
key_is_unique()
CO_Andisol::key_is_unique ($in_key, $in_classname = 'CO_KeyValue_CO_Collection')
Returns
true, if the key is unique in the DB for the given class (regardless of whether or not we can see it).
Parameters
$in_key The key to test (a string).
$in_classname This is the class to search for the key. The default is the base class.
Definition at line 1150 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->key_is_unique($in_key, $in_classname);
     }
References get_chameleon_instance().
location_search()
CO_Andisol::location_search ($in_longitude_degrees, $in_latitude_degrees, $in_radius_kilometers, $page_size = 0, $initial_page = 0, $and_writeable = false, $count_only = false, $ids_only = false)
This is a search, based on a location and radius around that location. Only objects that have a longitude and latitude that fall within the radius will be returned. All visible classes and instances will be returned. Only location and security filtering are applied.
Returns
an array of instances (or integers, if $ids_only is true) that fit within the location center and radius. If $count_only is true, then it will be a single integer, with the count of responses to the search (if a page, then this count will only be the number of items on that page).
Parameters
$in_longitude_degrees REQUIRED: The latitude of the center, in degrees.
$in_latitude_degrees REQUIRED: The logitude of the center, in degrees.
$in_radius_kilometers REQUIRED: The search radius, in Kilomters.
$page_size OPTIONAL: If specified with a 1-based integer, this denotes the size of a "page" of results. NOTE: This is only applicable to MySQL or Postgres, and will be ignored if the DB is not MySQL or Postgres. Default is 0.
$initial_page OPTIONAL: This is ignored unless $page_size is greater than 0. If so, then this 0-based index will specify which page of results to return. Values beyond the maximum number of pages will result in no returned values.
$and_writeable OPTIONAL: If true, then we only want records we can modify.
$count_only OPTIONAL: If true (default is false), then only a single integer will be returned, with the count of items that fit the search.
$ids_only OPTIONAL: If true (default is false), then the return array will consist only of integers (the object IDs). If $count_only is true, this is ignored.
Definition at line 533 of file co_andisol.class.php.
{
         $ret = $this->generic_search(Array('location' => Array('longitude' => $in_longitude_degrees, 'latitude' => $in_latitude_degrees, 'radius' => $in_radius_kilometers)), false, $page_size, $initial_page, $and_writeable, $count_only, $ids_only);
         return $ret;
     }
References generic_search().
logged_in()
CO_Andisol::logged_in ()
Returns
true, if we have actually logged into the CHAMELEON instance.
Definition at line 221 of file co_andisol.class.php.
{
         return $this->valid() && ($this->get_chameleon_instance()->get_login_item() instanceof CO_Security_Login);
     }
References get_chameleon_instance(), and valid().
Referenced by _create_db_object(), delete_item_by_id(), get_login_item(), get_login_item_by_login_string(), manager(), and set_value_for_key().
make_new_blank_record()
CO_Andisol::make_new_blank_record ($in_classname)
This method instantiates a new, default instance of a class.
The instance does not reflect a database entity until it has had its update_db() method called.
Returns
a new, uninitialized instance of the requested class.
Parameters
$in_classname This is the name of the class to instantiate.
Definition at line 1829 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->make_new_blank_record($in_classname);
     }
References get_chameleon_instance().
make_security_token()
CO_Andisol::make_security_token ()
This creates a new security token. Only managers or God can do this.
Returns
an integer, with the new token. NULL, if this did not work.
Definition at line 1000 of file co_andisol.class.php.
{
         return $this->_make_security_token();
     }
References _make_security_token().
make_standalone_user()
CO_Andisol::make_standalone_user ()
Creates a new "standalone" user that has no associated login instance.
Returns
the new user record.
Definition at line 675 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->manager()) { // Don't even bother unless we're a manager.
             $ret = $login_item = $this->get_cobra_instance()->make_standalone_user();
             if (isset($ret) && ($ret instanceof CO_User_Collection)) {
                 $generic_name = sprintf(CO_ANDISOL_Lang::$andisol_new_unnamed_user_name_format, $ret->id());
                 $ret->set_name($generic_name);
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, CO_ANDISOL_Lang\$andisol_new_unnamed_user_name_format, get_cobra_instance(), and manager().
manager()
CO_Andisol::manager ()
Returns
true, if we are logged in as a COBRA Login Manager or as God.
Definition at line 229 of file co_andisol.class.php.
{
         return $this->logged_in() && ($this->get_cobra_instance() instanceof CO_Cobra);
     }
References get_cobra_instance(), and logged_in().
Referenced by _make_security_token(), create_new_user(), delete_user(), get_all_logins(), get_user_from_login(), god(), make_standalone_user(), and who_can_see().
remove_personal_token_from_this_login()
CO_Andisol::remove_personal_token_from_this_login ($in_to_id, $in_id)
This removes a token that is owned by one ID, from another ID.
Returns
true, if the operation was successful.
Parameters
$in_to_id The ID of the object we are affecting.
$in_id The ID (personal token) to be removed.
Definition at line 1930 of file co_andisol.class.php.
{
         return $this->get_chameleon_instance()->remove_personal_token_from_this_login($in_to_id, $in_id);
     }
References get_chameleon_instance().
set_personal_ids()
CO_Andisol::set_personal_ids ($in_login_id, $in_personal_ids = [])
This sets just the "personal" IDs for the given ID.
This should only be called by the "God" admin, and will fail, otherwise (returns empty array).
This is not an atomic operation. If any of the given IDs are also in the regular ID list, they will be removed from the personal IDs.
Returns
an array of integers, with the new personal security IDs (usually a copy of the input Array). It will be empty, if the procedure fails.
Parameters
$in_login_id The ID of the login we want to modify.
$in_personal_ids An Array of Integers, with the new personal IDs. This replaces any previous ones. If empty, then the IDs are removed.
Definition at line 1860 of file co_andisol.class.php.
{
         return $this->get_cobra_instance()->set_personal_ids($in_login_id, $in_personal_ids);
     }
References get_cobra_instance().
set_value_for_key()
CO_Andisol::set_value_for_key ($in_key, $in_value, $in_classname = 'CO_KeyValue_CO_Collection')
This sets a value to a key, creating the record, if need be. Passing in NULL will delete the key (if we have write access). We need to have a login for it to work at all. If the value already exists, then we need to have write access to it, or we will fail. This will only work if we are logged in.
Returns
true, if successful.
Parameters
$in_key REQUIRED: This is the key that we are setting. It must be a string.
$in_value REQUIRED: The value to set. If NULL, then we will delete the key.
$in_classname OPTIONAL: This is the class to use for the key. The default is the base class.
Definition at line 1191 of file co_andisol.class.php.
{
         $ret = NULL;
         if ($this->logged_in()) {
             $ret = $this->get_chameleon_instance()->set_value_for_key($in_key, $in_value, $in_classname);
             if (isset($this->get_chameleon_instance()->error)) {
                 $this->error = $this->get_chameleon_instance()->error;
             }
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_chameleon_instance(), and logged_in().
Referenced by delete_key().
tag_search()
CO_Andisol::tag_search ($in_tags_associative_array, $in_or_search = false, $page_size = 0, $initial_page = 0, $and_writeable = false, $count_only = false, $ids_only = false)
Returns
an array of instances (or integers, if $ids_only is true) that match the requested tag values. If $count_only is true, then it will be a single integer, with the count of responses to the search (if a page, then this count will only be the number of items on that page).
Parameters
$in_tags_associative_array REQUIRED: This is an associative array, with the keys being "0" through "9". Each element will have a requested value for that element. Leaving an element out will remove it as a search factor. Adding it, but leaving it NULL or blank, means that this tag MUST be null or blank. If you add an element called 'use_like' ('use_like' => 1) to the array, then you can use SQL-style "wildcards" (%) in your matches. Unless $in_or_search is set to true, the search will be an AND search; meaning that ALL the tag values must match, in order to result in a record being returned.
$in_or_search OPTIONAL: If true (Default is false), then the search will be an "OR" search (any of the values).
$page_size OPTIONAL: If specified with a 1-based integer, this denotes the size of a "page" of results. NOTE: This is only applicable to MySQL or Postgres, and will be ignored if the DB is not MySQL or Postgres. Default is 0.
$initial_page OPTIONAL: This is ignored unless $page_size is greater than 0. If so, then this 0-based index will specify which page of results to return. Values beyond the maximum number of pages will result in no returned values.
$and_writeable OPTIONAL: If true, then we only want records we can modify.
$count_only OPTIONAL: If true (default is false), then only a single integer will be returned, with the count of items that fit the search.
$ids_only OPTIONAL: If true (default is false), then the return array will consist only of integers (the object IDs). If $count_only is true, this is ignored.
Definition at line 622 of file co_andisol.class.php.
{
         $tags_array = Array();
         $ret = Array();
         return $ret;
     }
valid()
CO_Andisol::valid ()
Returns
true, if we have an active database connection (as represented by an active CHAMELEON instance).
Definition at line 213 of file co_andisol.class.php.
{
         return (NULL != $this->get_chameleon_instance()) && ($this->get_chameleon_instance() instanceof CO_Chameleon);
     }
References get_chameleon_instance().
Referenced by get_object_for_key(), get_value_for_key(), and logged_in().
who_can_see()
CO_Andisol::who_can_see ($in_test_target)
Test an item to see which logins can access it.
This is security-limited.
Returns
an array of instances of CO_Security_Login (Security Database login) items that can read/see the given item. If the read ID is 0 (open), then the function simply returns true. If nothing can see the item, then false is returned.
Parameters
$in_test_target REQUIRED: This is an instance of a subclass of A_CO_DB_Table_Base (General Database Record).
Definition at line 342 of file co_andisol.class.php.
{
         $ret = Array();
         if ($this->manager()) { // Don't even bother unless we're a manager.
             $ret = $this->get_cobra_instance()->who_can_see($in_test_target);
             $this->error = $this->get_cobra_instance()->error;
         } else {
             $this->error = new LGV_Error(   CO_ANDISOL_Lang_Common::$andisol_error_code_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_name_user_not_authorized,
                                             CO_ANDISOL_Lang::$andisol_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_ANDISOL_Lang_Common\$andisol_error_code_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_desc_user_not_authorized, CO_ANDISOL_Lang\$andisol_error_name_user_not_authorized, get_cobra_instance(), and manager().
Member Data Documentation
$_chameleon_instance
CO_Andisol::$_chameleon_instance = NULL protected
This is the CHAMELEON instance.
Definition at line 51 of file co_andisol.class.php.
Referenced by get_chameleon_instance().
$_cobra_instance
CO_Andisol::$_cobra_instance = NULL protected
This is the COBRA instance.
Definition at line 52 of file co_andisol.class.php.
Referenced by get_cobra_instance().
$error
CO_Andisol::$error
Any errors that occured are kept here.
Definition at line 55 of file co_andisol.class.php.
$version
CO_Andisol::$version
The version indicator.
Definition at line 54 of file co_andisol.class.php.