BAOBAB: CO_Chameleon Class Reference
CO_Chameleon Class Reference
Public Member Functions
__construct ($in_login_id=NULL, $in_hashed_password=NULL, $in_raw_password=NULL, $in_api_key=NULL)
fetch_backup ()
get_security_ids ($no_personal=false)
get_all_collections_for_element ($in_element)
count_all_login_objects_with_access ($in_security_token)
get_all_login_objects_with_access ($in_security_token, $and_write=false)
get_all_user_objects_with_access ($in_security_token)
get_lang ($in_login_id=NULL)
test_access ($in_login_id)
get_value_for_key ($in_key, $in_classname='CO_KeyValue_CO_Collection')
key_is_unique ($in_key, $in_classname='CO_KeyValue_CO_Collection')
get_object_for_key ($in_key)
set_value_for_key ($in_key, $in_value, $in_classname='CO_KeyValue_CO_Collection')
get_all_visible_users ()
get_all_visible_logins ()
get_user_from_login ($in_login_id=NULL)
Public Member Functions inherited from CO_Access
item_exists ($in_id, $in_visibility_test=false)
get_personal_security_ids ()
get_all_personal_ids_except_for_id ($in_id=0)
get_logins_with_personal_ids ()
is_this_a_personal_id ($in_id)
add_personal_token_from_current_login ($in_to_id, $in_id)
remove_personal_token_from_this_login ($in_to_id, $in_id)
get_logins_that_have_any_of_my_ids ()
is_this_a_login_id ($in_id)
get_available_tokens ($no_personal=false)
main_db_available ()
get_login_id ($in_login_id=NULL)
get_login_item ($in_login_id=NULL)
god_mode ()
check_login_exists ($in_login_id)
check_login_exists_by_login_string ($in_login_id_string)
get_login_item_by_login_string ($in_login_id_string)
check_user_exists ($in_login_id)
make_new_blank_record ($in_classname)
get_multiple_data_records_by_id ($in_id_array)
get_single_data_record_by_id ($in_id)
get_data_access_class_by_id ($in_id)
get_security_access_class_by_id ($in_id)
can_i_see_this_data_record ($in_id)
can_i_see_this_security_record ($in_id)
get_all_data_readable_records ($open_only=false, $in_this_id=NULL)
get_all_data_writeable_records ($in_this_id=NULL)
security_db_available ()
i_have_this_token ($in_token_to_test)
get_multiple_security_records_by_id ($in_id_array)
get_single_security_record_by_id ($in_id)
get_all_security_readable_records ($in_this_id=NULL)
get_all_security_writeable_records ($in_this_id=NULL)
write_data_record ($params_associative_array)
delete_data_record ($id)
generic_search ($in_search_parameters=NULL, $or_search=false, $page_size=0, $initial_page=0, $and_writeable=false, $count_only=false, $ids_only=false)
get_all_login_objects ($and_write=false)
get_all_tokens ()
Protected Attributes
$_special_access_id
This is a special ephemeral ID that we use to allow a manager to create a login, and add that login to its pool.
Protected Attributes inherited from CO_Access
$_data_db_object
This is the instance of the class representing the "data" database. This will always be instantiated.
$_security_db_object
This is the instance of the class representing the "scurity" database. This may not be instantiated, if there is no login.
$_login_id
This is an integer, containing the security DB ID of the logged-in user. It will be NULL for no login.
Additional Inherited Members
Public Attributes inherited from CO_Access
$valid
This will be true, if the instance is "valid" (has at least an initialized "data" database).
$error
If there was an error, it will be held here.
$class_description
This is a brief textual description of the class.
$version
This will contain the BADGER Version.
Detailed Description
Definition at line 41 of file co_chameleon.class.php.
Constructor & Destructor Documentation
__construct()
CO_Chameleon::__construct ($in_login_id = NULL, $in_hashed_password = NULL, $in_raw_password = NULL, $in_api_key = NULL)
The constructor.
Parameters
$in_login_id The login ID
$in_hashed_password The password, crypt-hashed
$in_raw_password The password, cleartext.
$in_api_key An API key, for REST.
Reimplemented from CO_Access.
Definition at line 49 of file co_chameleon.class.php.
{
         parent::__construct($in_login_id, $in_hashed_password, $in_raw_password, $in_api_key);
         $this->version = __CHAMELEON_VERSION__;
     }
References __CHAMELEON_VERSION__.
Member Function Documentation
count_all_login_objects_with_access()
CO_Chameleon::count_all_login_objects_with_access ($in_security_token)
You give a security ID, and you will get a count of all login objects that have that token in their list (or are of that ID).
This is not restricted, and will count logins that we don't otherwise know about.
It does not count the "God" admin, which always has access.
Returns
an integer, with the total count of logins with access to the ID. -1, if we are not allowed to see the token.
Parameters
$in_security_token An integer, with the requested security token.
Definition at line 142 of file co_chameleon.class.php.
{
         return $this->_security_db_object->count_all_login_objects_with_access($in_security_token);
     }
fetch_backup()
CO_Chameleon::fetch_backup ()
This is a special "God Mode-Only" method that dumps everything in both databases. It is used to generate a CSV backup file.
The user must be logged in as "God."
Returns
an associative array ('security' => array, 'data' => array') of two sets of associative arrays, with the dump. NULL if the user is not authorized.
Definition at line 66 of file co_chameleon.class.php.
{
         // Have to be "God," and the variable in the config needs to be set.
         if ($this->god_mode()) {
             $security_db_backup = $this->_security_db_object->get_db_backup();
             $data_db_backup = $this->_data_db_object->get_db_backup();
             return ['security' => $security_db_backup, 'data' => $data_db_backup];
         }
         return NULL;
     }
References CO_Access\god_mode().
get_all_collections_for_element()
CO_Chameleon::get_all_collections_for_element ($in_element)
This method chacks all the collections for the presence of the given element. If the collection is a direct parent of the element, it is returned.
Returns
an array of collection objects. If the element has no parents, then NULL is returned.
Parameters
$in_element The element we're looking for parents.
Definition at line 106 of file co_chameleon.class.php.
{
         $ret = NULL;
         if (isset($in_element) && $in_element && ($in_element->get_access_object() == $this)) {
             $collection_objects = $this->generic_search(Array('access_class' => Array('%_collection', 'use_like' => true)));
             if (isset($collection_objects) && is_array($collection_objects) && count($collection_objects)) {
                 foreach ($collection_objects as $parent_object) {
                     if ($parent_object->areYouMyDaddy($in_element, false)) {
                         if (!$ret) {
                             $ret = Array();
                         }
                         array_push($ret, $parent_object);
                     }
                 }
             }
         } else {    // If the item is invalid, we not only give a NULL, we also flag an error.
             $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_collection_error_code_item_not_valid,
                                             CO_CHAMELEON_Lang::$co_collection_error_name_item_not_valid,
                                             CO_CHAMELEON_Lang::$co_collection_error_desc_item_not_valid);
         }
         return $ret;
     }
References CO_CHAMELEON_Lang_Common\$co_collection_error_code_item_not_valid, CO_CHAMELEON_Lang\$co_collection_error_desc_item_not_valid, CO_CHAMELEON_Lang\$co_collection_error_name_item_not_valid, and CO_Access\generic_search().
get_all_login_objects_with_access()
CO_Chameleon::get_all_login_objects_with_access ($in_security_token, $and_write = false)
You give a security ID, and you will get an array, with the login objects that have that token in their list (or are of that ID).
This is security restricted, and will not return logins that we don't otherwise know about.
Returns
an array, with the login objects that have that token in their list (or are of that ID).
Parameters
$in_security_token An integer, with the requested security token.
$and_write If true, then we only want ones we have write access to.
Reimplemented from CO_Access.
Definition at line 155 of file co_chameleon.class.php.
{
         return $this->_security_db_object->get_all_login_objects_with_access($in_security_token, $and_write);
     }
get_all_user_objects_with_access()
CO_Chameleon::get_all_user_objects_with_access ($in_security_token)
You give a security ID, and you will get an array, with the user objects, associated with login objects that have that token in their list (or are of that ID).
This is security restricted, and will not return users that we don't otherwise know about.
Returns
an array, with the user objects, associated with login objects that have that token in their list (or are of that ID).
Parameters
$in_security_token An integer, with the requested security token.
Reimplemented from CO_Access.
Definition at line 169 of file co_chameleon.class.php.
{
         return $this->_security_db_object->get_all_user_objects_with_access($in_security_token);
     }
get_all_visible_logins()
CO_Chameleon::get_all_visible_logins ()
Returns
a simple associative array, indexed by login (not user) IDs, with each element being an array, containing the name (usually display name) of the login object in [0], and the login ID, in [1]. It reurns ALL logins visible to the current login.
Definition at line 360 of file co_chameleon.class.php.
{
         return $this->_security_db_object->get_all_visible_users();
     }
get_all_visible_users()
CO_Chameleon::get_all_visible_users ()
Returns
a simple associative array, indexed by user (not login) IDs, with each element being the name (usually display name) of the user object. It reurns ALL users visible to the current login.
Definition at line 352 of file co_chameleon.class.php.
{
         return $this->_data_db_object->get_all_visible_users();
     }
get_lang()
CO_Chameleon::get_lang ($in_login_id = NULL)
This returns the language string for the given user/login.
If there is a user item associated with the login, then that gets first dibs. Login item gets dibs over default server.
Returns
a string, with the language ID for the login. If none, the the server default is returned.
Parameters
$in_login_id The integer login ID to check. If not-NULL, then the ID of a login instance. It must be one that the current user can see.
Reimplemented from CO_Access.
Definition at line 182 of file co_chameleon.class.php.
{
         $ret = parent::get_lang();
         $login_item = $this->get_login_item($in_login_id);
         if ($login_item) {
             $user_item = $this->get_user_from_login($login_item->login_id);
             if ($user_item) {
                 $ret = $user_item->get_lang();
             }
         }
         return $ret;
     }
References CO_Access\get_login_item(), and get_user_from_login().
get_object_for_key()
CO_Chameleon::get_object_for_key ($in_key)
Returns
the object that stores the given key. NULL, if no value or instance for the key.
Parameters
$in_key This is the key that we are searching for. It must be a string.
Definition at line 257 of file co_chameleon.class.php.
{
         $ret = NULL;
         $value_object_array = $this->generic_search(Array('access_class' => Array('%_KeyValue%', 'use_like' => 1), 'tags' => Array(strval($in_key))));
         if (isset($value_object_array) && is_array($value_object_array) && count($value_object_array)) {
             $ret = $value_object_array[0]; // If the DB is messed up, we could get more than one. In that case, we only take the first one.
         }
         return $ret;
     }
References CO_Access\generic_search().
get_security_ids()
CO_Chameleon::get_security_ids ($no_personal = false)
This fetches the list of security tokens the currently logged-in user has available. This will reload any non-God Mode IDs before fetching the IDs, in order to spike privilege escalation. If they have God Mode, then you're pretty much screwed, anyway.
Returns
an array of integers, with each one representing a security token. The first element will always be the ID of the user.
Parameters
$no_personal This is optional. If we DO NOT want personal tokens included, this should be set to true. Default is false (include personal tokens).
Reimplemented from CO_Access.
Definition at line 86 of file co_chameleon.class.php.
{
         $ret = parent::get_security_ids($no_personal);
         if (isset($this->_special_access_id)) {
             $id = $this->_special_access_id;
             unset($this->_special_access_id);
             $ret[] = intval($id);
         }
         return $ret;
     }
References $_special_access_id.
get_user_from_login()
CO_Chameleon::get_user_from_login ($in_login_id = NULL)
Returns
the user collection object for a given login. If there is no login given, then the current login is assumed. This is subject to security restrictions.
Parameters
$in_login_id The login ID that is associated with the user collection. If NULL, then the current login is used.
Definition at line 368 of file co_chameleon.class.php.
{
         $ret = NULL;
         $login_id = $this->get_login_id();  // Default is the current login.
         if (isset($in_login_id) && (0 < intval($in_login_id))) {    // See if they seek a different login.
             $login_id = intval($in_login_id);
         }
         $tag0 = strval($login_id);
         $ret_temp = $this->generic_search(Array('access_class' => Array('%_user_collection', 'use_like' => true), 'tags' => Array($tag0)));
         if (isset($ret_temp) && is_array($ret_temp) && count($ret_temp)) {
             $ret = $ret_temp[0];    // We only get the first one. Multiple responses mean the DB is not so healthy.
         }
         return $ret;
     }
References CO_Access\generic_search(), and CO_Access\get_login_id().
Referenced by get_lang().
get_value_for_key()
CO_Chameleon::get_value_for_key ($in_key, $in_classname = 'CO_KeyValue_CO_Collection')
Returns
the value for a given key. It is dependent on the class passed in. NULL, if no value or instance for the key.
Parameters
$in_key This is the key that we are searching for. It must be a string.
$in_classname This is the class to search for the key. The default is the base class.
Definition at line 227 of file co_chameleon.class.php.
{
         $ret = NULL;
         $value_object_array = $this->generic_search(Array('access_class' => $in_classname, 'tags' => Array(strval($in_key))));
         if (isset($value_object_array) && is_array($value_object_array) && count($value_object_array)) {
             $value_object = $value_object_array[0]; // If the DB is messed up, we could get more than one. In that case, we only take the first one.
             if (isset($value_object) && ($value_object instanceof CO_KeyValue_CO_Collection)) {
                 $ret = $value_object->get_value();
             }
         }
         return $ret;
     }
References CO_Access\generic_search().
key_is_unique()
CO_Chameleon::key_is_unique ($in_key, $in_classname = 'CO_KeyValue_CO_Collection')
Returns
true, if the key is unique in the DB for the given class (regardless of whether or not we can see it).
Parameters
$in_key The key to test (a string).
$in_classname This is the class to search for the key. The default is the base class.
Definition at line 247 of file co_chameleon.class.php.
{
         return $this->_data_db_object->tag0_is_unique($in_key, $in_classname);
     }
set_value_for_key()
CO_Chameleon::set_value_for_key ($in_key, $in_value, $in_classname = 'CO_KeyValue_CO_Collection')
This sets a value to a key, creating the record, if need be. Passing in NULL will delete the key (if we have write access). We need to have a login for it to work at all. If the value already exists, then we need to have write access to it, or we will fail.
Returns
true, if successful.
Parameters
$in_key This is the key that we are setting. It must be a string.
$in_value The value to set. If NULL, then we will delete the key.
$in_classname This is the class to use for the key. The default is the base class.
Definition at line 276 of file co_chameleon.class.php.
{
         $ret = false;
         if ($this->security_db_available()) {   // Must be logged in.
             // First, we look for the object.
             $value_object = $this->generic_search(Array('access_class' => $in_classname, 'tags' => Array(strval($in_key))));
             if ((NULL != $in_value) && (!isset($value_object) || !$value_object)) {
                 $value_object = $this->make_new_blank_record($in_classname);
                 if (isset($value_object) && ($value_object instanceof CO_KeyValue_CO_Collection) && $value_object->user_can_write()) {
                     $ret = $value_object->set_name($in_key);
                     $ret = $value_object->set_key($in_key);
                     if (!$ret) {
                         $this->error = $value_object->error;
                         $value_object->delete_from_db();
                         $value_object = NULL;
                         if (!$this->error) {
                             $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_instance_failed_to_initialize,
                                                             CO_CHAMELEON_Lang::$co_key_value_error_name_instance_failed_to_initialize,
                                                             CO_CHAMELEON_Lang::$co_key_value_error_desc_instance_failed_to_initialize);
                         }
                     }
                }
             } elseif (isset($value_object) && is_array($value_object) && count($value_object)) {
                 $value_object = $value_object[0];
             } else {
                 $value_object = NULL;
                 $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_instance_failed_to_initialize,
                                                 CO_CHAMELEON_Lang::$co_key_value_error_name_instance_failed_to_initialize,
                                                 CO_CHAMELEON_Lang::$co_key_value_error_desc_instance_failed_to_initialize);
             }
             if (isset($value_object) && ($value_object instanceof CO_KeyValue_CO_Collection) && $value_object->user_can_write()) {
                 if (NULL == $in_value) {    // If we are deleting, we ask the object to go quietly into the great beyond.
                     $ret = $value_object->delete_from_db();
                 } else {                    // Otherwise, we just set the value.
                     $ret = $value_object->set_tag(0, $in_key);
                     if ($ret) {
                         $ret = $value_object->set_value($in_value);
                     } else {
                         $this->error = $value_object->error;
                         if (!$this->error) {
                             $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_instance_failed_to_initialize,
                                                             CO_CHAMELEON_Lang::$co_key_value_error_name_instance_failed_to_initialize,
                                                             CO_CHAMELEON_Lang::$co_key_value_error_desc_instance_failed_to_initialize);
                         }
                     }
                 }
             } else {
                 if (isset($value_object) && ($value_object instanceof CO_KeyValue_CO_Collection) && !$value_object->user_can_write()) {
                     $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_user_not_authorized,
                                                     CO_CHAMELEON_Lang::$co_key_value_error_name_user_not_authorized,
                                                     CO_CHAMELEON_Lang::$co_key_value_error_desc_user_not_authorized);
                 } else {
                     $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_instance_failed_to_initialize,
                                                     CO_CHAMELEON_Lang::$co_key_value_error_name_instance_failed_to_initialize,
                                                     CO_CHAMELEON_Lang::$co_key_value_error_desc_instance_failed_to_initialize);
                 }
             }
         } else {
             $this->error = new LGV_Error(   CO_CHAMELEON_Lang_Common::$co_key_value_error_code_user_not_authorized,
                                             CO_CHAMELEON_Lang::$co_key_value_error_name_user_not_authorized,
                                             CO_CHAMELEON_Lang::$co_key_value_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_CHAMELEON_Lang_Common\$co_key_value_error_code_instance_failed_to_initialize, CO_CHAMELEON_Lang_Common\$co_key_value_error_code_user_not_authorized, CO_CHAMELEON_Lang\$co_key_value_error_desc_instance_failed_to_initialize, CO_CHAMELEON_Lang\$co_key_value_error_desc_user_not_authorized, CO_CHAMELEON_Lang\$co_key_value_error_name_instance_failed_to_initialize, CO_CHAMELEON_Lang\$co_key_value_error_name_user_not_authorized, CO_Access\generic_search(), CO_Access\make_new_blank_record(), and CO_Access\security_db_available().
test_access()
CO_Chameleon::test_access ($in_login_id)
This tests a login ID for the special "Heisenberg" one-time test.
Returns
true, if the item was a login, and had the flag set.
Parameters
$in_login_id The ID of the instance to test.
Definition at line 204 of file co_chameleon.class.php.
{
         $ret = false;
         // Yeah, this will crash if we're not in COBRA. Good.
         if ($this->security_db_available() && ($this->get_login_item() instanceof CO_Login_Manager)) {
             $item_to_test = $this->_security_db_object->get_initial_record_by_id($in_login_id);
             if (($item_to_test instanceof CO_Cobra_Login) || ($item_to_test instanceof CO_Security_ID)) {
                 $ret = $item_to_test->security_exemption();
                 if ($ret) {
                     $this->_special_access_id = $in_login_id;
                 }
             }
         }
         return $ret;
     }
References CO_Access\get_login_item(), and CO_Access\security_db_available().
Member Data Documentation
$_special_access_id
CO_Chameleon::$_special_access_id protected
This is a special ephemeral ID that we use to allow a manager to create a login, and add that login to its pool.
Definition at line 42 of file co_chameleon.class.php.
Referenced by get_security_ids().