BAOBAB: CO_Cobra Class Reference
CO_Cobra Class Reference
Public Member Functions
get_security_ids ()
make_standalone_user ()
get_login_instance ($in_login_id)
get_user_from_login ($in_login_id=NULL, $in_make_user_if_necessary=false)
create_new_standard_login ($in_login_id, $in_cleartext_password, $in_security_token_ids=NULL)
create_new_manager_login ($in_login_id, $in_cleartext_password, $in_security_token_ids=NULL)
convert_login ($in_login_id, $in_is_login_manager=false)
delete_login ($in_login_id, $also_delete_user=false)
get_all_logins ($and_write=false, $in_login_id=NULL, $in_login_integer_id=NULL)
who_can_see ($in_test_target)
who_can_modify ($in_test_target, $non_managers_only=false)
make_security_token ()
Static Public Member Functions
static make_cobra ($in_chameleon_instance)
Public Attributes
$version
The version indicator.
Protected Member Functions
_convert_login ($in_login_id, $in_is_login_manager=false)
_create_new_login ($in_login_id, $in_cleartext_password, $in_security_token_ids=NULL, $in_is_login_manager=false)
Private Member Functions
__construct ($in_chameleon_instance=NULL)
Private Attributes
$_chameleon_instance = NULL
This is the CHAMELEON instance that is associated with this COBRA instance.
Detailed Description
This class implements a "login manager" functionality to The Rift Valley Platform.
This class can only be instantiated by the "God" login, or a login that is a CO_Login_Manager.
You use COBRA to manage other logins, or security tokens.
Definition at line 46 of file co_cobra.class.php.
Constructor & Destructor Documentation
__construct()
CO_Cobra::__construct ($in_chameleon_instance = NULL) private
The constructor.
We declare it private to prevent it being instantiated outside the factory.
Parameters
$in_chameleon_instance The CHAMELEON instance associated with this COBRA instance.
Definition at line 88 of file co_cobra.class.php.
{
         $this->_chameleon_instance = $in_chameleon_instance;
         $this->version = __COBRA_VERSION__;
     }
References __COBRA_VERSION__.
Member Function Documentation
_convert_login()
CO_Cobra::_convert_login ($in_login_id, $in_is_login_manager = false) protected
This is the internal function used to convert a login to (or from) a manager, in the security database. This can only be called from a login manager.
Returns
the converted instance.
Parameters
$in_login_id The login ID as text. This must be for a login that can be managed by the current manager.
$in_is_login_manager If true, then this is a "promotion" to a a manager. If false (default), then this is a "demotion" to a standard user.
Definition at line 101 of file co_cobra.class.php.
{
         $ret = NULL;
         $working_login = $this->_chameleon_instance->get_login_item_by_login_string($in_login_id);   // This is the login we are changing.
         $manager = $this->_chameleon_instance->get_login_item();                                    // This is our current login.
         // Make sure we are a login manager, first, and that we have write permission on the user.
         if ($working_login && $working_login->user_can_write() && ($manager instanceof CO_Login_Manager || $manager->is_god())) {
             // Now, make sure that we're actually making a change.
             if (($in_is_login_manager && !$working_login->is_manager()) || (!$in_is_login_manager && $working_login->is_manager())) {
                 $className = $in_is_login_manager ? 'CO_Login_Manager' : 'CO_Cobra_Login';
                 $user_object = $this->get_user_from_login($working_login->id());    // Get this, so we can modify it.
                 // Create a new blank instance.
                 $new_login_object = $this->_chameleon_instance->make_new_blank_record($className);
                 if (isset($new_login_object) && ($new_login_object instanceof CO_Cobra_Login)) {
                     $original_login_id = $working_login->id();
                     $original_ids = $working_login->ids();
                     if (!isset($original_ids)) {
                         $original_ids = [];
                     }
                     array_push($original_ids, $original_login_id);    // We will add this to the new login's IDs.
                     $original_ids = array_unique($original_ids);
                     asort($original_ids);
                     $new_login_object->login_id = $working_login->login_id;
                     $new_login_object->name = $working_login->name;
                     $new_login_object->context = $working_login->context;
                     $new_login_object->set_ids($original_ids);
                     // OK. At this point, we have a new login that is of the type that we want. It is different from the previous one, and has all the relevant data.
                     // Now, we will delete the old one, and then replace it with the new one.
                     if ($working_login->delete_from_db()) {
                         if ($new_login_object->update_db()) {
                             $new_id = $new_login_object->id();
                             if (method_exists($manager, 'add_new_login_id')) {  // We only add the ID, if we are a manager object. God doesn't need this.
                                 $manager->add_new_login_id($new_id);
                             }
                             $new_login_object->read_security_id = $new_id;
                             $new_login_object->write_security_id = $new_id;
                             if ($new_login_object->update_db()) {
                                 $user_object->write_security_id = $new_id;
                                 $user_object->set_login($new_id);
                                 if ($user_object->update_db()) {
                                     $ret = $new_login_object;   // If everything went well, to this point, we update the return.
                                 } else {
                                     $this->error = $user_object->error;
                                 }
                             } else {
                                 $this->error = $new_login_object->error;
                             }
                         } else {
                             $this->error = $new_login_object->error;
                         }
                     } else {
                         $this->error = $working_login->error;
                     }
                 }
             }
         }
         return $ret;
     }
References get_user_from_login(), and CO_Security_Login\is_god().
Referenced by convert_login().
_create_new_login()
CO_Cobra::_create_new_login ($in_login_id, $in_cleartext_password, $in_security_token_ids = NULL, $in_is_login_manager = false) protected
This is the internal function used to create a new login in the security database. This can only be called from a login manager.
Returns
the new CO_Cobra_Login instance (or CO_Login_Manager instance).
Parameters
$in_login_id The login ID as text. It needs to be unique, within the Security database, and this will fail, if it is not.
$in_cleartext_password The password to set (in cleartext). It will be stored as a hashed password.
$in_security_token_ids An array of integers. These are security token IDs for the login (default is NULL). If NULL, then no IDs will be set. These IDs must be selected from those available to the currently logged-in manager.
$in_is_login_manager true, if we want a CO_Login_Manager instance, instead of a CO_Cobra_Login instance. Default is false.
Definition at line 174 of file co_cobra.class.php.
{
         $ret = NULL;
         if (isset($in_login_id) && !$this->_chameleon_instance->check_login_exists_by_login_string($in_login_id)) {
             $manager = $this->_chameleon_instance->get_login_item();
             if ($manager instanceof CO_Login_Manager || $manager->is_god()) { // Make sure we are a login manager, first.
                 $use_these_ids = Array();
                 // Next, see if they provided IDs. If so, we remove any that we don't own.
                 if (isset($in_security_token_ids) && is_array($in_security_token_ids) && count($in_security_token_ids)) {
                     $my_ids = $this->get_security_ids();
                     foreach ($in_security_token_ids as $id) {
                         if (in_array($id, $my_ids)) {
                             array_push($use_these_ids, $id);
                         }
                     }
                     // At this point, only IDs that we have available are in the array.
                 }
                 $className = $in_is_login_manager ? 'CO_Login_Manager' : 'CO_Cobra_Login';
                 $new_login_object = $this->_chameleon_instance->make_new_blank_record($className);
                 if (isset($new_login_object) && ($new_login_object instanceof CO_Cobra_Login)) {
                     $new_login_object->login_id = $in_login_id;
                     if (strlen($in_cleartext_password) >= CO_Config::$min_pw_len) {
                         $new_login_object->context['hashed_password'] = password_hash($in_cleartext_password, PASSWORD_DEFAULT);
                         if (!$new_login_object->update_db()) {
                             $this->error = $new_login_object->error;
                             $new_login_object->delete_from_db();
                             $new_login_object = NULL;
                         } else {
                             $new_id = $new_login_object->id();
                             if (method_exists($manager, 'add_new_login_id')) {
                                 $manager->add_new_login_id($new_id);
                             }
                             if ($new_login_object->set_read_security_id($new_id)) {
                                 if ($new_login_object->set_write_security_id($new_id)) {
                                     $new_ids = [];
                                     foreach ($use_these_ids as $id) {
                                         if (in_array($id, $my_ids) && ($id != $new_id)) {
                                             array_push($new_ids, $id);
                                         }
                                     }
                                     if ($new_login_object->set_ids($new_ids)) {
                                         $ret = $new_login_object;
                                     } else {
                                         $this->error = $new_login_object->error;
                                         $new_login_object->delete_from_db();
                                         $new_login_object = NULL;
                                     }
                                 } else {
                                     $this->error = $new_login_object->error;
                                     $new_login_object->delete_from_db();
                                     $new_login_object = NULL;
                                 }
                             } else {
                                 $this->error = $new_login_object->error;
                                 $new_login_object->delete_from_db();
                                 $new_login_object = NULL;
                             }
                         }
                     } else {
                         $new_login_object->delete_from_db();
                         $new_login_object = NULL;
                         $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_password_too_short,
                                                         CO_COBRA_Lang::$cobra_error_name_password_too_short,
                                                         CO_COBRA_Lang::$cobra_error_desc_password_too_short);
                     }
                 } else {
                     if (isset($this->_chameleon_instance->error)) {
                         $this->error = $this->_chameleon_instance->error;
                     } else {
                         $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_instance_failed_to_initialize,
                                                         CO_COBRA_Lang::$cobra_error_name_instance_failed_to_initialize,
                                                         CO_COBRA_Lang::$cobra_error_desc_instance_failed_to_initialize);
                     }
                 }
             } else {
                 $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_not_authorized,
                                                 CO_COBRA_Lang::$cobra_error_name_user_not_authorized,
                                                 CO_COBRA_Lang::$cobra_error_desc_user_not_authorized);
             }
         } elseif (isset($in_login_id)) {
             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_already_exists,
                                             CO_COBRA_Lang::$cobra_error_name_user_already_exists,
                                             CO_COBRA_Lang::$cobra_error_desc_user_already_exists);
         } else {
             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_login_error,
                                             CO_COBRA_Lang::$cobra_error_name_login_error,
                                             CO_COBRA_Lang::$cobra_error_desc_login_error);
         }
         return $ret;
     }
References CO_COBRA_Lang_Common\$cobra_error_code_instance_failed_to_initialize, CO_COBRA_Lang_Common\$cobra_error_code_login_error, CO_COBRA_Lang_Common\$cobra_error_code_password_too_short, CO_COBRA_Lang_Common\$cobra_error_code_user_already_exists, CO_COBRA_Lang_Common\$cobra_error_code_user_not_authorized, CO_COBRA_Lang\$cobra_error_desc_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_desc_login_error, CO_COBRA_Lang\$cobra_error_desc_password_too_short, CO_COBRA_Lang\$cobra_error_desc_user_already_exists, CO_COBRA_Lang\$cobra_error_desc_user_not_authorized, CO_COBRA_Lang\$cobra_error_name_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_name_login_error, CO_COBRA_Lang\$cobra_error_name_password_too_short, CO_COBRA_Lang\$cobra_error_name_user_already_exists, CO_COBRA_Lang\$cobra_error_name_user_not_authorized, get_security_ids(), and CO_Security_Login\is_god().
Referenced by create_new_manager_login(), and create_new_standard_login().
convert_login()
CO_Cobra::convert_login ($in_login_id, $in_is_login_manager = false)
This is the public function used to convert a login to (or from) a manager, in the security database. This can only be called from a login manager. The user is not affected, and the login IDs (tokens) are also left "as is."
Returns
the converted instance.
Parameters
$in_login_id The login ID as text. This must be for a login that can be managed by the current manager.
$in_is_login_manager If true, then this is a "promotion" to a a manager. If false (default), then this is a "demotion" to a standard user.
Definition at line 449 of file co_cobra.class.php.
{
         return $this->_convert_login($in_login_id, $in_is_login_manager);
     }
References _convert_login().
create_new_manager_login()
CO_Cobra::create_new_manager_login ($in_login_id, $in_cleartext_password, $in_security_token_ids = NULL)
This is the public function used to create a new login manager login in the security database. This can only be called from a login manager.
Returns
the new CO_Login_Manager instance.
Parameters
$in_login_id The login ID as text. It needs to be unique, within the Security database, and this will fail, if it is not.
$in_cleartext_password The password to set (in cleartext). It will be stored as a hashed password.
$in_security_token_ids An array of integers. These are security token IDs for the login (default is NULL). If NULL, then no IDs will be set. These IDs must be selected from those available to the currently logged-in manager.
Definition at line 434 of file co_cobra.class.php.
{
         return $this->_create_new_login($in_login_id, $in_cleartext_password, $in_security_token_ids, true);
     }
References _create_new_login().
create_new_standard_login()
CO_Cobra::create_new_standard_login ($in_login_id, $in_cleartext_password, $in_security_token_ids = NULL)
This is the public function used to create a new standard login in the security database. This can only be called from a login manager.
Returns
the new CO_Cobra_Login instance.
Parameters
$in_login_id The login ID as text. It needs to be unique, within the Security database, and this will fail, if it is not.
$in_cleartext_password The password to set (in cleartext). It will be stored as a hashed password.
$in_security_token_ids An array of integers. These are security token IDs for the login (default is NULL). If NULL, then no IDs will be set. These IDs must be selected from those available to the currently logged-in manager.
Definition at line 420 of file co_cobra.class.php.
{
         return $this->_create_new_login($in_login_id, $in_cleartext_password, $in_security_token_ids);
     }
References _create_new_login().
delete_login()
CO_Cobra::delete_login ($in_login_id, $also_delete_user = false)
This deletes a login, given the login ID. When we delete a login, it actually gets changed into a security ID instance (to reserve the ID slot), however, the user object is actually removed. It should be noted that deleting a (user) collection does not delete everything in the collection; only the collection object, itself.
Returns
true, if the operation (or operations) succeeded.
Parameters
$in_login_id The login ID as text.
$also_delete_user If true (Default is false), then we will also delete the user record associated with this login.
Definition at line 463 of file co_cobra.class.php.
{
         $ret = false;
         $cobra_login_instance = $this->get_login_instance($in_login_id);
         if ($cobra_login_instance) {
             $cobra_user_instance = NULL;
             if ($also_delete_user) {
                 $cobra_user_instance = $this->get_user_from_login($cobra_login_instance->id());
             }
             $ret = $cobra_login_instance->delete_from_db();
             if ($ret && $cobra_user_instance) {
                 $ret = $cobra_user_instance->delete_from_db();
             }
         }
         return $ret;
     }
References get_login_instance(), and get_user_from_login().
get_all_logins()
CO_Cobra::get_all_logins ($and_write = false, $in_login_id = NULL, $in_login_integer_id = NULL)
Returns
an array of instances of all the logins that are visible to the current user (or a supplied user, if in "God" mode).
Parameters
$and_write If true, then we only want ones we have write access to.
$in_login_id This is ignored, unless this is the God login. If We are logged in as God, then we can select a login via its string login ID, and see what logins are available to it.
$in_login_integer_id This is ignored, unless this is the God login and $in_login_id is not specified. If We are logged in as God, then we can select a login via its integer login ID, and see what logins are available to it.
Definition at line 491 of file co_cobra.class.php.
{
         if (!$this->_chameleon_instance->god_mode()) {  // Definitely won't look at this unless we are God.
             $in_login_id = NULL;
             $in_login_integer_id = 0;
         } else {
             $in_login_id = trim(strval($in_login_id));
             if (!$in_login_id) {    // String login ID trumps integer.
                 $in_login_integer_id = intval($in_login_integer_id);
             } else {
                 $item = $this->_chameleon_instance->get_login_item_by_login_string($in_login_id);
                 $in_login_id = NULL;
                 $in_login_integer_id = $item->id();
             }
         }
         // If both $in_login_id and $in_login_integer_id are unspecified, then we'll find every login we can see.
         // If they are specified (which means we're God), then we filter for only the
         $id_list = Array();
         $results = $this->_chameleon_instance->get_all_login_objects($and_write);
         if (isset($results) && is_array($results) && count($results)) {
             foreach ($results as $result) {
                 if (!$in_login_integer_id || ($in_login_integer_id == $result->id())) {
                     $id_list[] = $result->id();
                     foreach ($result->ids() as $id) {
                         if (($id != CO_Config::god_mode_id()) || (($id == CO_Config::god_mode_id()) && ($in_login_integer_id == CO_Config::god_mode_id()))) {
                             $id_list[] = $id;
                         }
                     }
                 }
             }
         }
         $id_list = array_unique($id_list);
         $ret = Array();
         foreach ($id_list as $id) {
             $object = $this->_chameleon_instance->get_single_security_record_by_id($id);
             if ($object instanceof CO_Security_Login) {
                 $ret[] = $object;
             }
         }
         if (1 < count($ret)) {
             // Sort the results by ID.
             usort($ret, function ($a, $b) {
                                             if ($a->id() == $b->id()) {
                                                 return 0;
                                             }
                                             if ($a->id() < $b->id()) {
                                                 return -1;
                                             }
                                             return 1;
                                             });
         }
         return $ret;
     }
References if.
get_login_instance()
CO_Cobra::get_login_instance ($in_login_id)
This returns the login instance for the given ID string.
This is scurity-vetted. The current login needs to be able to see the item.
Returns
the Login Item. NULL if unable to fetch the item.
Parameters
$in_login_id The string login ID that we are referencing.
Definition at line 332 of file co_cobra.class.php.
{
         $ret = NULL;
         if (isset($in_login_id) && $in_login_id) {
             $ret = $this->_chameleon_instance->get_login_item_by_login_string($in_login_id);
             $this->error = $this->_chameleon_instance->error;
         }
         return $ret;
     }
Referenced by delete_login().
get_security_ids()
CO_Cobra::get_security_ids ()
Returns
an array of integers, with each one representing a special security token for editing security items.
Definition at line 280 of file co_cobra.class.php.
{
         return $this->_chameleon_instance->get_security_ids();
     }
Referenced by _create_new_login().
get_user_from_login()
CO_Cobra::get_user_from_login ($in_login_id = NULL, $in_make_user_if_necessary = false)
This fetches a user from a given login ID.
The user may be created, if the current login is a Login Manager, and the second parameter is set to true.
Returns
an instance of a user collection. If new, it will be blank.
Parameters
$in_login_id The integer login ID that is associated with the user collection. If NULL, then the current login is used.
$in_make_user_if_necessary If true (Default is false), then the user will be created if it does not already exist. Ignored, if we are not a Login Manager.
Definition at line 353 of file co_cobra.class.php.
{
         $user = $this->_chameleon_instance->get_user_from_login($in_login_id);   // First, see if it's already a thing.
         if (!$user && $in_make_user_if_necessary && ($this->_chameleon_instance->god_mode() || ($this->_chameleon_instance->get_login_item() instanceof CO_Login_Manager))) {   // If not, we will create a new one, based on the given login. We must be a manager.
             if (isset($in_login_id) && (0 < intval($in_login_id))) {    // See if they seek a different login.
                 $login_id = intval($in_login_id);
             }
             // Assuming all is well, we need to create a new user. We have to be a login manager to do this.
             if (isset($in_login_id) && (0 < intval($in_login_id))) {
                 $login_item = $this->_chameleon_instance->get_login_item($in_login_id);
                 if (isset($login_item) && ($login_item instanceof CO_Security_Login)) {
                     if (!$this->_chameleon_instance->check_user_exists($in_login_id)) {
                         $user = $this->make_standalone_user();
                         if ($user) {
                             $user->set_login($in_login_id); // We set the user's login instance to the login instance we're using as the basis.
                             if (isset($user->error)) {
                                 $this->error = $user->error;
                                 $user->delete_from_db();
                                 $user = NULL;
                             } else {
                                 $user->set_write_security_id($in_login_id); // Make sure the user can modify their own record.
                                 if (isset($user->error)) {
                                     $this->error = $user->error;
                                     $user->delete_from_db();
                                     $user = NULL;
                                 }
                             }
                         } else {
                             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_instance_failed_to_initialize,
                                                             CO_COBRA_Lang::$cobra_error_name_instance_failed_to_initialize,
                                                             CO_COBRA_Lang::$cobra_error_desc_instance_failed_to_initialize);
                         }
                     } else {
                         $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_already_exists,
                                                         CO_COBRA_Lang::$cobra_error_name_user_already_exists,
                                                         CO_COBRA_Lang::$cobra_error_desc_user_already_exists);
                     }
                 } else {
                     $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_login_unavailable,
                                                     CO_COBRA_Lang::$cobra_error_name_login_unavailable,
                                                     CO_COBRA_Lang::$cobra_error_desc_login_unavailable);
                 }
             } else {
                 $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_login_unavailable,
                                                 CO_COBRA_Lang::$cobra_error_name_login_unavailable,
                                                 CO_COBRA_Lang::$cobra_error_desc_login_unavailable);
             }
         } elseif (!($this->_chameleon_instance->get_login_item() instanceof CO_Login_Manager)) {
             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_name_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_desc_user_not_authorized);
         }
         return $user;
     }
References CO_COBRA_Lang_Common\$cobra_error_code_instance_failed_to_initialize, CO_COBRA_Lang_Common\$cobra_error_code_login_unavailable, CO_COBRA_Lang_Common\$cobra_error_code_user_already_exists, CO_COBRA_Lang_Common\$cobra_error_code_user_not_authorized, CO_COBRA_Lang\$cobra_error_desc_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_desc_login_unavailable, CO_COBRA_Lang\$cobra_error_desc_user_already_exists, CO_COBRA_Lang\$cobra_error_desc_user_not_authorized, CO_COBRA_Lang\$cobra_error_name_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_name_login_unavailable, CO_COBRA_Lang\$cobra_error_name_user_already_exists, CO_COBRA_Lang\$cobra_error_name_user_not_authorized, and make_standalone_user().
Referenced by _convert_login(), and delete_login().
make_cobra()
static CO_Cobra::make_cobra ($in_chameleon_instance) static
Factory Function.
This vets the CHAMELEON instance, and makes sure that it's valid before returning a constructed COBRA.
Returns
an instance of CO_Cobra upon success. If there was an error set by COBRA (or CHAMELEON), or the vetting failed, that is returned instead of a COBRA instance.
Definition at line 59 of file co_cobra.class.php.
{
         $ret = NULL;
         // We must have a valid CHAMELEON instance that is logged in. The login user must be a COBRA Manager user (the standard logins cannot use COBRA).
         if (isset($in_chameleon_instance)
             && ($in_chameleon_instance instanceof CO_Chameleon)
             && $in_chameleon_instance->security_db_available()
             && ($in_chameleon_instance->god_mode() || ($in_chameleon_instance->get_login_item() instanceof CO_Login_Manager))) {
             $ret = new CO_Cobra($in_chameleon_instance);
         } elseif (isset($in_chameleon_instance) && ($in_chameleon_instance instanceof CO_Chameleon)) {
             $ret = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_not_authorized,
                                     CO_COBRA_Lang::$cobra_error_name_user_not_authorized,
                                     CO_COBRA_Lang::$cobra_error_desc_user_not_authorized_instance);
         } else {
             $ret = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_invalid_chameleon,
                                     CO_COBRA_Lang::$cobra_error_name_invalid_chameleon,
                                     CO_COBRA_Lang::$cobra_error_desc_invalid_chameleon);
         }
         return $ret;
     }
References CO_COBRA_Lang_Common\$cobra_error_code_invalid_chameleon, CO_COBRA_Lang_Common\$cobra_error_code_user_not_authorized, CO_COBRA_Lang\$cobra_error_desc_invalid_chameleon, CO_COBRA_Lang\$cobra_error_desc_user_not_authorized_instance, CO_COBRA_Lang\$cobra_error_name_invalid_chameleon, and CO_COBRA_Lang\$cobra_error_name_user_not_authorized.
Referenced by CO_Andisol\__construct().
make_security_token()
CO_Cobra::make_security_token ()
This simply generates a new security token instance.
Security tokens are "the gift that keeps on giving." Once created, they can't easily be deleted. Only the God admin can delete them. They are permanent placeholders.
Returns
an integer, with the new ID, or 0, if the method failed (check error).
Definition at line 636 of file co_cobra.class.php.
{
         $ret = 0;
         $manager = $this->_chameleon_instance->get_login_item();
         if ($this->_chameleon_instance->god_mode() || ($manager instanceof CO_Login_Manager)) {
             $new_token = $this->_chameleon_instance->make_new_blank_record('CO_Security_ID');
             if (isset($new_token) && ($new_token instanceof CO_Security_ID)) {
                 $new_id = $new_token->id();
                 if ($this->_chameleon_instance->god_mode() || $manager->add_new_login_id($new_id)) {  // We need to do the "special excemption" add of the ID to the manager.
                     $ret = $new_id;
                 } else {    // We were unable to set the new token ID to the manager.
                     $new_token->delete_from_db();
                     $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_token_id_not_set,
                                                     CO_COBRA_Lang::$cobra_error_name_token_id_not_set,
                                                     CO_COBRA_Lang::$cobra_error_desc_token_id_not_set);
                 }
             } else {    // Token object did not get instantiated.
                 $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_token_instance_failed_to_initialize,
                                                 CO_COBRA_Lang::$cobra_error_name_token_instance_failed_to_initialize,
                                                 CO_COBRA_Lang::$cobra_error_desc_token_instance_failed_to_initialize);
             }
         } else {    // Should never happen, but what the hell...
             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_name_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_desc_user_not_authorized);
         }
         return $ret;
     }
References CO_COBRA_Lang_Common\$cobra_error_code_token_id_not_set, CO_COBRA_Lang_Common\$cobra_error_code_token_instance_failed_to_initialize, CO_COBRA_Lang_Common\$cobra_error_code_user_not_authorized, CO_COBRA_Lang\$cobra_error_desc_token_id_not_set, CO_COBRA_Lang\$cobra_error_desc_token_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_desc_user_not_authorized, CO_COBRA_Lang\$cobra_error_name_token_id_not_set, CO_COBRA_Lang\$cobra_error_name_token_instance_failed_to_initialize, and CO_COBRA_Lang\$cobra_error_name_user_not_authorized.
make_standalone_user()
CO_Cobra::make_standalone_user ()
Creates a new "standalone" user that has no associated login instance.
Returns
the new user record.
Definition at line 290 of file co_cobra.class.php.
{
         $user = NULL;
         if ($this->_chameleon_instance->god_mode() || ($this->_chameleon_instance->get_login_item() instanceof CO_Login_Manager)) {     // We have to be a manager to create a user.
             $user = $this->_chameleon_instance->make_new_blank_record('CO_User_Collection');
             if ($user) {
                 if (!isset($user->error)) {
                     $user->set_read_security_id(1); // Users default to 1 (only logged-in users can see).
                     $user->set_write_security_id($this->_chameleon_instance->get_login_item()->id()); // Make sure that only we can modify this record.
                     if (isset($user->error)) {
                         $this->error = $user->error;
                         $user->delete_from_db();
                         $user = NULL;
                     }
                 } else {
                     $this->error = $user->error;
                     $user->delete_from_db();
                     $user = NULL;
                 }
             } else {
                 $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_instance_failed_to_initialize,
                                                 CO_COBRA_Lang::$cobra_error_name_instance_failed_to_initialize,
                                                 CO_COBRA_Lang::$cobra_error_desc_instance_failed_to_initialize);
             }
         } elseif (!($this->_chameleon_instance->get_login_item() instanceof CO_Login_Manager)) {
             $this->error = new LGV_Error(   CO_COBRA_Lang_Common::$cobra_error_code_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_name_user_not_authorized,
                                             CO_COBRA_Lang::$cobra_error_desc_user_not_authorized);
         }
         return $user;
     }
References CO_COBRA_Lang_Common\$cobra_error_code_instance_failed_to_initialize, CO_COBRA_Lang_Common\$cobra_error_code_user_not_authorized, CO_COBRA_Lang\$cobra_error_desc_instance_failed_to_initialize, CO_COBRA_Lang\$cobra_error_desc_user_not_authorized, CO_COBRA_Lang\$cobra_error_name_instance_failed_to_initialize, and CO_COBRA_Lang\$cobra_error_name_user_not_authorized.
Referenced by get_user_from_login().
who_can_modify()
CO_Cobra::who_can_modify ($in_test_target, $non_managers_only = false)
Test an item to see which logins can modify it.
This is security-limited.
Returns
an array of instances of CO_Security_Login (Security Database login) items that can modify the given item. If the write ID is 0 (open), then the function simply returns true. If nothing can modify the item, then false is returned.
Parameters
$in_test_target This is a subclass of A_CO_DB_Table_Base (General Database Record).
$non_managers_only Ignored if the target is not an instance (or subclass) of CO_Security_Login. If true (default is false), then only login manager objects will be returned. If you supply a login object as the target, this is a quick way to see if any non-manager objects can modify it. In reality, there should be no non-manager objects that can modify a login, besides the login, itself.
Definition at line 589 of file co_cobra.class.php.
{
         $ret = false;
         if (isset($in_test_target) && ($in_test_target instanceof A_CO_DB_Table_Base)) {
             $id = intval($in_test_target->write_security_id);
             if (0 < $id) {
                 $ret = $this->_chameleon_instance->get_all_login_objects_with_access($id, true);
                 // Check to see if any non-manager objects can modify the login (should never be).
                 if (($in_test_target instanceof CO_Security_Login) && isset($ret) && is_array($ret) && $non_managers_only) {
                     $ret_temp = Array();
                     foreach ($ret as $login) {
                         if (!($login instanceof CO_Login_Manager)) {
                             $ret_temp[] = $login;
                         }
                     }
                     if (count($ret_temp)) {
                         $ret = $ret_temp;
                     } else {
                         $ret = false;
                     }
                 } elseif (!isset($ret) || !is_array($ret) || !count($ret)) {
                     $ret = false;
                 }
             } elseif (0 == $id) {
                 $ret = true;
             }
         }
         return $ret;
     }
who_can_see()
CO_Cobra::who_can_see ($in_test_target)
Test an item to see which logins can access it.
This is security-limited.
Returns
an array of instances of CO_Security_Login (Security Database login) items that can read/see the given item. If the read ID is 0 (open), then the function simply returns true. If nothing can see the item, then false is returned.
Parameters
$in_test_target This is a subclass of A_CO_DB_Table_Base (General Database Record).
Definition at line 561 of file co_cobra.class.php.
{
         $ret = false;
         if (isset($in_test_target) && ($in_test_target instanceof A_CO_DB_Table_Base)) {
             $id = intval($in_test_target->read_security_id);
             if (0 < $id) {
                 $ret = $this->_chameleon_instance->get_all_login_objects_with_access($id);
                 if (!isset($ret) || !is_array($ret) || !count($ret)) {
                     $ret = false;
                 }
             } elseif (0 == $id) {
                 $ret = true;
             }
         }
         return $ret;
     }
Member Data Documentation
$_chameleon_instance
CO_Cobra::$_chameleon_instance = NULL private
This is the CHAMELEON instance that is associated with this COBRA instance.
Definition at line 47 of file co_cobra.class.php.
$version
CO_Cobra::$version
The version indicator.
Definition at line 49 of file co_cobra.class.php.