BAOBAB: CO_Security_Login Class Reference
CO_Security_Login Class Reference
Public Member Functions
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_login_id=NULL, $in_ids=NULL)
load_from_db ($in_db_result)
get_crypted_password ($in_password_to_crypt=NULL)
is_login_valid ($in_login_id, $in_hashed_password=NULL, $in_raw_password=NULL, $in_dont_create_new_api_key=false)
i_am_a_god ()
is_god ()
is_manager ()
get_lang ()
set_lang ($in_lang_id=NULL)
get_user_object ()
set_password_from_cleartext ($in_cleartext_password)
is_api_key_valid ($in_api_key)
get_api_key ()
get_api_key_age_in_seconds ()
clear_api_key ()
user_can_write ()
delete_from_db ()
Public Member Functions inherited from CO_Security_Node
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_ids=NULL)
load_from_db ($in_db_result)
set_ids ($in_ids_array)
add_id ($in_id)
remove_id ($in_id)
ids ()
user_can_edit_ids ()
Public Member Functions inherited from A_CO_DB_Table_Base
__construct ($in_db_object=NULL, $in_db_result=NULL)
set_batch_mode ()
clear_batch_mode ()
load_from_db ($in_db_result)
id ()
lock ()
locked ()
danger_will_robinson_danger_clear_id ()
user_can_read ()
user_can_write ()
set_read_security_id ($in_new_id)
set_write_security_id ($in_new_id)
set_name ($in_new_value)
delete_from_db ()
update_db ()
reload_from_db ()
get_access_object ()
get_lang ()
set_lang ($in_lang_id=NULL)
Public Attributes
$login_id
Public Attributes inherited from A_CO_DB_Table_Base
$class_description
This is a description of the class (not the instance).
$instance_description
This is a description that describes the instance.
$last_access
This is a UNIX epoch date that describes the last modification. The default is UNIX Day Two (in case of UTC timezone issues).
$name
This is the "object_name" string field.
$read_security_id
This is a single integer, defining the security ID required to view the record. If it is 0, then it is "open.".
$write_security_id
This is a single integer, defining the required security token to modify the record. If it is 0, then any logged-in user can modify.
$context
This is a mixed associative array, containing fields for the object.
$error
If there is an error, it is contained here, in a LGV_Error instance.
Protected Member Functions
_set_up_api_key ($key_length)
_default_setup ()
_build_parameter_array ()
Protected Member Functions inherited from CO_Security_Node
_default_setup ()
_build_parameter_array ()
Protected Member Functions inherited from A_CO_DB_Table_Base
_default_setup ()
_build_parameter_array ()
_badger_serialize ($in_data)
_badger_unserialize ($in_data)
_write_to_db ()
_seppuku ()
Static Protected Member Functions
static _random_str ($length, $keyspace='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
Protected Attributes
$_api_key
This is an API key for REST.
Protected Attributes inherited from CO_Security_Node
$_ids
Protected Attributes inherited from A_CO_DB_Table_Base
$_db_object
This is the actual database object that "owns" this instance. It should not be exposed beyond this class or subclasses, thereof.
$_id
This is the within-table unique ID of this record.
$_batch_mode
If this is true, then the write_record call will not be made in update_db. It will be done when clear_batch_mode() is called, instead.
Private Attributes
$_override_access_class
This is a special "one-shot" semaphore telling the save to override the access class.
Detailed Description
This is the specializing class for the login ID record type.
Definition at line 38 of file co_security_login.class.php.
Constructor & Destructor Documentation
__construct()
CO_Security_Login::__construct ($in_db_object = NULL, $in_db_result = NULL, $in_login_id = NULL, $in_ids = NULL)
Constructor
Parameters
$in_db_object This is the database instance that "owns" this record.
$in_db_result This is a database-format associative array that is used to initialize this instance.
$in_login_id The login ID
$in_ids An array of integers, representing the permissions this ID has.
Definition at line 127 of file co_security_login.class.php.
References $lang.
{
         $this->login_id = $in_login_id;
         $this->_override_access_class = false;
         parent::__construct($in_db_object, $in_db_result, $in_ids);
         $this->class_description = 'This is a security class for individual logins.';
         if (!isset($this->context)) {
             $this->context = Array();
         }
         if (!isset($this->context['lang'])) {
             $this->context['lang'] = CO_Config::$lang;
         }
         if (isset($in_db_result['api_key'])) {
             $this->_api_key = $in_db_result['api_key'];
         }
         if (intval($this->id()) == intval(CO_Config::god_mode_id())) {
             // God Mode is always forced to use the config password.
             $this->context['hashed_password'] = bin2hex(openssl_random_pseudo_bytes(4));    // Just create a randomish junk password. It will never be used.
             $this->instance_description = 'GOD MODE: '.(isset($this->name) && $this->name ? "$this->name (".$this->login_id.")" : "Unnamed Login Node (".$this->login_id.")");
         } else {
             $this->instance_description = isset($this->name) && $this->name ? "$this->name (".$this->login_id.")" : "Unnamed Login Node (".$this->login_id.")";
         }
     }
Member Function Documentation
_build_parameter_array()
CO_Security_Login::_build_parameter_array () protected
This builds up the basic section of the instance database record. It should be overloaded, and the parent called before adding new fields.
This method overloads (and calls) the base class method.
Returns
an associative array, in database record form.
Definition at line 106 of file co_security_login.class.php.
References $_api_key, and $login_id.
{
         $ret = parent::_build_parameter_array();
         $ret['api_key'] = $this->_api_key;
         $ret['login_id'] = $this->login_id;
         if ($this->_override_access_class) {
             $ret['access_class'] = 'CO_Security_ID';
             $ret['object_name'] = NULL;
             $ret['ids'] = NULL;
             $this->context = NULL;
             $this->_override_access_class = false;
         }
         return $ret;
     }
_default_setup()
CO_Security_Login::_default_setup () protected
This is called to populate the object fields for this class with default values. These use the SQL table tags.
This should be subclassed, and the parent should be called before applying specific instance properties.
This method overloads (and calls) the base class method.
Returns
An associative array, simulating a database read.
Definition at line 89 of file co_security_login.class.php.
References $_api_key, and $login_id.
{
         $default_setup = parent::_default_setup();
         $default_setup['login_id'] = $this->login_id;
         $default_setup['object_name'] = $this->login_id;
         $default_setup['api_key'] = $this->_api_key;
         return $default_setup;
     }
_random_str()
static CO_Security_Login::_random_str ($length, $keyspace = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ') static protected
Generates a cryptographically secure string.
Returns
a randome string.
Definition at line 50 of file co_security_login.class.php.
     {
         $pieces = [];
         $max = mb_strlen($keyspace, '8bit') - 1;
         for ($i = 0; $i < $length; ++$i) {
             $pieces []= $keyspace[random_int(0, $max)];
         }
         return implode('', $pieces);
     }
_set_up_api_key()
CO_Security_Login::_set_up_api_key ($key_length) protected
This sets up a new API key after the login has been successfully verified.
Parameters
$key_length The length (in bytes) of the key.
Definition at line 64 of file co_security_login.class.php.
Referenced by is_login_valid().
{
         $temp_api_key = self::_random_str($key_length);
         $temp_api_key .= ' - '.strval(microtime(true)); // Add the current generation microtime, for key timeout.
         // If we are taking the IP address into consideration, then we store that, as well.
         if (isset(CO_Config::$api_key_includes_ip_address) && CO_Config::$api_key_includes_ip_address) {
             $temp_api_key .= ' - '.strtolower(strval($_SERVER['REMOTE_ADDR']));
         }
         $this->_api_key = strval($temp_api_key);
     }
clear_api_key()
CO_Security_Login::clear_api_key ()
Removes the API Key.
Returns
true, if the operation was successful (even if there was no previous key).
Definition at line 427 of file co_security_login.class.php.
References A_CO_DB_Table_Base\update_db().
{
         $this->_api_key = NULL;
         return $this->update_db();
     }
delete_from_db()
CO_Security_Login::delete_from_db ()
We override this, because logins never die. They just become security placeholders.
Returns
true, if the conversion was successful.
Definition at line 468 of file co_security_login.class.php.
References CO_Lang_Common\$login_error_code_attempt_to_delete_god, CO_Lang\$login_error_desc_attempt_to_delete_god, CO_Lang\$login_error_name_attempt_to_delete_god, A_CO_DB_Table_Base\_write_to_db(), get_user_object(), and user_can_write().
{
         if ($this->id() != CO_Config::god_mode_id()) {
             if ($this->user_can_write()) {
                 $user_object = $this->get_user_object();
                 if (isset($user_object) && ($user_object instanceof CO_User_Collection)) {
                     $user_object->set_login(NULL);
                 }
                 $this->read_security_id = 0;
                 $this->write_security_id = -1;
                 $this->api_key = NULL;
                 $this->context = NULL;
                 $this->name = NULL;
                 $this->login_id = NULL;
                 $this->_ids = Array();
                 $this->_override_access_class = true;
                 $ret = $this->_write_to_db();
                 return $ret;
             } else {
                 return false;
             }
         } else {
             $this->error = new LGV_Error(   CO_Lang_Common::$login_error_code_attempt_to_delete_god,
                                             CO_Lang::$login_error_name_attempt_to_delete_god,
                                             CO_Lang::$login_error_desc_attempt_to_delete_god
                                         );
         }
     }
get_api_key()
CO_Security_Login::get_api_key ()
Returns
a string, with the API key, if the key is still valid. NULL, otherwise.
Definition at line 363 of file co_security_login.class.php.
References CO_Lang_Common\$login_error_code_api_key_invalid, CO_Lang\$login_error_desc_api_key_invalid, CO_Lang\$login_error_name_api_key_invalid, and i_am_a_god().
Referenced by is_api_key_valid(), and is_login_valid().
{
         $ret = NULL;
         if (isset($this->_api_key) && $this->_api_key) {
             $api_expl = explode(' - ', trim($this->_api_key));
             $my_ip = NULL;
             // God Mode gets a different timeout.
             $timeout = floatval($this->i_am_a_god() ? CO_Config::$god_session_timeout_in_seconds : CO_Config::$session_timeout_in_seconds);
             // We first check to make sure that we are still within the time window. If not, then all bets are off.
             if (isset($api_expl[1]) && ((microtime(true) - floatval($api_expl[1])) <= $timeout)) {
                 if (isset(CO_Config::$api_key_includes_ip_address) && CO_Config::$api_key_includes_ip_address) {    // See if we are also checking the IP address.
                     $my_ip = strtolower(strval($_SERVER['REMOTE_ADDR']));
                     if (isset($api_expl[2])) {
                         if ($api_expl[2] == $my_ip) {
                             $ret = $api_expl[0];
                         } else {
                             $this->error = new LGV_Error(   CO_Lang_Common::$login_error_code_api_key_invalid,
                                                             CO_Lang::$login_error_name_api_key_invalid,
                                                             CO_Lang::$login_error_desc_api_key_invalid
                                                         );
                         }
                     } else {
                         $this->error = new LGV_Error(   CO_Lang_Common::$login_error_code_api_key_invalid,
                                                         CO_Lang::$login_error_name_api_key_invalid,
                                                         CO_Lang::$login_error_desc_api_key_invalid
                                                     );
                     }
                 } else {
                     $ret = $api_expl[0];
                 }
             } elseif ($api_expl[0]) {
                 $this->error = new LGV_Error(   CO_Lang_Common::$login_error_code_api_key_invalid,
                                                 CO_Lang::$login_error_name_api_key_invalid,
                                                 CO_Lang::$login_error_desc_api_key_invalid
                                             );
             }
         }
         return $ret;
     }
get_api_key_age_in_seconds()
CO_Security_Login::get_api_key_age_in_seconds ()
Returns
an integer, with the number of seconds since the API key was created. -1 if there is no API key. This will return a value, even if the API key is present, but expired.
Definition at line 410 of file co_security_login.class.php.
{
         $ret = -1;
         if (isset($this->_api_key) && $this->_api_key) {
             list($api_key, $api_time) = explode(' - ', trim($this->_api_key));
             $ret = ceil(microtime(true) - floatval($api_time));
         }
         return $ret;
     }
get_crypted_password()
CO_Security_Login::get_crypted_password ($in_password_to_crypt = NULL)
Returns
the crypted password, as a string.
Parameters
$in_password_to_crypt If this is not-NULL, then, instead of returning the instance's crypted PW, the given password is crypted and returned.
Definition at line 195 of file co_security_login.class.php.
Referenced by is_login_valid(), and set_password_from_cleartext().
{
         $ret = $this->context['hashed_password'];
         if ($in_password_to_crypt) {
             if (strlen($in_password_to_crypt) >= CO_Config::$min_pw_len) {
                 $ret = password_hash($in_password_to_crypt, PASSWORD_DEFAULT);
             } else {
                 $ret = false;
             }
         }
         return $ret;
     }
get_lang()
CO_Security_Login::get_lang ()
Returns
a string, with the language ID for this login.
Definition at line 285 of file co_security_login.class.php.
{
         return $this->context['lang'];
     }
get_user_object()
CO_Security_Login::get_user_object ()
Returns
The associated User object, if it exists. NULL, otherwise.
Definition at line 309 of file co_security_login.class.php.
References A_CO_DB_Table_Base\get_access_object().
Referenced by delete_from_db().
{
         $ret = NULL;
         $access_instance = $this->get_access_object();
         // If we have a user, we also clear the user from knowing about us.
         if ($access_instance && method_exists($access_instance, 'get_user_from_login')) {
             $ret = $access_instance->get_user_from_login($this->id());
         }
         return $ret;
     }
i_am_a_god()
CO_Security_Login::i_am_a_god ()
Returns
true, if this object represents the database "God" object.
Definition at line 261 of file co_security_login.class.php.
Referenced by get_api_key(), and user_can_write().
{
         return intval(CO_Config::god_mode_id()) == intval($this->id());
     }
is_api_key_valid()
CO_Security_Login::is_api_key_valid ($in_api_key)
This tests a given API key against the stored value. It also checks time elapsed, to ensure that we are still within the login window.
Returns
true, if the API key is valid, and we are still within the allotted timespan for the key.
Parameters
$in_api_key The API key that we're testing.
Definition at line 345 of file co_security_login.class.php.
References CO_Lang_Common\$login_error_code_api_key_mismatch, CO_Lang\$login_error_desc_api_key_mismatch, CO_Lang\$login_error_name_api_key_mismatch, and get_api_key().
{
         $ret = ($this->get_api_key() == $in_api_key);
         if ($ret && !$this->error) {
             $this->error = new LGV_Error(   CO_Lang_Common::$login_error_code_api_key_mismatch,
                                             CO_Lang::$login_error_name_api_key_mismatch,
                                             CO_Lang::$login_error_desc_api_key_mismatch
                                         );
         }
         return $ret;
     }
is_god()
CO_Security_Login::is_god ()
Returns
true, if we are the "God" login.
Definition at line 269 of file co_security_login.class.php.
References A_CO_DB_Table_Base\id().
Referenced by CO_Cobra\_create_new_login(), and is_manager().
{
         return $this->id() == CO_Config::god_mode_id();
     }
is_login_valid()
CO_Security_Login::is_login_valid ($in_login_id, $in_hashed_password = NULL, $in_raw_password = NULL, $in_dont_create_new_api_key = false)
Returns
true, if the presented credentials are good.
Parameters
$in_login_id The login ID
$in_hashed_password The password, crypt-hashed
$in_raw_password The password, cleartext.
$in_dont_create_new_api_key If true, then we don't create a new API key.
Definition at line 215 of file co_security_login.class.php.
References _set_up_api_key(), get_api_key(), and get_crypted_password().
{
         $ret = false;
         if (isset($this->login_id) && $this->login_id && ($this->login_id == $in_login_id)) {
             $api_key = $this->get_api_key();
             if ($this->id() == CO_Config::god_mode_id()) {
                 if ($in_hashed_password == $api_key) { // We have a special provision that allows the God hashed password to use the API key.
                     $ret = true;
                 } else {    // God mode uses the cleartext password in the config file.
                     if ($in_raw_password && !$in_dont_create_new_api_key && isset(CO_Config::$block_logins_for_valid_api_key) && CO_Config::$block_logins_for_valid_api_key && $api_key) {
                         return false;
                     } else {
                         $ret = ($in_raw_password == CO_Config::god_mode_password());
                     }
                 }
             } else {
                 // The server can be set up to prevent users from logging in while another login is still active.
                 if ($in_raw_password && !$in_dont_create_new_api_key && isset(CO_Config::$block_logins_for_valid_api_key) && CO_Config::$block_logins_for_valid_api_key && $api_key) {
                     return false;
                 } elseif (isset($this->context['hashed_password']) && $this->context['hashed_password']) {
                     // First, see if this is in the hashed password.
                     if ($in_hashed_password) {
                         $ret = hash_equals($this->get_crypted_password(), $in_hashed_password);
                     } else { // If not, see if it's the raw password.
                         $ret = password_verify($in_raw_password, $this->get_crypted_password());
                     }
                 }
             }
         }
         // Generate an API key. We can't save it yet, as we're probably not actually logged in.
         if ($ret && !$in_dont_create_new_api_key) {
             // God mode gets a longer key. It's not actually more secure, but we can use that to determine different treatment, later on.
             $this->_set_up_api_key($this->id() == CO_Config::god_mode_id() ? 40 : 32);
         }
         return $ret;
     }
is_manager()
CO_Security_Login::is_manager ()
Returns
false, as we are not a manager.
Definition at line 277 of file co_security_login.class.php.
References is_god().
{
         return $this->is_god();
     }
load_from_db()
CO_Security_Login::load_from_db ($in_db_result)
This function sets up this instance, according to the DB-formatted associative array passed in.
Returns
true, if the instance was able to set itself up to the provided array.
Definition at line 164 of file co_security_login.class.php.
References $lang.
{
         $ret = parent::load_from_db($in_db_result);
         if ($ret) {
             if (!isset($this->context)) {
                 $this->context = Array();
             }
             if (!isset($this->context['lang'])) {
                 $this->context['lang'] = CO_Config::$lang;
             }
             $this->class_description = 'This is a security class for individual logins.';
             if (isset($in_db_result['login_id'])) {
                 $this->login_id = $in_db_result['login_id'];
                 $this->instance_description = isset($this->name) && $this->name ? "$this->name (".$this->login_id.")" : "Unnamed Login Node (".$this->login_id.")";
             }
             if (isset($in_db_result['api_key'])) {
                 $this->_api_key = $in_db_result['api_key'];
             }
         }
         return $ret;
     }
set_lang()
CO_Security_Login::set_lang ($in_lang_id = NULL)
Returns
true, if the set was successful.
Parameters
$in_lang_id The lang ID. This is not used for the low-level error handlers (which use the server setting). It is used to determine higher-level strings.
Definition at line 293 of file co_security_login.class.php.
References A_CO_DB_Table_Base\update_db(), and user_can_write().
{
         $ret = false;
         if ($this->user_can_write()) {
             $this->context['lang'] = strtolower(trim(strval($in_lang_id)));
             $ret = $this->update_db();
         }
         return $ret;
     }
set_password_from_cleartext()
CO_Security_Login::set_password_from_cleartext ($in_cleartext_password)
This encrypts a cleartext password, and sets it into the record.
Returns
true, if the set was successful.
Parameters
$in_cleartext_password The cleartext password. It will not be saved. Instead, the hashed password will be saved.
Definition at line 327 of file co_security_login.class.php.
References get_crypted_password(), A_CO_DB_Table_Base\update_db(), and user_can_write().
{
         $ret = false;
         if ($this->user_can_write()) {
             $this->context['hashed_password'] = $this->get_crypted_password($in_cleartext_password);
             $ret = $this->update_db();
         }
         return $ret;
     }
user_can_write()
CO_Security_Login::user_can_write ()
We override this, because the God login can only be modified by itself. No one else.
Returns
true, if the current logged-in user has write permission on this record.
Definition at line 439 of file co_security_login.class.php.
References A_CO_DB_Table_Base\get_access_object(), and i_am_a_god().
Referenced by delete_from_db(), set_lang(), and set_password_from_cleartext().
{
         $ret = false;
         // Only God can edit God.
         if ($this->i_am_a_god() && !$this->get_access_object()->god_mode()) {
             return false;
         } else {
             $ids = $this->get_access_object()->get_security_ids();
             $my_write_item = intval($this->write_security_id);
             if ((0 == $my_write_item) || $this->get_access_object()->god_mode()) {
                 $ret = true;
             } else {
                 if (isset($ids) && is_array($ids) && count($ids)) {
                     $ret = in_array($my_write_item, $ids);
                 }
             }
         return $ret;
         }
     }
Member Data Documentation
$_api_key
CO_Security_Login::$_api_key protected
This is an API key for REST.
Definition at line 40 of file co_security_login.class.php.
Referenced by _build_parameter_array(), and _default_setup().
$_override_access_class
CO_Security_Login::$_override_access_class private
This is a special "one-shot" semaphore telling the save to override the access class.
Definition at line 39 of file co_security_login.class.php.
$login_id
CO_Security_Login::$login_id
Definition at line 42 of file co_security_login.class.php.
Referenced by _build_parameter_array(), and _default_setup().