BAOBAB: CO_Security_Node Class Reference
CO_Security_Node Class Reference
Public Member Functions
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_ids=NULL)
load_from_db ($in_db_result)
set_ids ($in_ids_array)
add_id ($in_id)
remove_id ($in_id)
ids ()
user_can_edit_ids ()
Public Member Functions inherited from A_CO_DB_Table_Base
__construct ($in_db_object=NULL, $in_db_result=NULL)
set_batch_mode ()
clear_batch_mode ()
load_from_db ($in_db_result)
id ()
lock ()
locked ()
danger_will_robinson_danger_clear_id ()
user_can_read ()
user_can_write ()
set_read_security_id ($in_new_id)
set_write_security_id ($in_new_id)
set_name ($in_new_value)
delete_from_db ()
update_db ()
reload_from_db ()
get_access_object ()
get_lang ()
set_lang ($in_lang_id=NULL)
Protected Member Functions
_default_setup ()
_build_parameter_array ()
Protected Member Functions inherited from A_CO_DB_Table_Base
_default_setup ()
_build_parameter_array ()
_badger_serialize ($in_data)
_badger_unserialize ($in_data)
_write_to_db ()
_seppuku ()
Protected Attributes
$_ids
Protected Attributes inherited from A_CO_DB_Table_Base
$_db_object
This is the actual database object that "owns" this instance. It should not be exposed beyond this class or subclasses, thereof.
$_id
This is the within-table unique ID of this record.
$_batch_mode
If this is true, then the write_record call will not be made in update_db. It will be done when clear_batch_mode() is called, instead.
Additional Inherited Members
Public Attributes inherited from A_CO_DB_Table_Base
$class_description
This is a description of the class (not the instance).
$instance_description
This is a description that describes the instance.
$last_access
This is a UNIX epoch date that describes the last modification. The default is UNIX Day Two (in case of UTC timezone issues).
$name
This is the "object_name" string field.
$read_security_id
This is a single integer, defining the security ID required to view the record. If it is 0, then it is "open.".
$write_security_id
This is a single integer, defining the required security token to modify the record. If it is 0, then any logged-in user can modify.
$context
This is a mixed associative array, containing fields for the object.
$error
If there is an error, it is contained here, in a LGV_Error instance.
Detailed Description
This is the base class for records in the security database.
Definition at line 38 of file co_security_node.class.php.
Constructor & Destructor Documentation
__construct()
CO_Security_Node::__construct ($in_db_object = NULL, $in_db_result = NULL, $in_ids = NULL)
Initializer
Parameters
$in_db_object This is the database instance that "owns" this record.
$in_db_result This is a database-format associative array that is used to initialize this instance.
$in_ids This is a preset array of integers, containing security IDs for the row.
Definition at line 92 of file co_security_node.class.php.
{
         parent::__construct($in_db_object, $in_db_result);
         $this->class_description = 'The basic class for all security nodes. This should be specialized.';
         // If explicit IDs are passed in, then that overrides the DB.
         if (isset($in_ids) && is_array($in_ids)) {
             $in_db_result['ids'] = implode(',', $in_ids);
         }
         if ($this->_db_object) {
             $this->_ids = Array($this->id());
             if (isset($in_db_result['ids'])) {
                 $temp = $in_db_result['ids'];
                 if (isset ($temp) && $temp) {
                     $tempAr = explode(',', $temp);
                     if (is_array($tempAr) && count($tempAr)) {
                         $tempAr = array_map('intval', $tempAr);
                         sort($tempAr);
                         $tempAr = array_unique(array_merge($this->_ids, $tempAr));
                         if (isset($tempAr) && is_array($tempAr) && count($tempAr)) {
                             $this->_ids = $tempAr;
                         }
                     }
                 }
             }
         }
         $this->instance_description = isset($this->name) && $this->name ? "$this->name ($this->_id)" : "Unnamed Security Node ($this->_id)";
     }
Member Function Documentation
_build_parameter_array()
CO_Security_Node::_build_parameter_array () protected
This builds up the basic section of the instance database record. It should be overloaded, and the parent called before adding new fields.
This method overloads (and calls) the base class method.
Returns
an associative array, in database record form.
Definition at line 66 of file co_security_node.class.php.
{
         $ret = parent::_build_parameter_array();
         $ids_as_string_array = Array();
         $ids_as_int = array_map('intval', $this->_ids);
         sort($ids_as_int);
         foreach ($this->_ids as $id) {
             if ($id != $this->id()) {
                 array_push($ids_as_string_array, strval($id));
             }
         }
         $id_list_string = trim(implode(',', $ids_as_string_array));
         $ret['ids'] = $id_list_string ? $id_list_string : NULL;
         $ret['login_id'] = NULL;
         return $ret;
     }
_default_setup()
CO_Security_Node::_default_setup () protected
This is called to populate the object fields for this class with default values. These use the SQL table tags.
This should be subclassed, and the parent should be called before applying specific instance properties.
This method overloads (and calls) the base class method.
Returns
An associative array, simulating a database read.
Definition at line 52 of file co_security_node.class.php.
References $_ids.
{
         $default_setup = parent::_default_setup();
         $default_setup['ids'] = (NULL != $this->_ids) ? $this->_ids : '';
         return $default_setup;
     }
add_id()
CO_Security_Node::add_id ($in_id)
This is a setter, allowing you to add an ID.
Returns
true, if successful.
Parameters
$in_id A single integer. The new ID to add.
Definition at line 239 of file co_security_node.class.php.
References CO_Lang_Common\$db_error_code_user_not_authorized, CO_Lang\$db_error_desc_user_not_authorized, CO_Lang\$db_error_name_user_not_authorized, A_CO_DB_Table_Base\get_access_object(), A_CO_DB_Table_Base\update_db(), and user_can_edit_ids().
{
         $ret = false;
         if ($this->user_can_edit_ids() || ($this->_added_new_id == $in_id)) {
             $id_pool = $this->get_access_object()->get_security_ids();
             if ($this->get_access_object()->god_mode() || (isset($id_pool) && is_array($id_pool) && count($id_pool))) {
                 // We can add an ID to the user, as long as it is one we own. We don't have to have full access to all user IDs.
                 if (($this->get_access_object()->god_mode() || (in_array($in_id, $id_pool)) || ($this->_added_new_id == $in_id)) && ($in_id != $this->id())) {
                     if (!isset($this->_ids) || !is_array($this->_ids) || !count($this->_ids)) {
                         $this->_ids = Array(intval($in_id));
                     } else {
                         $this->_ids[] = $in_id;
                         $this->_ids = array_unique($this->_ids);
                     }
                     $ret = $this->update_db();
                 } else {
                     if ($in_id != $this->id()) {
                         $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                                         CO_Lang::$db_error_name_user_not_authorized,
                                                         CO_Lang::$db_error_desc_user_not_authorized,
                                                         __LINE__,
                                                         __FILE__,
                                                         __METHOD__
                                                     );
                     } else {    // If we tried to add our own ID, then we don't add it, but it's not an error.
                         $ret = true;
                     }
                 }
             }
         } else {
             $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                             CO_Lang::$db_error_name_user_not_authorized,
                                             CO_Lang::$db_error_desc_user_not_authorized,
                                             __LINE__,
                                             __FILE__,
                                             __METHOD__
                                         );
         }
         return $ret;
     }
ids()
CO_Security_Node::ids ()
This does a security vetting. If logged in as God, then all IDs are returned. Otherwise, only IDs that our login can see are returned, whether or not they are in the object.
Returns
The current IDs.
Definition at line 342 of file co_security_node.class.php.
References $_ids, and A_CO_DB_Table_Base\get_access_object().
{
         if ($this->get_access_object()->god_mode()) {
             return $this->_ids;
         } else {
             $my_ids = $this->get_access_object()->get_security_ids();
             $ret = Array();
             foreach ($this->_ids as $id) {
                 if (in_array($id, $my_ids)) {
                     array_push($ret, $id);
                 }
             }
             return $ret;
         }
     }
load_from_db()
CO_Security_Node::load_from_db ($in_db_result)
This function sets up this instance, according to the DB-formatted associative array passed in.
This should be subclassed, and the parent should be called before applying specific instance properties.
Returns
true, if the instance was able to set itself up to the provided array.
Parameters
$in_db_result This is an associative array, formatted as a database row response.
Definition at line 134 of file co_security_node.class.php.
{
         $ret = parent::load_from_db($in_db_result);
         if ($ret && isset($in_db_result['ids']) && $in_db_result['ids']) {
             if ($this->_db_object) {
                 $this->_ids = Array($this->id());
                 if (isset($in_db_result['ids'])) {
                     $temp = $in_db_result['ids'];
                     if (isset ($temp) && $temp) {
                         $tempAr = explode(',', $temp);
                         if (is_array($tempAr) && count($tempAr)) {
                             $tempAr = array_map('intval', $tempAr);
                             sort($tempAr);
                             $tempAr = array_unique(array_merge($this->_ids, $tempAr));
                             if (isset($tempAr) && is_array($tempAr) && count($tempAr)) {
                                 $this->_ids = $tempAr;
                             }
                         }
                     }
                 }
             }
         }
         return $ret;
     }
remove_id()
CO_Security_Node::remove_id ($in_id)
This allows you to remove a single ID. We can remove one of our IDs from a user that may have other IDs.
Returns
true, if successful.
Parameters
$in_id A single integer. The ID to remove.
Definition at line 291 of file co_security_node.class.php.
References CO_Lang_Common\$db_error_code_user_not_authorized, CO_Lang\$db_error_desc_user_not_authorized, CO_Lang\$db_error_name_user_not_authorized, A_CO_DB_Table_Base\get_access_object(), set_ids(), and user_can_edit_ids().
{
         $ret = false;
         if ($this->user_can_edit_ids()) {
             $id_pool = $this->get_access_object()->get_security_ids();
             if ($this->get_access_object()->god_mode() || (isset($id_pool) && is_array($id_pool) && count($id_pool) && in_array($in_id, $id_pool))) {
                 if (isset($this->_ids) && is_array($this->_ids) && count($this->_ids) && $this->user_can_edit_ids()) {
                     $new_array = Array();
                     foreach($this->_ids as $id) {
                         if ($id != $in_id) {
                             array_push($new_array, $id);
                         } else {
                             $ret = true;
                         }
                         if ($ret) {
                             $ret = $this->set_ids($new_array);
                         }
                     }
                 }
             } else {
                 $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                                 CO_Lang::$db_error_name_user_not_authorized,
                                                 CO_Lang::$db_error_desc_user_not_authorized,
                                                 __LINE__,
                                                 __FILE__,
                                                 __METHOD__
                                             );
             }
         } else {
             $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                             CO_Lang::$db_error_name_user_not_authorized,
                                             CO_Lang::$db_error_desc_user_not_authorized,
                                             __LINE__,
                                             __FILE__,
                                             __METHOD__
                                         );
         }
         return $ret;
     }
set_ids()
CO_Security_Node::set_ids ($in_ids_array)
This is a setter for the ID array. It can delete the array by sending in NULL, or an empty array. No user can set IDs for which they do not have access. Since this is a "whole hog" operation, we need to be able to access every single ID in the current object before we can replace or delete them.
Returns
true, if successful.
Parameters
$in_ids_array This is a preset array of integers, containing security IDs for the row. NULL/Empty to delete all IDs.
Definition at line 170 of file co_security_node.class.php.
References CO_Lang_Common\$db_error_code_user_not_authorized, CO_Lang\$db_error_desc_user_not_authorized, CO_Lang\$db_error_name_user_not_authorized, A_CO_DB_Table_Base\get_access_object(), A_CO_DB_Table_Base\update_db(), and user_can_edit_ids().
Referenced by remove_id().
{
         $ret = false;
         if ($this->user_can_edit_ids()) {
             $id_pool = $this->get_access_object()->get_security_ids();
             if ($this->get_access_object()->god_mode() || (isset($id_pool) && is_array($id_pool) && count($id_pool))) {
                 // First thing we do, is ensure that EVERY SINGLE ID in the current user are ones we have in our own set.
                 // An empty set is fine.
                 foreach($this->_ids as $id) {
                     if (!$this->get_access_object()->god_mode() && (isset($id) && (0 < $id) && !in_array($id, $id_pool))) {
                         // Even one failure scrags the operation.
                         $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                                         CO_Lang::$db_error_name_user_not_authorized,
                                                         CO_Lang::$db_error_desc_user_not_authorized,
                                                         __LINE__,
                                                         __FILE__,
                                                         __METHOD__
                                                     );
                         return false;
                     }
                 }
                 // Next, if there is an existing array, we check our input, and add only the IDs we own.
                 if ($this->get_access_object()->god_mode() || (isset($in_ids_array) && is_array($in_ids_array) && count($in_ids_array))) {
                     $temp_ids = array_map('intval', $in_ids_array);
                     $new_ids = Array();
                     foreach($temp_ids as $in_id) {
                         if (($in_id != $this->id()) && ($this->get_access_object()->god_mode() || in_array($in_id, $id_pool))) {
                             $new_ids[] = $in_id;
                         }
                     }
                     if (count($new_ids)) {
                         $this->_ids = $new_ids;
                     }
                 // Otherwise, we are clearing the array.
                 } else {
                     $this->_ids = Array();
                 }
                 $ret = $this->update_db();
             } else {
                 $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                                 CO_Lang::$db_error_name_user_not_authorized,
                                                 CO_Lang::$db_error_desc_user_not_authorized,
                                                 __LINE__,
                                                 __FILE__,
                                                 __METHOD__
                                             );
             }
         } else {
              $this->error = new LGV_Error(   CO_Lang_Common::$db_error_code_user_not_authorized,
                                             CO_Lang::$db_error_name_user_not_authorized,
                                             CO_Lang::$db_error_desc_user_not_authorized,
                                             __LINE__,
                                             __FILE__,
                                             __METHOD__
                                         );
         }
         return $ret;
     }
user_can_edit_ids()
CO_Security_Node::user_can_edit_ids ()
We check to see if we can edit the IDs for this record. We cannot edit our own IDs, and have to own all of the IDs in the object in order to be able to change them. Of course, God can do whatever God wants...
Returns
true, if the current logged-in user can edit IDs for this login.
Definition at line 365 of file co_security_node.class.php.
References A_CO_DB_Table_Base\$_id, and A_CO_DB_Table_Base\get_access_object().
Referenced by add_id(), remove_id(), and set_ids().
{
         $ret = ($this->get_access_object()->get_login_id() != $this->_id) && ($this->get_access_object()->god_mode() || $this->_db_object->i_have_all_ids($this->_id));
         return $ret;
     }
Member Data Documentation
$_ids
CO_Security_Node::$_ids protected
Definition at line 39 of file co_security_node.class.php.
Referenced by _default_setup(), and ids().