BAOBAB: CO_Security_DB Class Reference
CO_Security_DB Class Reference
Public Member Functions
__construct ($in_pdo_object, $in_access_object=NULL)
get_security_ids_for_id ($in_id)
i_have_all_ids ($in_id)
get_all_tokens ()
get_initial_record_by_login_id ($in_login_id)
get_credentials_by_api_key ($in_api_key)
get_initial_record_by_id ($in_id)
get_single_record_by_login_id ($in_login_id, $and_write=false)
get_multiple_records_by_login_id ($in_login_id_array, $and_write=false)
get_all_login_objects ($and_write=false)
get_all_login_objects_with_access ($in_security_token, $and_write=false)
count_all_login_objects_with_access ($in_security_token)
get_all_user_objects_with_access ($in_security_token)
Public Member Functions inherited from A_CO_DB
_instantiate_record ($in_db_result)
execute_query ($in_sql, $in_parameters=NULL, $exec_only=false)
get_db_backup ()
get_access_class_by_id ($in_id)
can_i_see_this_record ($in_id)
get_single_raw_row_by_id ($in_id, $and_write=false)
get_single_record_by_id ($in_id, $and_write=false)
get_multiple_records_by_id ($in_id_array, $and_write=false)
get_all_readable_records ($open_only=false, $in_this_id=NULL)
get_all_writeable_records ($in_this_id=NULL)
lock_record ($in_record_id)
write_record ($params_associative_array)
delete_record ($id)
Additional Inherited Members
Public Attributes inherited from A_CO_DB
$access_object
$class_description
$error
$table_name
Protected Member Functions inherited from A_CO_DB
_create_read_security_predicate ()
_create_write_security_predicate ()
_create_security_predicate ($write=false)
Protected Attributes inherited from A_CO_DB
$_pdo_object
$_existing_record_objects
Detailed Description
This is the base class for the security database. It assumes that it will have logins and Security ID table rows.
Definition at line 39 of file co_security_db.class.php.
Constructor & Destructor Documentation
__construct()
CO_Security_DB::__construct ($in_pdo_object, $in_access_object = NULL)
This is the initializer.
Parameters
$in_pdo_object The PDO instance for this database.
$in_access_object The access object (if any) for this login.
Reimplemented from A_CO_DB.
Definition at line 45 of file co_security_db.class.php.
{
         parent::__construct($in_pdo_object, $in_access_object);
         $this->table_name = 'co_security_nodes';    // This is the name of the SQL table we will query.
         $this->class_description = 'The security database class.';  // A simple explanation of what this class is.
     }
Member Function Documentation
count_all_login_objects_with_access()
CO_Security_DB::count_all_login_objects_with_access ($in_security_token)
You give a security ID, and you will get a count of all login objects that have that token in their list (or are of that ID).
This is not restricted, and will count logins that we don't otherwise know about.
It does not count the "God" admin, which always has access.
Returns
an integer, with the total count of logins with access to the ID. -1, if we are not allowed to see the token.
Parameters
$in_security_token An integer, with the requested security token.
Definition at line 445 of file co_security_db.class.php.
{
         $ret = -1;
         $in_security_token = intval($in_security_token);
         // No security predicate, but we do have to "own" the given token.
         if (($this->access_object->god_mode() && $in_security_token) || in_array($in_security_token, $this->access_object->get_security_ids())) {
             $sql = 'SELECT * FROM '.$this->table_name.' WHERE (login_id IS NOT NULL) AND (login_id<>\'\') AND (id<>'.intval(CO_Config::god_mode_id()).')';
             $temp = $this->execute_query($sql, Array());    // We just get everything.
             if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
                 $ret = 0;
                 foreach ($temp as $result) {
                     $id = intval($result['id']);
                     $ids = explode(',', $result['ids']);
                     if (isset($ids) && is_array($ids) && count($ids)) {
                         $ids = array_map('trim', $ids);
                         $ids = array_map('intval', $ids);
                         array_push($ids, $id);
                         $ids = array_unique($ids);
                         foreach ($ids as $single_id) {
                             if ($single_id == $in_security_token) {
                                 $ret += 1;
                                 break;
                             }
                         }
                     }
                 }
             }
         }
         return $ret;
     }
References A_CO_DB\execute_query().
get_all_login_objects()
CO_Security_DB::get_all_login_objects ($and_write = false)
This is a security-vetted search for all login objects (visible to the current user).
Returns
an array of instances.
Parameters
$and_write If true, then we only want ones we have write access to.
Definition at line 320 of file co_security_db.class.php.
{
         $ret = Array();
         // Can only look for tokens we can see.
         $predicate = $this->_create_security_predicate($and_write);
         if ($predicate) {   // If we got a predicate, then we AND it with the rest of the statement.
             $predicate .= ' AND ';
         }
         $sql = 'SELECT * FROM '.$this->table_name.' WHERE '.$predicate. '(login_id IS NOT NULL) AND (login_id<>\'\')';
         $temp = $this->execute_query($sql, Array());    // We just get everything.
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             foreach ($temp as $result) {
                 $result = $this->_instantiate_record($result);
                 if ($result) {
                     array_push($ret, $result);
                 }
             }
         }
         // At this point, only managers (or the login object, itself) can see logins. God, too, of course.
         $my_id = $this->access_object->get_login_id();
         $my_login_instance_is_manager = $this->access_object->god_mode() || ($this->access_object->get_login_item() instanceof CO_Login_Manager);
         $temp_ret = Array();
         foreach ($ret as $instance) {
             if (($instance->id() == $my_id) || $my_login_instance_is_manager) {
                 array_push($temp_ret, $instance);
             }
         }
         return $temp_ret;
     }
References A_CO_DB\_create_security_predicate(), A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
get_all_login_objects_with_access()
CO_Security_DB::get_all_login_objects_with_access ($in_security_token, $and_write = false)
You give a security ID, and you will get all login objects that have that token in their list (or are of that ID).
This is restricted to use security vetting, so only logins visible to the current login.
Returns
an array of instances.
Parameters
$in_security_token An integer, with the requested security token.
$and_write If true, then we only want ones we have write access to.
Definition at line 365 of file co_security_db.class.php.
{
         $ret = Array();
         $in_security_token = intval($in_security_token);
         $access_ids = $this->access_object->get_security_ids();
         // Can only look for tokens we can see.
         if (($this->access_object->god_mode() && $in_security_token) || in_array($in_security_token, $access_ids)) {
             $predicate = $this->_create_security_predicate($and_write);
             if ($predicate) {   // If we got a predicate, then we AND it with the rest of the statement.
                 $predicate .= ' AND ';
             }
             $sql = 'SELECT * FROM '.$this->table_name.' WHERE '.$predicate.'(login_id IS NOT NULL) AND (login_id<>\'\')';
             $temp = $this->execute_query($sql, Array());    // We just get everything.
             if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
                 $ret = Array();
                 foreach ($temp as $result) {
                     $id = intval($result['id']);
                     $id_array = Array($id);
                     $ids = explode(',', $result['ids']);
                     if (isset($ids) && is_array($ids) && count($ids)) {
                         $ids = array_map('trim', $ids);
                         $ids = array_map('intval', $ids);
                         foreach ($ids as $single_id) {
                             array_push($id_array, $single_id);
                         }
                     }
                     $found = (2 > $in_security_token);
                     if (!$found) {
                         foreach ($id_array as $test_id) {
                             if ($test_id == $in_security_token) {
                                 $found = true;
                                 break;
                             }
                         }
                     }
                     if ($found) {
                         $result = $this->_instantiate_record($result);
                         if ($result) {
                             array_push($ret, $result);
                         }
                     }
                 }
             }
         }
         // At this point, only managers (or the login object, itself) can see logins. God, too, of course.
         $my_id = $this->access_object->get_login_id();
         $my_login_instance_is_manager = $this->access_object->god_mode() || ($this->access_object->get_login_item() instanceof CO_Login_Manager);
         $temp_ret = Array();
         foreach ($ret as $instance) {
             if (($instance->id() == $my_id) || $my_login_instance_is_manager) {
                 array_push($temp_ret, $instance);
             }
         }
         return $temp_ret;
     }
References A_CO_DB\_create_security_predicate(), A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
get_all_tokens()
CO_Security_DB::get_all_tokens ()
This returns the entire list of IDs in the Security Database.
It should only ever be called by the "God" admin.
Returns
an array of integers, each, a security ID for the given login, and the first element is always the login ID itself.
Definition at line 133 of file co_security_db.class.php.
{
         $ret = NULL;
         if ($this->access_object->god_mode()) {
             $sql = 'SELECT id FROM '.$this->table_name.' WHERE true ORDER BY id';
             $temp = $this->execute_query($sql, Array());
             if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
                 $ret = [];
                 foreach($temp as $row) {
                     $ret[] = intval($row['id']);
                 }
             }
         }
         return $ret;
     }
References A_CO_DB\execute_query().
get_all_user_objects_with_access()
CO_Security_DB::get_all_user_objects_with_access ($in_security_token)
You give a security ID, and you will get an array, with the user objects, associated with login objects that have that token in their list (or are of that ID).
This is security restricted, and will not return users that we don't otherwise know about.
Returns
an array, with the user objects, associated with login objects that have that token in their list (or are of that ID).
Parameters
$in_security_token An integer, with the requested security token.
Definition at line 488 of file co_security_db.class.php.
{
         $ret = array();
         $in_security_token = intval($in_security_token);
         $access_instance = $this->access_object;
         // No security predicate, but we do have to "own" the given token.
         if (($access_instance->god_mode() && $in_security_token) || in_array($in_security_token, $access_instance->get_security_ids())) {
             $sql = 'SELECT * FROM '.$this->table_name.' WHERE (login_id IS NOT NULL) AND (login_id<>\'\') AND (id<>'.intval(CO_Config::god_mode_id()).')';
             $temp = $this->execute_query($sql, Array());    // We just get everything.
             if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
                 foreach ($temp as $result) {
                     $id = intval($result['id']);
                     $ids = explode(',', $result['ids']);
                     if (isset($ids) && is_array($ids) && count($ids)) {
                         $ids = array_map('trim', $ids);
                         $ids = array_map('intval', $ids);
                         array_push($ids, $id);
                         $ids = array_unique($ids);
                         foreach ($ids as $single_id) {
                             if ($single_id == $in_security_token) {
                                 array_push($ret, $id);
                                 break;
                             }
                         }
                     }
                 }
             }
         }
         $returnVar = array();
         foreach ($ret as $id) {
             $temp2 = $access_instance->get_user_from_login($id);
             if (isset($temp2) && $temp2) {
                 array_push($returnVar, $temp2);
             }
         }
         return $returnVar;
     }
References A_CO_DB\$access_object, and A_CO_DB\execute_query().
get_credentials_by_api_key()
CO_Security_DB::get_credentials_by_api_key ($in_api_key)
This is a special "raw" function for getting login credentials from an API key.
Returns
an associative array, with the login ID and hashed password that correspond to the API key.
Parameters
$in_api_key The API Key of the element.
Definition at line 183 of file co_security_db.class.php.
{
         $ret = NULL;
         $sql = 'SELECT * FROM '.$this->table_name.' WHERE api_key LIKE ?';
         $params = Array(trim($in_api_key).' - %');
         $temp = $this->execute_query($sql, $params);
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             $result = $this->_instantiate_record($temp[0]);
             if (isset($result) && ($result instanceof CO_Security_Login) && $result && $result->is_api_key_valid($in_api_key)) {
                 $ret = Array('login_id' => $result->login_id, 'hashed_password' => $result->get_crypted_password());
                 if ($result->id() == CO_Config::god_mode_id()) {
                     $ret['hashed_password'] = $in_api_key;
                 }
             } elseif (isset($result) && ($result instanceof CO_Security_Login)) {
                 $this->error = $result->error;
             }
         }
         return $ret;
     }
References A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
get_initial_record_by_id()
CO_Security_DB::get_initial_record_by_id ($in_id)
This is a very "raw" function that should ONLY be called from a special check from the access class.
It has no security screening, as this is just for checking.
Returns
a newly-instantiated record.
Parameters
$in_id The ID of the element.
Definition at line 214 of file co_security_db.class.php.
{
         $ret = NULL;
         $sql = 'SELECT * FROM '.$this->table_name.' WHERE id='.intval($in_id);
         $temp = $this->execute_query($sql, Array());
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             $result = $this->_instantiate_record($temp[0]);
             if ($result) {
                 $ret = $result;
             }
         }
         return $ret;
     }
References A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
get_initial_record_by_login_id()
CO_Security_DB::get_initial_record_by_login_id ($in_login_id)
This is a very "raw" function that should ONLY be called from the access instance __construct() method (or a special check from the access class).
It is designed to fetch the current login object from its string login ID, so we can extract the id.
It has no security screening, as it needs to be called before the security screens can be put into place.
Returns
a newly-instantiated record.
Parameters
$in_login_id The login ID of the element.
Definition at line 159 of file co_security_db.class.php.
{
         $ret = NULL;
         $sql = 'SELECT * FROM '.$this->table_name.' WHERE login_id=?';
         $params = Array(trim($in_login_id));
         $temp = $this->execute_query($sql, $params);
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             $result = $this->_instantiate_record($temp[0]);
             if ($result) {
                 $ret = $result;
             }
         }
         return $ret;
     }
References A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
get_multiple_records_by_login_id()
CO_Security_DB::get_multiple_records_by_login_id ($in_login_id_array, $and_write = false)
This is a security-screened multiple login fetcher.
Returns
an array of newly-instantiated objects.
Definition at line 257 of file co_security_db.class.php.
{
         $ret = NULL;
         $predicate = $this->_create_security_predicate($and_write);
         if ($predicate) {   // If we got a predicate, then we AND it with the rest of the statement.
             $predicate .= ' AND ';
         }
         $sql = 'SELECT * FROM '.$this->table_name.' WHERE '.$predicate. '(';
         $params = Array();
         foreach ($in_login_id_array as $id) {
             if (trim($id)) {
                 if (0 < count($params)) {
                     $sql .= ') OR (';
                 }
                 $sql.= 'login_id=?';
                 array_push($params, $id);
             }
         }
         $sql  .= ')';
         if (0 < count($params)) {
             $temp = $this->execute_query($sql, $params);
             if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
                 $ret = Array();
                 foreach ($temp as $result) {
                     $result = $this->_instantiate_record($result);
                     if ($result) {
                         array_push($ret, $result);
                     }
                 }
                 usort($ret, function($a, $b){return ($a->id() > $b->id());});
             }
         }
         // At this point, only managers (or the login object, itself) can see logins. God, too, of course.
         $my_id = $this->access_object->get_login_id();
         $my_login_instance_is_manager = $this->access_object->god_mode() || ($this->access_object->get_login_item() instanceof CO_Login_Manager);
         $temp_ret = Array();
         if (isset($ret) && is_array($ret) && count($ret)) {
             foreach ($ret as $instance) {
                 if (($instance->id() == $my_id) || $my_login_instance_is_manager) {
                     array_push($temp_ret, $instance);
                 }
             }
         }
         return $temp_ret;
     }
References A_CO_DB\_create_security_predicate(), A_CO_DB\_instantiate_record(), and A_CO_DB\execute_query().
Referenced by get_single_record_by_login_id().
get_security_ids_for_id()
CO_Security_DB::get_security_ids_for_id ($in_id)
This returns just the security IDs (including the item ID, itself) for the given ID.
This should only be called from the ID fetcher in the access class, as it does not do a security predicate.
Returns
an array of integers, each, a security ID for the given login, and the first element is always the login ID itself.
Parameters
$in_id The integer ID of the row.
Definition at line 63 of file co_security_db.class.php.
{
         $ret = NULL;
         $sql = 'SELECT ids FROM '.$this->table_name.' WHERE (login_id IS NOT NULL) AND (id='.intval($in_id).')';
         $temp = $this->execute_query($sql, Array());
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             $ret = explode(',', $temp[0]['ids']);
             if (isset($ret) && is_array($ret) && count($ret)) {
                 array_unshift($ret, $in_id);
                 $ret = array_unique(array_map('intval', $ret));
                 $ret_temp = Array();
                 foreach ( $ret as $i) {
                     if (0 < $i) {
                         array_push($ret_temp, $i);
                     }
                 }
                 $ret = $ret_temp;
             }
         } else {
             $ret = Array($in_id);
         }
         return $ret;
     }
References A_CO_DB\execute_query().
get_single_record_by_login_id()
CO_Security_DB::get_single_record_by_login_id ($in_login_id, $and_write = false)
This is a security-screened method to fetch a single instance of a record object, based on its ID.
Returns
a single, newly-instantiated object.
Parameters
$in_login_id The login ID of the requested login object.
$and_write If this is true, then we need the item to be modifiable.
Definition at line 237 of file co_security_db.class.php.
{
         $ret = NULL;
         $temp = $this->get_multiple_records_by_login_id(Array($in_login_id), $and_write);
         if (isset($temp) && $temp && is_array($temp) && count($temp) ) {
             $ret = $temp[0];
         }
         return $ret;
     }
References get_multiple_records_by_login_id().
i_have_all_ids()
CO_Security_DB::i_have_all_ids ($in_id)
This method will check a given security record (indicated by its ID), and make sure that we have COMPLETE access to it. This means that we check ALL the ids, as well as the record's write (not read) token.
This is not "security-vetted," in order to make sure that we are looking at the complete record.
Returns
true, if we completely match. False, otherwise.
Parameters
$in_id This is the ID of the record to check.
Definition at line 99 of file co_security_db.class.php.
{
         $ret = false;
         if (intval($in_id)) {
             $sql = 'SELECT write_security_id, ids FROM '.$this->table_name.' WHERE id='.intval($in_id);
             $result = $this->execute_query($sql, Array());
             if (isset($result) && is_array($result) && (1 == count($result))) {
                 $access_ids = $this->access_object->get_security_ids();
                 $write_security_id = intval($result[0]['write_security_id']);
                 $ids = (isset($result[0]['ids']) && trim($result[0]['ids'])) ? array_map('intval', explode(',', trim($result[0]['ids']))) : [];
                 $ids[] = $write_security_id;
                 sort($ids);
                 sort($access_ids);
                 $diff = array_diff($ids, $access_ids);
                 if (is_array($diff) && !count($diff)) { // We only go true if there are no outliers. We have to have ALL of them.
                     $ret = true;
                 }
             }
         }
         return $ret;
     }
References A_CO_DB\execute_query().