BAOBAB: CO_Main_DB_Record Class Reference
CO_Main_DB_Record Class Reference
Public Member Functions
__construct ($in_db_object=NULL, $in_db_result=NULL, $in_owner_id=NULL, $in_tags_array=NULL)
load_from_db ($in_db_result)
set_owner_id ($in_new_id)
set_tags ($in_tags_array)
set_tag ($in_tag_index, $in_tag_value)
get_payload ()
set_payload ($in_payload)
owner_id ()
tags ()
Public Member Functions inherited from A_CO_DB_Table_Base
__construct ($in_db_object=NULL, $in_db_result=NULL)
set_batch_mode ()
clear_batch_mode ()
id ()
lock ()
locked ()
danger_will_robinson_danger_clear_id ()
user_can_read ()
user_can_write ()
set_read_security_id ($in_new_id)
set_write_security_id ($in_new_id)
set_name ($in_new_value)
delete_from_db ()
update_db ()
reload_from_db ()
get_access_object ()
get_lang ()
set_lang ($in_lang_id=NULL)
Static Public Attributes
static $s_table_name = 'co_data_nodes'
Protected Member Functions
_default_setup ()
_build_parameter_array ()
Protected Member Functions inherited from A_CO_DB_Table_Base
_badger_serialize ($in_data)
_badger_unserialize ($in_data)
_write_to_db ()
_seppuku ()
Protected Attributes
$_owner_id
$_tags
Protected Attributes inherited from A_CO_DB_Table_Base
$_db_object
This is the actual database object that "owns" this instance. It should not be exposed beyond this class or subclasses, thereof.
$_id
This is the within-table unique ID of this record.
$_batch_mode
If this is true, then the write_record call will not be made in update_db. It will be done when clear_batch_mode() is called, instead.
Private Attributes
$_raw_payload
Additional Inherited Members
Public Attributes inherited from A_CO_DB_Table_Base
$class_description
This is a description of the class (not the instance).
$instance_description
This is a description that describes the instance.
$last_access
This is a UNIX epoch date that describes the last modification. The default is UNIX Day Two (in case of UTC timezone issues).
$name
This is the "object_name" string field.
$read_security_id
This is a single integer, defining the security ID required to view the record. If it is 0, then it is "open.".
$write_security_id
This is a single integer, defining the required security token to modify the record. If it is 0, then any logged-in user can modify.
$context
This is a mixed associative array, containing fields for the object.
$error
If there is an error, it is contained here, in a LGV_Error instance.
Detailed Description
This is the main instance base class for records in the main "data" database.
Definition at line 38 of file co_main_db_record.class.php.
Constructor & Destructor Documentation
__construct()
CO_Main_DB_Record::__construct ($in_db_object = NULL, $in_db_result = NULL, $in_owner_id = NULL, $in_tags_array = NULL)
The initializer.
Parameters
$in_db_object The database object for this instance.
$in_db_result The database row for this instance (associative array, with database keys).
$in_owner_id The ID of the object (in the database) that "owns" this instance.
$in_tags_array An array of strings, up to ten elements long, for the tags.
Reimplemented in CO_User_Collection, CO_Collection, and CO_KeyValue_CO_Collection.
Definition at line 95 of file co_main_db_record.class.php.
{
         $this->_owner_id = intval($in_owner_id);
         $this->_tags = (isset($in_tags_array) && is_array($in_tags_array) && count($in_tags_array)) ? array_map(function($in) { return strval($in); }, $in_tags_array) : Array();
         parent::__construct($in_db_object, $in_db_result);
         $this->class_description = 'Base Class for Main Database Records.';
         $this->name = (isset($this->name) && trim($this->name)) ? trim($this->name) : "Base Class Instance ($this->_id)";
     }
Member Function Documentation
_build_parameter_array()
CO_Main_DB_Record::_build_parameter_array () protected
This adds our data to the saved parameter associative array.
Returns
an associative array of instance values, using the database keys.
Reimplemented from A_CO_DB_Table_Base.
Reimplemented in CO_LL_Location.
Definition at line 72 of file co_main_db_record.class.php.
{
         $ret = parent::_build_parameter_array();    // Start with the base class.
         $ret['owner'] = intval($this->_owner_id);
         for ($tag_no = 0; $tag_no < 10; $tag_no++) {
             $key = "tag$tag_no";
             if (isset($this->_tags[$tag_no])) {
                 $ret[$key] = $this->_tags[$tag_no];
             } else {
                 $ret[$key] = '';
             }
         }
         $ret['payload'] = base64_encode($this->_raw_payload);
         return $ret;
     }
_default_setup()
CO_Main_DB_Record::_default_setup () protected
This prepares an associative array of database values for the object.
Returns
an associative array of default values, using the database keys.
Reimplemented from A_CO_DB_Table_Base.
Reimplemented in CO_LL_Location.
Definition at line 53 of file co_main_db_record.class.php.
{
         $default_setup = parent::_default_setup();
         $default_setup['owner_id'] = $this->_owner_id;
         for ($tag_no = 0; $tag_no < 10; $tag_no++) {
             $key = "tag$tag_no";
             $tag_val = (isset($this->_tags) && is_array($this->_tags) && ($tag_no < count($this->_tags))) ? $this->_tags[$tag_no] : '';
             $default_setup[$key] = $tag_val;
         }
         return $default_setup;
     }
References $_owner_id.
get_payload()
CO_Main_DB_Record::get_payload ()
Returns the payload.
Returns
the payload, in whatever form it takes.
Definition at line 232 of file co_main_db_record.class.php.
{
         return $this->_raw_payload;
     }
References $_raw_payload.
load_from_db()
CO_Main_DB_Record::load_from_db ($in_db_result)
This sets up the instance, based on a supplied associative array of database values and keys.
Returns
true, if sucessful.
Parameters
$in_db_result This is the associative array of database values.
Reimplemented from A_CO_DB_Table_Base.
Reimplemented in CO_User_Collection, CO_US_Place_Collection, CO_Place_Collection, CO_KeyValue_CO_Collection, CO_Collection, and CO_LL_Location.
Definition at line 113 of file co_main_db_record.class.php.
{
         $ret = parent::load_from_db($in_db_result);    // Start by calling the base class version.
         if ($ret) { // If that went OK, we add our own two cents...
             $this->class_description = 'Base Class for Main Database Records.';
             $this->name = (isset($this->name) && trim($this->name)) ? trim($this->name) : "Base Class Instance ($this->_id)";
             if ($this->_db_object) {
                 $this->_owner_id = NULL;
                 $this->_tags = array();
                 $this->_raw_payload = NULL;
                 if (isset($in_db_result['owner'])) {
                     $this->_owner_id = intval($in_db_result['owner']);
                 }
                 if (isset($in_db_result['payload']) ) {
                     $payload = $in_db_result['payload'];
                     $length = strlen($payload);
                     $counter = 0;
                     $new_payload = [];
                     // We decode in chunks.
                     while($counter < $length) {
                         $this_chunk = substr($payload, $counter, 4096);
                         $new_payload[] = base64_decode($this_chunk);
                         $counter += 4096;
                     }
                     $this->_raw_payload = implode('', $new_payload);
                 }
                 for ($tag_no = 0; $tag_no < 10; $tag_no++) {
                     $key = "tag$tag_no";
                     $tag_val = (isset($in_db_result[$key])) && $in_db_result[$key] ? $in_db_result[$key] : '';
                     $this->_tags[$tag_no] = $tag_val;
                 }
                 for ($i = 0; $i < 10; $i++) {
                     $tagname = 'tag'.$i;
                     $this->_tags[$i] = '';
                     if (isset($in_db_result[$tagname])) {
                         $this->_tags[$i] = $in_db_result[$tagname];
                     }
                 }
             }
         }
         return $ret;
     }
owner_id()
CO_Main_DB_Record::owner_id ()
Returns
the current owner ID.
Definition at line 258 of file co_main_db_record.class.php.
{
         return $this->_owner_id;
     }
References $_owner_id.
set_owner_id()
CO_Main_DB_Record::set_owner_id ($in_new_id)
Simple setter for the owner ID.
Returns
true, if successful.
Parameters
$in_new_id The new value
Definition at line 171 of file co_main_db_record.class.php.
{
         $ret = false;
         if (isset($in_new_id) && $this->user_can_write()) {
             $this->_owner_id = intval($in_new_id);
             $ret = $this->update_db();
         }
         return $ret;
     }
References A_CO_DB_Table_Base\update_db(), and A_CO_DB_Table_Base\user_can_write().
set_payload()
CO_Main_DB_Record::set_payload ($in_payload)
Sets the payload.
Returns
true, if successful.
Parameters
$in_payload The raw payload to be stored.
Definition at line 242 of file co_main_db_record.class.php.
{
         $ret = false;
         if ($this->user_can_write()) {
             $this->_raw_payload = $in_payload;
             $ret = $this->update_db();
         }
         return $ret;
     }
References A_CO_DB_Table_Base\update_db(), and A_CO_DB_Table_Base\user_can_write().
set_tag()
CO_Main_DB_Record::set_tag ($in_tag_index, $in_tag_value)
Setter for one tag, by index.
Returns
true, if successful.
Parameters
$in_tag_index The index (0-based -0 through 9) of the tag to set.
$in_tag_value A string, with the tag value.
Reimplemented in CO_User_Collection.
Definition at line 207 of file co_main_db_record.class.php.
{
         $ret = false;
         $in_tag_index = intval($in_tag_index);
         if ((10 > $in_tag_index) && $this->user_can_write()) {
             if (!isset($this->_tags) || !$this->_tags) {
                 $this->_tags = Array();
             }
             $this->_tags[$in_tag_index] = (NULL != $in_tag_value) ? strval($in_tag_value) : NULL;
             $ret = $this->update_db();
         }
         return $ret;
     }
References A_CO_DB_Table_Base\update_db(), and A_CO_DB_Table_Base\user_can_write().
set_tags()
CO_Main_DB_Record::set_tags ($in_tags_array)
Simple setter for the tags.
Returns
true, if successful.
Parameters
$in_tags_array An array of strings, up to ten elements long, for the tags.
Reimplemented in CO_User_Collection.
Definition at line 189 of file co_main_db_record.class.php.
{
         $ret = false;
         if (isset($in_tags_array) && is_array($in_tags_array) && count($in_tags_array) && (11 > count($in_tags_array)) && $this->user_can_write()) {
             $this->_tags = array_map('strval', $in_tags_array);
             $ret = $this->update_db();
         }
         return $ret;
     }
References A_CO_DB_Table_Base\update_db(), and A_CO_DB_Table_Base\user_can_write().
Referenced by CO_Place\set_tags_from_address_elements().
tags()
CO_Main_DB_Record::tags ()
Returns
the current tags.
Definition at line 266 of file co_main_db_record.class.php.
{
         return $this->_tags;
     }
References $_tags.
Referenced by CO_Place\__construct(), CO_User_Collection\_load_login(), CO_User_Collection\has_login(), CO_User_Collection\has_login_i_cant_see(), and CO_User_Collection\is_god().
Member Data Documentation
$_owner_id
CO_Main_DB_Record::$_owner_id protected
Definition at line 41 of file co_main_db_record.class.php.
Referenced by _default_setup(), and owner_id().
$_raw_payload
CO_Main_DB_Record::$_raw_payload private
Definition at line 44 of file co_main_db_record.class.php.
Referenced by get_payload().
$_tags
CO_Main_DB_Record::$_tags protected
Definition at line 42 of file co_main_db_record.class.php.
Referenced by tags().
$s_table_name
CO_Main_DB_Record::$s_table_name = 'co_data_nodes' static
Definition at line 39 of file co_main_db_record.class.php.